english_to_cc = {'genesis':         '創世記',
                 'exodus':          '出埃及記',
                 'leviticus':       '利未記',
                 'numbers':         '民數記',
                 'deuteronomy':     '申命記',
                 'joshua':          '約書亞記',
                 'judges':          '士師記',
                 'ruth':            '路得記',
                 '1 samuel':        '撒母耳記上',
                 '2 samuel':        '撒母耳記下',
                 '1 kings':         '列王紀上',
                 '2 kings':         '列王紀下',
                 '1 chronicles':    '歷代志上',
                 '2 chronicles':    '歷代志下',
                 'ezra':            '以斯拉記',
                 'nehemiah':        '尼希米記',
                 'esther':          '以斯帖記',
                 'job':             '約伯記',
                 'psalms':          '詩篇',
                 'proverbs':        '箴言',
                 'ecclesiastes':    '傳道書',
                 'song of songs':   '雅歌',
                 'isaiah':          '以賽亞書',
                 'jeremiah':        '耶利米書',
                 'lamentations':    '耶利米哀歌',
                 'ezekiel':         '以西結書',
                 'daniel':          '但以理書',
                 'hosea':           '何西阿書',
                 'joel':            '約珥書',
                 'amos':            '阿摩司書',
                 'obadiah':         '俄巴底亞書',
                 'jonah':           '約拿書',
                 'micah':           '彌迦書',
                 'nahum':           '那鴻書',
                 'habakkuk':        '哈巴谷書',
                 'zephaniah':       '西番雅書',
                 'haggai':          '哈該書',
                 'Zachariah':       '撒迦利亞書',
                 'malachi':         '瑪拉基書',
                 'matthew':         '馬太福音',
                 'mark':            '馬可福音',
                 'luke':            '路加福音',
                 'john':            '約翰福音',
                 'acts':            '使徒行傳',
                 'romans':          '羅馬人書',
                 '1 corinthians':   '哥林多前書',
                 '2 corinthians':   '哥林多後書',
                 'galatians':       '加拉太書',
                 'ephesians':       '以弗所書',
                 'phillipians':     '腓立比書',
                 'colossians':      '歌羅西書',
                 '1 thessalonians': '帖撒羅尼迦前書',
                 '2 thessalonians': '帖撒羅尼迦後書',
                 '1 timothy':       '提摩太前書',
                 '2 timothy':       '提摩太後書',
                 'titus':           '提多書',
                 'philemon':        '腓利門書',
                 'hebrews':         '希伯來書',
                 'james':           '雅各書',
                 '1 peter':         '彼得前書',
                 '2 peter':         '彼得後書',
                 '1 john':          '約翰一書',
                 '2 john':          '約翰二書',
                 '3 john':          '約翰三書',
                 'jude':            '猶大書',
                 'revelations':     '啟示錄'}
