abbreviations = {"genesis":         "Gen",
                 "exodus":          "Exod",
                 "leviticus":       "Lev",
                 "numbers":         "Num",
                 "deuteronomy":     "Deut",
                 "joshua":          "Josh",
                 "judges":          "Judg",
                 "ruth":            "Ruth",
                 "1 samuel":        "1Sam",
                 "2 samuel":        "2Sam",
                 "1 kings":         "1Kgs",
                 "2 kings":         "2Kgs",
                 "1 chronicles":    "1Chr",
                 "2 chronicles":    "2Chr",
                 "ezra":            "Ezra",
                 "nehemiah":        "Neh",
                 "esther":          "Esth",
                 "job":             "Job",
                 "psalms":          "Ps",
                 "proverbs":        "Prov",
                 "ecclesiastes":    "Eccl",
                 "song of songs":   "Song",
                 "isaiah":          "Isa",
                 "jeremiah":        "Jer",
                 "lamentations":    "Lam",
                 "ezekiel":         "Ezek",
                 "daniel":          "Dan",
                 "hosea":           "Hos",
                 "joel":            "Joel",
                 "amos":            "Amos",
                 "obadiah":         "Obad",
                 "jonah":           "Jonah",
                 "micah":           "Mic",
                 "nahum":           "Nah",
                 "habakkuk":        "Hab",
                 "zephaniah":       "Zeph",
                 "haggai":          "Hag",
                 "Zachariah":       "Zech",
                 "malachi":         "Mal",
                 "matthew":         "Matt",
                 "mark":            "Mark",
                 "luke":            "Luke",
                 "john":            "John",
                 "acts":            "Acts",
                 "romans":          "Rom",
                 "1 corinthians":   "1Cor",
                 "2 corinthians":   "2Cor",
                 "galatians":       "Gal",
                 "ephesians":       "Eph",
                 "phillipians":     "Phil",
                 "colossians":      "Col",
                 "1 thessalonians": "1Thess",
                 "2 thessalonians": "2Thess",
                 "1 timothy":       "1Tim",
                 "2 timothy":       "2Tim",
                 "titus":           "Titus",
                 "philemon":        "Phlm",
                 "hebrews":         "Heb",
                 "james":           "Jas",
                 "1 peter":         "1Pet",
                 "2 peter":         "2Pet",
                 "1 john":          "1John",
                 "2 john":          "2John",
                 "3 john":          "3John",
                 "jude":            "Jude",
                 "revelations":     "Rev"}
