english_to_japanese = {'genesis':         '創世記(文語訳)',
                       'exodus':          '出エジプト記(文語訳)',
                       'leviticus':       'レビ記(文語訳)',
                       'numbers':         '民數紀略(文語訳)',
                       'deuteronomy':     '申命記(文語訳)',
                       'joshua':          'ヨシュア記(文語訳)',
                       'judges':          '士師記(文語訳)',
                       'ruth':            'ルツ記(文語訳)',
                       '1 samuel':        'サムエル前書(文語訳)',
                       '2 samuel':        'サムエル後書(文語訳)',
                       '1 kings':         '列王紀略上(文語訳)',
                       '2 kings':         '列王紀略下(文語訳)',
                       '1 chronicles':    '歴代志略上(文語訳)',
                       '2 chronicles':    '歴代志略下(文語訳)',
                       'ezra':            'エズラ書(文語訳)',
                       'nehemiah':        'ネヘミヤ記(文語訳)',
                       'esther':          'エステル書(文語訳)',
                       'job':             'ヨブ記(文語訳)',
                       'psalms':          '詩篇(文語訳)',
                       'proverbs':        '箴言(文語訳)',
                       'ecclesiastes':    '傳道之書(文語訳)',
                       'song of songs':   '雅歌(文語訳)',
                       'isaiah':          'イザヤ書(文語訳)',
                       'jeremiah':        'ヱレミヤ記(文語訳)',
                       'lamentations':    'エレミヤの哀歌(文語訳)',
                       'ezekiel':         'エゼキエル書(文語訳)',
                       'daniel':          'ダニエル書(文語訳)',
                       'hosea':           'ホセア書(文語訳)',
                       'joel':            'ヨエル書(文語訳)',
                       'amos':            'アモス書(文語訳)',
                       'obadiah':         'オバデヤ書(文語訳)',
                       'jonah':           'ヨナ書(文語訳)',
                       'micah':           'ミカ書(文語訳)',
                       'nahum':           'ナホム書(文語訳)',
                       'habakkuk':        'ハバクク書(文語訳)',
                       'zephaniah':       'ゼパニヤ書(文語訳)',
                       'haggai':          'ハガイ書(文語訳)',
                       'Zachariah':       'ゼカリヤ書(文語訳)',
                       'malachi':         'マラキ書(文語訳)',
                       'matthew':         '馬太傳福音書(明治元訳)',
                       'mark':            '馬可傳福音書(明治元訳)',
                       'luke':            '路加傳福音書(明治元訳)',
                       'john':            '約翰傳福音書(明治元訳)',
                       'acts':            '使徒行傳(明治元訳)',
                       'romans':          '羅馬書(明治元訳)',
                       '1 corinthians':   '哥林多前書(明治元訳)',
                       '2 corinthians':   '哥林多後書(明治元訳)',
                       'galatians':       '加拉太書(明治元訳)',
                       'ephesians':       '以弗所書(明治元訳)',
                       'phillipians':     '腓立比書(明治元訳)',
                       'colossians':      '哥羅西書(明治元訳)',
                       '1 thessalonians': '帖撒羅尼迦前書(明治元訳)',
                       '2 thessalonians': '帖撒羅尼迦後書(明治元訳)',
                       '1 timothy':       '提摩太前書(明治元訳)',
                       '2 timothy':       '提摩太後書(明治元訳)',
                       'titus':           '提多書(明治元訳)',
                       'philemon':        '腓利門書(明治元訳)',
                       'hebrews':         '希伯來書(明治元訳)',
                       'james':           '雅各書(明治元訳)',
                       '1 peter':         '彼得前書(明治元訳)',
                       '2 peter':         '彼得後書(明治元訳)',
                       '1 john':          '約翰第一書(明治元訳)',
                       '2 john':          '約翰第二書(明治元訳)',
                       '3 john':          '約翰第三書(明治元訳)',
                       'jude':            '猶太書(明治元訳)',
                       'revelations':     '約翰默示録(明治元訳)'}
