import re

versions = {
    "afrikaans":         ['Ou Vertaling (aov)'],
    "albanian":          ['Albanian (albanian)', 'Albanian Bible (ALB)'],
    "amharic":           ['Amharic NT (amharic)', 'Haile Selassie Amharic Bible (hsab)'],
    "arabic":            ['Smith and Van Dyke (arabicsv)', 'Arabic Bible: Easy-to-Read Version (erv-ar)',
                          'Ketab El Hayat (nav)'],
    "awadhi":            ["Awadhi Bible: Easy-to-Read Version (ERV-AWA)"],
    "aramaic":           ['Peshitta NT (peshitta)'],
    "armenian":          ['Eastern (Genesis Exodus Gospels) (easternarmenian)', 'Western NT (westernarmenian)'],
    "basque":            ['(Navarro Labourdin) NT (basque)'],
    "breton":            ['Gospels (breton)'],
    "bulgarian":         ['Bulgarian Bible (1940) (bulgarian1940)', '1940 Bulgarian Bible (BG1940)',
                          'Bulgarian Bible (BULG)', 'Bulgarian New Testament: Easy-to-Read Version (ERV-BG)'],
    "chamorro":          ['(Psalms Gospels Acts) (chamorro)'],
    "chinese":           ['Chinese Contemporary Bible (Traditional) (CCBT)', 'NCV Simplified (cns)',
                          'NCV Traditional (cnt)', 'Union Simplified (cus)',
                          'Union Traditional (cut)', 'Chinese Contemporary Bible (Simplified) (CCB)'
                                                     'Chinese New Testament: Easy-to-Read Version (ERV-ZH)'],
    "classical chinese": ['Classical Chinese (cc)'],
    "coptic":            ['New Testament (coptic)', 'Bohairic NT (bohairic)', 'Sahidic NT (sahidic)'],
    "croatian":          ['Croatian (croatia)', 'Hrvatski Novi Zavjet (HNZ-RI)'],
    "czech":             ['Czech BKR (bkr)', 'Czech CEP (cep)', 'Czech KMS (kms)', 'Czech NKB (nkb)', 'Bible 21 (B21)',
                          'Slovo na cestu (SNC) NT'],
    "danish":            ['Danish (danish)', 'Bibelen på hverdagsdansk (BPH)', 'Dette er Biblen på dansk (DN1933)'],
    "dutch":             ['Dutch Staten Vertaling (statenvertaling)', 'BasisBijbel (BB)', 'Het Boek (HTB)'],
    "english":           ['King James Version (kjv)', 'American King James Version (akjv)',
                          'American Standard Version (asv)', 'Basic English Bible (basicenglish)',
                          'Douay Rheims (douayrheims)', "Webster's Bible (wb)", 'Weymouth NT (weymouth)',
                          'World English Bible (web)', "Young's Literal Translation (ylt)",
                          'Century King James Version (KJ21)', 'American Standard Version (ASV)',
                          'Amplified Bible (AMP)', 'Classic Edition (AMPC)', 'BRG Bible (BRG)',
                          'Christian Standard Bible (CSB) ', 'Common English Bible (CEB) with Apocrypha',
                          'Complete Jewish Bible (CJB)', 'Contemporary English Version (CEV)',
                          'Darby Translation (DARBY)', 'Disciples’ Literal New Testament (DLNT) NT',
                          'Douay-Rheims 1899 American Edition (DRA) with Apocrypha', 'Easy-to-Read Version (ERV)',
                          'Evangelical Heritage Version (EHV)', 'English Standard Version (ESV) ',
                          'English Standard Version Anglicised (ESVUK)', 'Expanded Bible (EXB)',
                          '1599 Geneva Bible (GNV) ', 'GOD’S WORD Translation (GW)',
                          'Good News Translation (GNT) with Apocrypha', 'Holman Christian Standard Bible (HCSB) ',
                          'International Children’s Bible (ICB)', 'International Standard Version (ISV)',
                          'J.B. Phillips New Testament (PHILLIPS) NT', 'Jubilee Bible 2000 (JUB)',
                          'King James Version (KJV) ', 'Authorized (King James) Version (AKJV)',
                          'Lexham English Bible (LEB) ', 'Living Bible (TLB)', 'The Message (MSG) ',
                          'Modern English Version (MEV)', 'Mounce Reverse-Interlinear New Testament (MOUNCE) NT',
                          'Names of God Bible (NOG)', 'New American Bible (Revised Edition) (NABRE)',
                          'New American Standard Bible (NASB) ', 'New Century Version (NCV)',
                          'New English Translation (NET Bible)', "New International Reader's Version (NIRV)",
                          'New International Version (NIV) ', 'New International Version - UK (NIVUK) ',
                          'New King James Version (NKJV)', 'New Life Version (NLV)', 'New Living Translation (NLT)',
                          'New Matthew Bible (NMB) NT', 'New Revised Standard Version (NRSV) with Apocrypha',
                          'Anglicised (NRSVA) with Apocrypha', 'Anglicised Catholic Edition (NRSVACE)',
                          'New Revised Standard Version Catholic Edition (NRSVCE)',
                          'New Testament for Everyone (NTE) NT', 'Orthodox Jewish Bible (OJB)',
                          'The Passion Translation (TPT)', 'Revised Standard Version (RSV) with Apocrypha',
                          'Revised Standard Version Catholic Edition (RSVCE)', 'Tree of Life Version (TLV)',
                          'The Voice (VOICE)', 'World English Bible (WEB)', 'Worldwide English (New Testament) (WE) NT',
                          'Wycliffe Bible (WYC) with Apocrypha', "Young's Literal Translation (YLT)"],
    "esperanto":         ['Esperanto (esperanto)'],
    "estonian":          ['Estonian (estonian)'],
    "finnish":           ['Finnish Bible (1776) (finnish1776)', 'Pyha Raamattu (1933 1938) (pyharaamattu1933)',
                          'Pyha Raamattu (1992) (pyharaamattu1992)', 'Raamattu 1933/38 (R1933)'],
    "french":            ['Darby (darby)', 'Louis Segond (1910) (ls1910)', 'Martin (1744) (martin)',
                          'Ostervald (1996 revision) (ostervald)', 'La Bible du Semeur (BDS)', 'Louis Segond (LSG)',
                          'Nouvelle Edition de Genève (NEG1979)'],
    "georgian":          ['Georgian (Gospels Acts James) (georgian)'],
    "german":            ['Elberfelder (1871) (elberfelder)', 'Elberfelder (1905) (elberfelder1905)',
                          'Luther (1545) (luther1545)', 'Luther (1912) (luther1912)', 'Schlachter (1951) (schlachter)',
                          'Hoffnung für Alle (HOF)', 'Luther Bibel 1545 (LUTH1545)',
                          'Neue Genfer Übersetzung (NGU-DE) NT', 'Schlachter 1951 (SCH1951)',
                          'Schlachter 2000 (SCH2000)'],
    "gothic":            ['Gothic (Nehemiah NT Portions) (gothic)'],
    "greek":             ['OT LXX Accented (lxx)', 'Greek Modern (moderngreek)',
                          'NT Byzantine Majority Text (2000) Parsed (majoritytext)',
                          'NT Byzantine Majority Text (2000) (byzantine)',
                          'NT Textus Receptus (1550 1894) Parsed (textusreceptus)', 'Textus Receptus (text)',
                          'NT Tischendorf 8th Ed (tischendorf)', 'NT Westcott Hort UBS4 variants Parsed (westcotthort)',
                          'NT Westcott Hort UBS4 variants (westcott)',
                          'OT LXX Unaccented (lxxunaccents)', '1550 Stephanus New Testament (TR1550) NT',
                          '1881 Westcott-Hort New Testament (WHNU) NT', '1894 Scrivener New Testament (TR1894) NT',
                          'SBL Greek New Testament (SBLGNT) NT'],
    "hebrew":            ['OT WLC (Consonants and Vowels) (wlc)', 'Aleppo Codex (aleppo)',
                          'Hebrew Modern (modernhebrew)',
                          'OT BHS (Consonants Only) (bhsnovowels)', 'OT BHS (Consonants and Vowels) (bhs)',
                          'OT WLC (Consonants Only) (wlcnovowels)',
                          'OT Westminster Leningrad Codex (codex)', 'Habrit Hakhadasha/Haderekh (HHH) NT',
                          'The Westminster Leningrad Codex (WLC) OT'],
    "hungarian":         ['Hungarian Karoli (karoli)', 'Hungarian Károli (KAR)',
                          'Hungarian Bible: Easy-to-Read Version (ERV-HU)'],
    "italian":           ['Giovanni Diodati Bible (1649) (giovanni)', 'Riveduta Bible (1927) (riveduta)',
                          'La Bibbia della Gioia (BDG) NT', 'Conferenza Episcopale Italiana (CEI) with Apocrypha',
                          'La Nuova Diodati (LND)', 'Nuova Riveduta 1994 (NR1994)', 'Nuova Riveduta 2006 (NR2006)'],
    "kabyle":            ['Kabyle NT (kabyle)'],
    "korean":            ['Korean (korean)', 'Korean Living Bible (KLB)'],
    "latin":             ['Vulgata Clementina (vulgate)', 'Nova Vulgata (newvulgate)'],
    "latvian":           ['New Testament (latvian)'],
    "lithuanian":        ['Lithuanian (lithuanian)'],
    "manx_gaelic":       ['Manx Gaelic (Esther Jonah 4 Gospels) (manxgaelic)'],
    "maori":             ['Maori (maori)', 'Maori Bible (MAORI)'],
    "myanmar_burmse":    ['Judson (1835) (judson)'],
    "old english":       ['West Saxon Translation (old_english)'],
    "norwegian":         ['Det Norsk Bibelselskap (1930) (bibelselskap)', 'Det Norsk Bibelselskap 1930 (DNB1930)',
                          'En Levende Bok (LB) NT'],
    "portuguese":        ['Almeida Atualizada (almeida)', 'Almeida Revista e Corrigida 2009 (ARC)',
                          'Nova Traduҫão na Linguagem de Hoje 2000 (NTLH)', 'Nova Versão Transformadora (NVT)',
                          'Nova Versão Internacional (NVI-PT) ', 'O Livro (OL)',
                          'Portuguese New Testament: Easy-to-Read Version (VFL)'],
    "potawatomi":        ['Potawatomi (Matthew Acts) (Lykins 1844) (potawatomi)'],
    "romani":            ['Romani NT E Lashi Viasta (Gypsy) (rom)'],
    "romanian":          ['Cornilescu (cornilescu)', 'Cornilescu 1924 - Revised 2010, 2014 (RMNN)',
                          'Nouă Traducere În Limba Română (NTLR)'],
    "russian":           ['Synodal Translation (synodal)', 'Makarij Translation Pentateuch (makarij)',
                          'Victor Zhuromsky NT (zhuromsky)', 'New Russian Translation (NRT)',
                          'Russian New Testament: Easy-to-Read Version (ERV-RU)'],
    "scottish_gaelic":   ['Scots Gaelic (Gospel of Mark) (gaelic)'],
    "spanish":           ['Reina Valera (1909) (valera)', 'Reina Valera NT (1858) (rv1858)',
                          'Sagradas Escrituras (1569) (sse)', 'La Biblia de las Américas (LBLA) ',
                          'Dios Habla Hoy (DHH) with Apocrypha', 'Jubilee Bible 2000 (Spanish) (JBS)',
                          'Nueva Biblia Latinoamericana de Hoy (NBLH)', 'Nueva Biblia Viva (NBV)',
                          'Nueva Traducción Viviente (NTV)', 'Nueva Versión Internacional (Castilian) (CST)',
                          'Nueva Versión Internacional (NVI) ', 'Palabra de Dios para Todos (PDT)',
                          'La Palabra (España) (BLP)', 'La Palabra (Hispanoamérica) (BLPH)',
                          'Reina Valera Actualizada (RVA-2015)', 'Reina Valera Contemporánea (RVC)',
                          'Reina-Valera 1960 (RVR1960)', 'Reina Valera Revisada (RVR1977)',
                          'Reina-Valera 1995 (RVR1995)', 'Reina-Valera Antigua (RVA)',
                          'Spanish Blue Red and Gold Letter Edition (SRV-BRG)',
                          'Traducción en lenguaje actual (TLA) with Apocrypha'],
    "swahili":           ['Swahili (swahili)', 'Swedish (1917) (swedish)', 'Neno: Bibilia Takatifu (SNT)'],
    "tagalog":           ['Ang Dating Biblia (1905) (tagalog)', 'Ang Bagong Tipan: Filipino Standard Version (FSV)'],
    "tamajaq":           ['Tamajaq Portions (tamajaq)'],
    "thai":              ['Thai from kjv (thai)', 'Thai New Contemporary Bible (TNCV) ',
                          'Thai New Testament: Easy-to-Read Version (ERV-TH)'],
    "turkish":           ['NT (1987 1994) (tnt)', 'Turkish (turkish)'],
    "ukrainian":         ['Bible (UKR)', 'NT (P Kulish 1871) (ukranian)',
                          'Ukrainian New Testament: Easy-to-Read Version (ERV-UK)'],
    "uma":               ['Uma NT (uma)'],
    "vietnamese":        ['Vietnamese (1934) (vietnamese)', 'Viêt 1934 Vietnamese Bible (VIET)',
                          'Bản Dịch 2011 (BD2011)', 'New Vietnamese Bible (NVB)',
                          'Vietnamese Bible: Easy-to-Read Version (BPT)'],
    "wolof":             ['Wolof NT (wolof)'],
    "xhosa":             ['Xhosa (xhosa)'],
    "amuzgo guerrero":   ['Amuzgo de Guerrero Amuzgo de Guerrero (AMU) NT'],
    "awadhi":            ['Awadhi Bible: Easy-to-Read Version (ERV-AWA)', 'Pavithar Bible (New India Bible Version)'],
    "cebuano":           ['Pulong Sa Dios (APSD-CEB) NT'],
    "cherokee":          ['ᎦᏬᏂᎯᏍ Cherokee New Testament (CHR) NT'],
    "kaqchikel":         ['Occidental Cakchiquel Occidental (CKW) NT'],
    "welsh":             ['Beibl William Morgan (BWM)'],
    "hindi":             ['Hindi Bible: Easy-to-Read Version (ERV-HI)'],
    "hiligaynon":        ['Ang Pulong Sang Dios (HLGN)'],
    "icelandic":         ['Icelandic Bible (ICELAND)'],
    "japanese":          ['Japanese Living Bible (JLB)', 'Japanese Meiji Bible (MEIJI)'],
    "jakaltek":          ['Jacalteco (JAC)'],
    "kekchi":            ['Kekchi (KEK) NT'],
    "macedonian":        ['Macedonian New Testament (MNT) NT'],
    "marathi":           ['Marathi Bible: Easy-to-Read Version (ERV-MR)'],
    "mam":               ['Central Mam (MVC) NT', 'Mam de Todos Santos Chuchumatán (MVJ) NT'],
    "low german":        ['Plautdietsch Reimer 2001 (REIMER) NT'],
    "nepali":            ['Nepali Bible: Easy-to-Read Version (ERV-NE)'],
    "nahuatl":           ['de Guerrero Náhuatl de Guerrero (NGU) NT'],
    "oriya":             ['Oriya Bible (ERV-OR)'],
    "punjabi":           ['Punjabi Bible (ERV-PA)'],
    "polish":            ['Nowe Przymierze (NP) NT', 'Słowo Życia (SZ-PL) NT', 'Updated Gdańsk Bible (UBG) NT'],
    "pipil":             ['Ne Bibliaj Tik Nawat (NBTN) NT'],
    "quichua":           ['Testamento Diospaj Shimi (MTDS) NT'],
    "kiche":             ['Centro Occidental (QUT) NT'],
    "slovak":            ['Nádej pre kazdého (NPK) NT'],
    "somali":            ['Bible (SOM)'],
    "serbian":           ['Serbian New Testament: Easy-to-Read Version (ERV-SR)'],
    "swedish":           ['nuBibeln (Swedish Contemporary Bible) (NUB)', 'Svenska 1917 (SV1917)',
                          'Svenska Folkbibeln (SFB)', 'Svenska Folkbibeln 2015 (SFB15)'],
    "tamil":             ['Tamil Bible (ERV-TA)'],
    "twi":               ['Asem (NA-TWI) NT'],
    "urdu":              ['Urdu Bible: Easy-to-Read Version (ERV-UR)'],
    "uspanteko":         ['Uspanteco (USP) NT']
    }

all_versions = set()
for v in versions.values():
    for version in v:
        lang_version = re.findall(r'\(.*?\)', version)[-1].replace("(", "").replace(")", "")
        all_versions.add(lang_version.lower())

lang_to_versions = {}
for lang, versions_for_lang in versions.items():
    versions_set = []
    for version in versions_for_lang:
        lang_version = re.findall(r'\(.*?\)', version)[-1].replace("(", "").replace(")", "")
        versions_set.append(lang_version.lower())
    lang_to_versions[lang] = versions_set
