transliteratable_versions = {'coptic':    ['bohairic', 'sahidic', 'coptic'],
                             'aramaic':   ['peshitta'],
                             'latin':     ['vulgate', 'newvulgates'],
                             'hebrew':    ['aleppo', 'modernhebrew', 'bhsnovowels', 'bhs', 'wlcnovowels', 'wlc',
                                           'codex'],
                             'arabic':    ['arabicsv', 'nav', 'erv-ar'],
                             'greek':     ['moderngreek', 'majoritytext',
                                           'byzantine', 'textusreceptus', 'text',
                                           'tischendorf', 'westcotthort',
                                           'westcott', 'lxxpar', 'lxx',
                                           'lxxunaccentspar', 'lxxunaccents',
                                           'sblgnt'],
                             'russian':   ['makarij', 'synodal', 'zhuromsky'],
                             'ukrainian': ['ukr', 'ukrainian', 'ukr-uk'],
                             'bulgarian': ['bg1940', 'bulgarian1940', 'bulg', 'erv-bg'], 'serbian': ['erv-sr'],
                             'georgian':  ['georgian'], 'armenian': ['westernarmenian', 'easternarmenian'],
                             'korean':    ['korean', 'klb'],
                             'chinese':   ['ccb', 'ccbt', 'erv-zh', 'cns', 'cnt', 'cus', 'cut', 'cc'],
                             'japanese':  ['meiji', 'jlb']}
