mark = {
"1":      {
    "1":  "Her ys godspellys angyn Hælyndes cristes godes suna.",
    "2":  "Swa áwriten is on þæs witegan béc isaiam. nu ic asénde minne engel be-foran þinre ansyne. Se ge-gearwað þinne weg be-foran ðe.",
    "3":  "clypiende stefn on þam westene ge-gearwiað drihtnes weg. doð rihte his siðas;",
    "4":  "Iohannes wæs on westene fulligende and bodiende dædbote fulwiht on synna for-gyfenesse.",
    "5":  "And to him ferde eall iudeisc rice. and ealle hierosolima-ware. and wæron fram him gefullode. on iordanes flode hyra synna anddetenne;",
    "6":  "And iohannes wæs gescryd mid oluendes hærum. and fellen gyrdel wæs ymbe his lendenu. and gærstapan and wudu hunig he æt.",
    "7":  "And he bodude and cwæð. strengra cymð æfter me. þæs ne eom ic wyrðe þæt ic his sceona þwanga bugende uncnytte.",
    "8":  "Ic fullige eow on wætere. he eow fullað on halgum gaste.",
    "9":  "And on ðam dagum cóm se hælend fram nazareth galilee and wæs ge-fullod on iordané fram iohanne.",
    "10": "And sona of ðam wætere he geseah opene heofonas. and haligne gast swa culfran astigende and on him wunigende.",
    "11": "And þa wæs stefn of heofenum geworden. þu eart min ge-lufoda sunu on þe ic gelicode;",
    "12": "And sona gast hine on westen genydde.",
    "13": "And he on wéstene wæs feowertig daga and feowertig nihta. and he wæs fram satane gecostnod. and he mid wilddeorum wæs and him englas þenodon;",
    "14": "Syððan iohannes geseald wæs. com se hælend on galileam godes rices. godspell bodigende",
    "15": "And þus cweðende. witodlice tíd is gefylled and heofena ríce genealæcð. doð dæd-bote and gelyfaþ þam godspelle.",
    "16": "And þa he ferde wið þa galileiscan sæ. he geseah simonem and andream his broðor hyra nett on þa sæ lætende. Soðlice hi wæron fisceras;",
    "17": "And þa cwæð se hælend cumað æfter me and ic dó inc þæt gyt beoð sawla onfonde.",
    "18": "And hi þa hrædlice him fyligdon. and for-leton heora net.",
    "19": "And ðanon hwón agán he geseah iacobum and zebedei and iohannes his broðor. and hi on heora scype heora nett logodon.",
    "20": "And he hi sona clypode. and hi heora fæder zebedeo on scipe forleton. mid hyrlingum.",
    "21": "And ferdon to cafarnaum and sona reste-dagum he lærde hi on gesamnunge. ingancgende",
    "22": "And hi wundredon be his láre; Soþlice he wæs hi lærende swa se þe anweald hæfð. næs swa boceras.",
    "23": "And on heora gesamnunge wæs sum man. on unclænum gaste and he hrymde",
    "24": "And cwæð eala nazarenisca hælend hwæt is us and þe. com ðu us to for-spillanne. ic wat þu eart godes halga;",
    "25": "Ða cidde se hælend him and cwæð adumba. and gá of þisum men.",
    "26": "And se unclæna gast hine slitende and mycelre stefne clypiende him of eode;",
    "27": "Þa wundredon hi ealle swa þæt hi betwux him cwædon. hwæt ys þis. hwæt is þeos niwe lár. þæt he on anwealde unclænum gastum bebyt. and hi hyrsumiað him.",
    "28": "And sona ferde his hlísa to galilea rice;",
    "29": "Hrædlice of hyra gesamnunge hi comon on simonis and andreas hus. mid iacobe and Iohanne;",
    "30": "Soðlice þa sæt simonis swegr hriðigende and hi him be hyre sædon.",
    "31": "And ge-nealæcende he hi up ahóf hyre handa ge-gripenre. and hrædlice se fefor hi forlet. and heo þenode him;",
    "32": "Soðlice þa hit wæs æfen geworden þa sunne to setle eode. hi brohton to him ealle þa unhalan. and þa ðe wóde wæron.",
    "33": "And eall seo burh-waru wæs ge-gaderod to þære duran.",
    "34": "And he manega gehælde þe missenlicum ádlum gedrehte wæron. and manega deofol-seocnyssa he ut adraf. and hi sprecan ne lét. forþam hi wiston þæt he crist wæs;",
    "35": "And swiðe ær arisende he ferde. on wéste stowe and hine þar gebæd",
    "36": "And him fyligde simon. and þa ðe mid him wæron.",
    "37": "And þa hi hine gemetton hi sædon him. eall þis folc ðe secð;",
    "38": "Þa cwæð he fare we on ge-hende túnas and ceastra. þæt ic ðar bodige. witodlice to ðam ic com.",
    "39": "And he wæs bodigende on heora ge-samnungum and ealre galilea. and deofol-seocnessa ut adrifende;",
    "40": "And to him com sum hreofla hine biddende. and gebigedum cneowum him to cwæþ; Drihten. gif þu wylt ðu miht ge-clænsian me;",
    "41": "Soðlice se hælend him ge-miltsode. and his hand aþenode and hine æt-hrinende and þus cwæð; Ic wylle. beo ðu geclænsod.",
    "42": "And þa he ðus cwæð sona seo hreofnys him fram ge-wát. and he wæs geclænsod.",
    "43": "And sona he bead him",
    "44": "And cwæð. warna þæt ðu hit nanum men ne secge. ac gá and æt-yw ðe þara sacerda ealdre. and bring for ðinre clænsunga þæt moyses bebead him on ge-witnesse.",
    "45": "And he þa ut-gangende ongan bodian and widmærsian þa spræce; Swa þæt he ne mihte openlice on þa ceastre gán. ac beon úte on westum stowum and hi æghwanon to him comon."},

    "2":  {
        "1":  "And eft æfter dagum he eode into cafarnaum. and hit wæs ge-hyred þæt he wæs on huse",
        "2":  "And manega togædere comon. and he to heom spræc.",
        "3":  "And hi comon anne laman to him berende. þone feower men bæron.",
        "4":  "And þa hí ne mihton hine inbringan for þære mænigu. hi openodon þone hróf þar se hælend wæs. and hi þa in-asendan. þæt bed þe se lama on læg;",
        "5":  "Soðlice ða se hælend geseah heora geleafan. he cwæð to þam laman; Sunu þe synt þine synna for-gyfene.",
        "6":  "Þar wæron sume of ðam bocerum sittende. and on heora heortum þencende",
        "7":  "hwí spycð þes þus. he dysegað. hwa mæg synna for-gyfan buton god ána;",
        "8":  "Ða se hælend þæt on his gaste oncneow. þæt hi swa betwux him þohton. he cwæð to him. hwi ðence ge þas ðing on eowrum heortan.",
        "9":  "hwæðer is eðre to secgenne to þam laman. þe synd ðine synna forgyfene. hwæðer þe cweðan arís nim ðín bed and gá.",
        "10": "þæt ge soðlice witon þæt mannes sunu hæfð anweald on eorðan; synna to for-gyfanne; He cwæð to þam láman",
        "11": "þe ic secge arís. nim þin bed. and gá to þinum huse",
        "12": "And he sona aras. and be-foran him eallum eode; Swa þæt ealle wundredon and þus cwædon. næfre wé ær þyllic ne ge-sawon.",
        "13": "eft he ut eode to ðære sæ. and eall seo menigeo him to com and he hi lærde.",
        "14": "And þa he forð eode he ge-seah leuin alphei. sittende æt his cep-setle. and he cwæð to him folga mé. þa aras he and folgode him.",
        "15": "And hit gewearð þa he sæt on his húse þæt manega manfulle. sæton mid þam hælende and his leorning-cnihtum; Soðlice manega þa ðe him fyligdon wæron",
        "16": "boceras and farisei. and cwædon. witodlice he ýtt mid mánfullum and synfullum. and hi cwædon to his leorning-cnihtum. hwi ytt eower lareow and drincð. mid manfullum and synfullum;",
        "17": "Þa se hælend þis ge-hyrde he sæde him. ne beþurfon na ða halan læces. ac ða þe untrume synt; Ne com ic na þæt ic clypode riht-wise ac synfulle.",
        "18": "And þa wæron Iohannes leorning-cnihtas and pharisei fæstende. and þa comon hi and sædon him; Hwi fæstað iohannes leorning-cnihtas and phariseorum. and þine ne fæstað;",
        "19": "Ða .cw. se hælend. cweðe ge sceolan þæs brydguman cnihtas fæstan swa lange swa se brydguma mid him is. ne magon hi fæstan swa lange tíde swa hi ðone brydguman mid him habbað;",
        "20": "Soðlice þa dagas cumað þonne se brydguma him bið fram acyrred. and þonne hi fæstað; On þam dagum",
        "21": "nán man ne síwaþ níwne scýp to ealdum reafe elles he afyrð þone níwan scyp. of þam ealdan reafe. and biþ mare slite.",
        "22": "And nán man ne deð niwe win on ealde bytta. elles þæt wín tobrycð þa bytta. and þæt wín bið agoten. and þa bytta forwurðaþ; Ac niwe wín sceal beon gedon on níwe bytta. þonne beoð butu gehealden;",
        "23": "Eft wæs geworden þa he reste-dagum þurh æceras eode. his leorning-cnihtas ongunnon þa éár pluccigean.",
        "24": "þa cwædon pharisei to him. loca nu hwæt þine leorning-cnihtas doð. þæt him alyfed næs. on reste-dagum;",
        "25": "Þa sæde he him ne rædde ge næfre. hwæt dyde dauid þa hine hingrode. and þa ðe mid him wæron.",
        "26": "hu he in godes huse eode. under abiathár þara sacerda ealdre. and he æt þa ofrung-hlafas. þe him ne alyfede næron to etanne. buton sacerdon anum. and he sealde þam ðe mid him wæron.",
        "27": "And he sæde him. reste-dæg wæs geworht for þa men. næs se man for ðam reste-dæge;",
        "28": "Witodlice drihten is mannes sunu eac swylce reste-dæges;"},

"3":      {
    "1":  "And eft he eode on ge-samnunge and þar wæs án man for-scruncene hand hæbbende",
    "2":  "And hi gymdon hwæþer he on reste-dagum gehælde. þæt hi hine gewregdon;",
    "3":  "Ða cwæð he to ðam men þe for-scruncene hand hæfde. arís gemang him.",
    "4":  "þá cwæð he alyfð reste-dagum wel to dónne hweþer ðe yfele. sawla ge-hælan. hweþer ðe for-spillan. and hí suwodon.",
    "5":  "And hi besceawiende mid yrre ofer hyra heortan blindnesse ge-unrét cwæð to þam men; Aþene þine hand. and he aþenede hi. þa wearð his hand ge-hæled sona;",
    "6":  "Þa pharisei mid herodianiscum utgangende þeahtedon ongen hine. hu hi hine fordon mihton.",
    "7":  "And þa ferde se hælend to þære sæ. mid his leorning-cnihton. and mycel menigeo him fyligde fram galilea. and iudea.",
    "8":  "And hierusalem. and fram iudea and be-geondan iordane and to him com mycel menegeo ymbe tírum and sidóne gehyrende þa ðing þe he worhte.",
    "9":  "And he cwæð to his cnihtum þæt hi him on scipe þenodon. for þære menigu þæt hi hine ne ofþrungon;",
    "10": "Soþlice manega he ge-hælde; Swa þæt hi æt-hrinon his. and swa fela swa untrumnessa",
    "11": "And unclæne gastas hæfdon; Þa hi hine gesawon. hi to-foran him astrehton. and þus cweðende clypedon. þu eart godes sunu.",
    "12": "And he him swyðe forbead. þæt hi hine ne ge-swutelodon.",
    "13": "And on anne munt he ferde and to him ge-clypode þa ðe he wolde and hi to him comon",
    "14": "And he dyde þæt hi twelfe mid him wæron. and he hi asende godspell to bodigenne.",
    "15": "And he him anweald sealde untrumnessa to hælanne. and deofol-seocnessa út to adrifanne.",
    "16": "And he nemde simon petrum",
    "17": "And iacobum zebedei. and iohannem his broðor and him naman onsette. boaneries þæt is ðunres bearn.",
    "18": "And andream. and philippum. and bartholomeum and thomam. and iacobum alphei. and taddeum. and simonem chananeum.",
    "19": "And iudam scarioth. se hine sealde.",
    "20": "And eft him to com. swa micel menigu. þæt hi næfdon hlaf to etanne",
    "21": "And þa hi hine gehyrdon hi ferdon þæt hi hine namon and þus cwædon; Soðlice he is on hat-heortnesse gewend.",
    "22": "And þa boceras þe wendon fram hierusalem cwædon; Soþlice he hæfð beelzebub and on deofla ealdre he deoful-seocnessa ut adrífð.",
    "23": "And he hi togædere geclypode. and on bigspellum him to cwæð; Hu mæg satanas satanan ut adrifan.",
    "24": "And gif his rice on him sylfum bið to-dæled hu mæg hit standan",
    "25": "And gif þæt hus ofer hit sylf ys to-dæled. hu mæg hit standan",
    "26": "And gif satanas winð ongen hine sylfne he bið to-dæled and he standan ne mæg ac hæfð ende;",
    "27": "Ne mæg man þone strangan his æhta and his fatu be-reafian and on his hus gan, buton man þone strangan ærest gebinde. and þonne his hus reafige;",
    "28": "Soðlice ic eow secge þæt ealle synna synd manna bearnum forgyfene. and bysmorunga þam ðe hi bysmeriað;",
    "29": "Soþlice ic eow secge se þe ðone halgan gast bysmerað. se næfð on ecnysse forgyfenesse; Ac bið éces gyltes scyldig.",
    "30": "forþam þe hi cwædon he hæfð unclænne gast.",
    "31": "Þa com to him his modor and his gebroðra. and þar-ute stodon and to him sendon. and to him clypedon.",
    "32": "And mycel menigu ymb hine sæt and to him cwædon. her is þin modor and þine gebroðra úte and secaþ þe;",
    "33": "He þa him andswarode and cwæð. hwylc is min modor and mine gebroþru.",
    "34": "And he cwæþ ða behealdende þe him abuton sæton. her is min modor and mine gebroðru;",
    "35": "Soðlice se ðe déþ godes willan se is min modor and min broðor and swustor."},

    "4":  {
        "1":  "And eft he ongan hi æt þære sæ læran. and him wæs mycel menegu togegaderod; Swa þæt he on scip eode. and on þære sæ wæs. and eall seo menegu ymbe þa [sæ] wæron on lande.",
        "2":  "And he hi fela on bigspellum lærde. and him to cwæð on his lare.",
        "3":  "gehyrað; +Ut eode se sædere his sæd to sawenne.",
        "4":  "And þa he sew sum feoll wið þone weg. and fugelas comon and hit fræton;",
        "5":  "Sum feoll ofer stan-scyligean þar hit næfde mycele eorðan. and sona úp eóde. and forþam hit næfde eorþan þiccnesse.",
        "6":  "þa hit up-eode. Seo sunne hit forswælde. and hit forscranc. forþam hit wyrt-ruman næfde.",
        "7":  "And sum feoll on þornas. þa stigon ða þórnas and forðrysmodon þæt. and hit wæstm ne bær.",
        "8":  "And sum feoll on god land and hit sealde upp-stigende and wexende wæstm; and án brohte þritig-fealdne; Sum syxtig-fealdne; Sum hund-fealdne;",
        "9":  "And he cwæð. gehyre se ðe earan hæbbe to gehyranne.",
        "10": "And þa he ana wæs hine axodon þæt bigspell þa twelfe þe mid him wæron.",
        "11": "And he sæde him. eow is geseald to witanne godes ríces gerýnu; Þam þe úte synt ealle þing on bigspellum gewurþað.",
        "12": "þæt hi geseonde geseon and na ne ge-seon and gehyrende gehyren and ne ongyten þe læs hi hwænne sýn gescyrede. and him sín hyra synna forgyfene;",
        "13": "Ða sæde he him. ge nyton þis bigspell. and hu mage ge ealle bigspell witan;",
        "14": "Se þe sæwð. word he sæwð;",
        "15": "Soðlice þa synt wið þone weg þar þæt word is gesawen. and þonne hi hit gehyrað; Sona cymð satanas and afyrð þæt word þe on heora heortan asawen ys.",
        "16": "And þa synt gelice þe synt ofer þa stan-scylian gesawen; Sona þænne hi þæt word gehyrað. and þæt mid blisse onfoð.",
        "17": "And hi nabbað wyrtruman on him. ac beoð unstaðolfæste. and syþþan upcymð deofles costnung and his ehtnys for þam worde;",
        "18": "Hi synd on þornum gesawen. þæt synd þa ðe þæt word gehyrað.",
        "19": "And of-yrmðe and swicdome worold-welene. and oðra gewilnunga þæt word of-þrysmað. and synt buton wæstme gewordene.",
        "20": "And þa ðe gesawene synt ofer þæt gode land. þa synd þe þæt word gehyrað and onfoð. and wæstm bringað. Sum þritig-fealdne. sum syxtig-fealdne. and sum hund-fealdne;",
        "21": "He sæde him cwyst þu cymð þæt leoht-fæt þæt hit beo under bydene asett. oððe under bedde. witegere þæt hit sy ofer candel-stæf asett;",
        "22": "Soðlice nis nan ðing behydd þe ne sy geswutelod; ne nis digle geworden. ac þæt hit openlice cume;",
        "23": "Gehyre gif hwa earan hæbbe to gehyranne.",
        "24": "And he cwæð to him warniað hwæt ge gehyran. and on þam gemete. þe ge metað eow bið gemeten and eow bið ge-ict.",
        "25": "þam bið geseald þe hæfð and þam ðe næfð. eac þæt he hæfð him bið æt-broden.",
        "26": "And he cw. godes rice ys swylce man wurpe god sæd on his land",
        "27": "And sawe and arise dæges and nihtes. and þæt sæd. growe and wexe þonne he nat;",
        "28": "Soðlice sylf-willes seo eorðe wæstm berað ærest gærs syððan ear. syþþan fullne hwæte on þam eare;",
        "29": "And þonne se wæstm hine forð-bringð. sona he sent his sícol forþam þæt rip æt is.",
        "30": "And eft he cwæð. for hwam geanlicie we heofena ríce. oððe hwylcum bigspelle wið-mete we hit;",
        "31": "Swa swa senepes sæd. þonne hit bið on eorðan gesawen. hit is ealra sæda læst þe on eorðan synt.",
        "32": "And þonne hit asawen bið hit astihþ. and bið ealra wyrta mæst and hæfð swa mycele bógas þæt heofenes fugelas eardian magon under his sceade.",
        "33": "And manegum swylcum bigspellum he spræc to him þæt hi mihton gehyran;",
        "34": "Ne spæc he na butan bigspelle. eall he his leorning-cnihtum asundron rehte.",
        "35": "And sæde him þonne æfen bið uton faran agen;",
        "36": "And þas menigu forlætan; hi onfengon hine swa he on scipe wæs. and oþre scipu wæron mid him.",
        "37": "And þa wæs mycel ýst windes geworden. and yþa he awearp on þæt scyp þæt hit gefylled wæs",
        "38": "And he wæs on scipe ofer bolster slapende. and hi awehton hine and cwædon. ne be-limpð to þe þæt we forwurþað.",
        "39": "And he arás and þam winde bebead. and cwæð to ðære sæ; Suwa and gestille. and se wind geswac þa. and wearð mycel smyltnes.",
        "40": "And he sæde him hwi synt ge forhte. gyt ge nabbað geleafan.",
        "41": "And hi micclum ege him ondredon. and cwædon ælc to oðrum hwæt wenst þu hwæt is ðes þæt him [wyndas and] sæ hyrsumiað;"},

    "5":  {
        "1":  "Ða comon hi ofer þære sæs muðan on þæt ríce. hierasenórum",
        "2":  "And him of scipe gangendum him sona agen árn án man of þam byrgenum on unclænum gaste;",
        "3":  "Se hæfde on byrgenum scræf and hine nán man mid racenteagum ne mihte gebindan.",
        "4":  "forþam he oft mid fot-coppsum and racenteagum gebunden. toslat þa raceteaga and þa fot-coppsas tobræc. and hine nán man gewyldan ne mihte.",
        "5":  "And symle dæges and nihtes he wæs on byrgenum and on muntum. hrymende and hine sylfne mid stanum ceorfende;",
        "6":  "Soðlice ða he þone hælend feorran geseah. he árn and hine gebæd.",
        "7":  "And mycelre stemne hrymende and þus cw. eala mæra hælend godes sunu hwæt is me and þe. Ic halsige þe ðurh god þæt ðu me ne þreage;",
        "8":  "Þa cwæð se hælend. eala unclæna gast. ga of ðysum men;",
        "9":  "Ða ahsode he hine hwæt is þin nama. þa cwæð he min nama is legio. forþam we manega synt.",
        "10": "And he hine swyðe bæd þæt he hine of þam rice ne dyde.",
        "11": "þar wæs embe þone munt mycel swyna heord læsgende.",
        "12": "And þa unclænan gastas hine bædon and cwædon; Send ús on þas swyn þæt we [on] hi gegán.",
        "13": "And þa lyfde se hælend sona. and ða eodon þa unclænan gastas on þa swýn. and on myclum hryre seo heord wearð on sæ besceofen. twa þusendo and wurdon adruncene. on ðære sæ;",
        "14": "Soþlice þa ðe hi heoldon flugon and cyddon on þære ceastre and on lande and hí ut eodon þæt hi ge-sawon hwæt þar gedón wære.",
        "15": "And hi comon to þam hælende and hi gesawon þone ðe mid deofle gedreht wæs. gescrydne sittan. [and] hales modes. and hi him ondredon.",
        "16": "And hi rehton him þa ðe hit gesawon hu hit gedón wæs. be þam ðe deofol-seocnesse hæfde and be þam swynum.",
        "17": "And hi bædon þæt he of hyra ge-mærum fore;",
        "18": "Þa he on scip eode hine ongan biddan se ðe ær mid deofle gedreht wæs. þæt he mid him wære;",
        "19": "Him þa se hælend ne getiðode. ac he sæde him ga to þinum huse to þinum híwum and cyð him hu mycel drihten gedyde and he ge-miltsode þe;",
        "20": "And he ða ferde and ongan bodigean on decapolim hu fela se hælend him dyde. and hig ealle þæs wundredon;",
        "21": "And þa se hælend eft on scype ferde ofer þone muþan him com to mycel menigu and wæs ymbe þa sæ.",
        "22": "And ða com sum of heah-gesamnungum iáirus hatte; and þa he hine geseah he astrehte hine to his fotum",
        "23": "And hine swyðe bæd. and he cwæð; Min dohtor is on ytemestum siðe. cum and sete þine hand ofer hi þæt heo hal sy and lybbe;",
        "24": "Ða ferde he mid him and him fyligde mycel menigeo and þrungon hine;",
        "25": "And þa þæt wíf ðe on blodryne twelf winter wæs.",
        "26": "And fram manegum læcum fela þinga þolode. and dælde eall þæt heo ahte. and hit naht ne fremode. ac wæs þe wyrse;",
        "27": "Þa heo be ðam hælende gehyrde heo com wið-æftan þa menigu and his reaf æt-hrán;",
        "28": "Soðlice heo cwæð gif ic fúrþon his reafes æt-hríne ic beo hál;",
        "29": "And þa sona wearð hyre blodes ryne adruwod. and heo on hire gefredde þæt heo of þam wíte gehæled wæs;",
        "30": "And þa se hælend on-cneow on him sylfum þæt him mægen of-eode. he cwæð bewend to þære menigu; Hwa æthran mines reafes.",
        "31": "þa cwædon his leorning-cnihtas þu ge-syxst þas menigu þe ðringende. and þu cwyst hwa æt-hran me;",
        "32": "And þa beseah he hine þæt he ge-sawe þæne ðe þæt dyde;",
        "33": "Ðat wíf þa ondrædende and forhtigende com and astrehte hi be-foran him and sæde him eall þæt riht;",
        "34": "Þa cwæð se hælend. dohtor þin geleafa þe hale gedyde. ga þe on sibbe and beo of ðisum hal;",
        "35": "Him þa gyt sprecendum hi comon fram þam heah-gesamnungum and cwædon; Ðín dohtor is dead. hwi drecst þu leng þone lareow;",
        "36": "Þa he ge-hyrde þæt word þa cwæð se hælend ne ondræd þu ðe gelyf for án;",
        "37": "And he ne lét him ænigne fyligean. buton petrum. and iacobum. and iohannem. Iacobes broðor",
        "38": "And hi comon on þæs heah-ealdres hus. and he ge-seah mycel gehlyd wepende and geomriende;",
        "39": "And þa he ineode he cw. hwi synd ge gedrefede and wepað. nis þis mæden na dead ac heo slæpð;",
        "40": "Ða tældon hi hine; He þa eallum út adrifenum. nam petrum and þæs mædenes modor. and þa ðe mid him wæron. and inn-eodon suwiende þar þæt mæden wæs.",
        "41": "And hire hand nam and cwæð. thalim-tha cumi. þæt is on ure geþeode gereht. mæden þe ic secge arís;",
        "42": "And heo sona aras and eode; Soðlice heo wæs twelf wintre. and ealle hi wundredon mycelre wundrunge.",
        "43": "And he him þearle bebead þæt hi hyt nanum men ne sædon and he het hire etan syllan;"},

    "6":  {
        "1":  "And þa he ðanon eode he ferde on his eðel. and him folgodon his leorning-cnihtas;",
        "2":  "And gewordenum reste-dæge he ongann on gesamnunge læran and manege gehyrdon and wundrodon on his láre and cwædon; Hwanon synd þyssum ealle þas ðincg and hwæt is se wisdom þe him ge-seald is. and swylce mihta þe ðurh his handa gewordene synd;",
        "3":  "Hu nys [þys] se smið marian sunu. iacobes broðor. and Iosepes. and iude [and] simonis. hu ne synt his swustra her mid ús. and þa wurdon hi gedrefede.",
        "4":  "þa cwæð se hælend; Soðlice nis nán witega buton wurðscipe. buton on his eðele and on his mægðe. and on his húse;",
        "5":  "And he ne mihte þar ænig mægen wyrcan. buton feawa untrume on-asettum his handum he ge-hælde.",
        "6":  "And he wundrode for heora ungeleafan; He ða lær[en]de þa castel be-ferde.",
        "7":  "And him twelfe togeclypode. and agan hi sendan twam and twam. and him anweald sealde unclænra gasta.",
        "8":  "And him bebead þæt hi naht on wege ne namon. buton gyrde áne. ne codd ne hlaf. ne feoh on heora gyrdlum;",
        "9":  "Ac ge-sceode mid calcum and þæt hi mid twam tunecum gescrydde næron;",
        "10": "And he cwæð to him; Swa hwylc hús swa ge ingað. wuniað þar oð þæt ge út-gan.",
        "11": "And swa hwylce swa eow ne ge-hyrað. þonne ge þanon út gað ásceacað þæt dust of eowrum fotum. him on ge-witnesse;",
        "12": "And út-gangende hi bodedon þæt hi dædbote dydon",
        "13": "And hi manega deofol-seocnessa út-adrifon. and manega untrume mid ele smyredon and gehældon;",
        "14": "And þa gehyrde herodes se cyng þæt; Soþlice his nama wæs swutol geworden and he cwæð; Witodlice Iohannes se fulluhtere of deaðe aras. and on him synd forþam mægenu geworht;",
        "15": "Sume cwædon he is elias. sume cwædon he is witega swylce án of þam witegum;",
        "16": "Ða herodes þæt ge-hyrde he cwæð; Se iohannes þe ic be-heafdode se aras of deaðe;",
        "17": "Soðlice herodes sende and hét iohannem gebindan on cwerterne. for þære herodiadiscan his broðar láfe philippus. for þam ðe he nam hi;",
        "18": "Þa sæde Iohannes heróde. nys þe alyfed to hæbbenne þines broðer wíf;",
        "19": "Ða syrwde herodias ymbe hine and wolde hine of-slean and heo ne mihte;",
        "20": "Soðlice herodes on-dred Iohannem and wiste þæt he wæs rihtwis. and halig. and he heold hine on cwerterne. and he ge-hyrde þæt he fela wundra worhte and he luflice him hyrde;",
        "21": "Þa se dæg com herodes gebrydtíde he ge-gearwode mycele feorme his ealdor-mannum. and þam fyrmestum on galilea.",
        "22": "And þa ða þære herodiadiscan dohtor inneode and tumbode. hit licode heróde. and eallum þam ðe him mid sæton; Se cing cwæð þa to ðam mædene. bide me swa hwæt swa þu wylle and ic þe sylle;",
        "23": "And he swór hire. soðes ic þe sylle swa hwæt swa þu me bitst. þeah þu wylle healf min rice;",
        "24": "Ða heo út eode heo cwæð to hyre meder; Hwæs bidde ic; Þa cwæþ heo. iohannes heafod þæs fulluhteres;",
        "25": "Sona þa heo mid ofste inn to þam cinincge eode. heo bæd and þus cwæð; Ic wylle þæt ðu me hrædlice on anum disce sylle iohannes heafod;",
        "26": "Þa wearð se cinincg geunrét for þam aðe. and for þam ðe him mid sæton; Nolde þeah hi ge-unretan.",
        "27": "Ac sende ænne cwellere and bebead þæt man his heafod on ánum disce brohte; And he hine þa on cwerterne beheafdode.",
        "28": "And his heafod on disce brohte and hit sealde þam mædene. and þæt mæden hit sealde hire meder;",
        "29": "Ða his cnihtas þæt ge-hyrdon hi cómon and his líc namon. and hine on byrgene ledon;",
        "30": "Soðlice þa ða apostolas togædere comon. hi cyddon þam hælende eall þæt hi dydon and hi lærdon.",
        "31": "And he sæde him; Cumað and uton gán onsundron on weste stowe. and us hwon restan; Soðlice manega wæron þe comon and agén-hwyrfdon and fyrst næfdon þæt hi æton.",
        "32": "And on scyp stigende. hi fóron onsundran on weste stowe.",
        "33": "And gesawon hi farende. and hi ge-cneowon manega; And gangende of þam burgum þyder úrnon. and him beforan comon;",
        "34": "And þa se hælend ðanon eode. he geseah mycele menegu. and he ge-miltsode him for þam þe hi wæron swa swa scép þe nanne hyrde nabbað; And he ongan hi fela læran.",
        "35": "And þa hit mycel ylding wæs. his leorning-cnihtas him to comon and cwædon. þeos stow is wéste and tíma is forð agán.",
        "36": "forlæt þas menegu. þæt hi faran on ge-hende tunas. and him mete bicgan. þæt hi eton;",
        "37": "Þa cwæð he sylle ge him etan; Ða cwædon hi uton gan. and mid twam hundred penegon hlafas bicgan. and we him etan syllað;",
        "38": "Ða cwæð he hu fela hlafa hæbbe ge. gað and lociað. and þa hi wiston hi cwædon. fif hlafas and twegen fixas.",
        "39": "And þa be-bead se hælend þæt ðæt folc sæte ofer þæt grene hig.",
        "40": "And hi þa sæton hundredon and fiftigon.",
        "41": "And fif hlafum. and twam fixum onfangenum he on heofon locode and hi bletsode. and þa hlafas bræc. and sealde his leorning-cnihtum. þæt hi toforan him asetton. and twegen fixas him eallon dælde",
        "42": "And hi æton þa ealle and gefyllede wurdon;",
        "43": "And hi namon þara hlafa. and fixa lafe. twelf wilian fulle;",
        "44": "Soðlice fif þusend manna þara etendra wæron;",
        "45": "Ða sona he nydde his leorning-cnihtas on scyp stígan. þæt hi him beforan foron ofer þæne muþan to bethsaida. oþ he þæt folc for-lete;",
        "46": "And þa he hi for-let he ferde on þone munt and hine ana þar gebæd;",
        "47": "And þa æfen wæs þæt scyp wæs on middre sæ. and he ana wæs on lande",
        "48": "And he ge-seah hi on rewette swincende. him wæs wiðer-weard wind; And on niht embe þa feorþan wæccan he com to him ofer þa sæ gangende. and wolde hi for-bugan;",
        "49": "Þa hi hine gesawon ofer þa sæ gangende hi wendon þæt hit unfæle gast wære. and hi clypedon;",
        "50": "Hi ealle hine gesawon. and wurdon gedrefede and sona he spræc to him and cwæð; Gelyfaþ ic hit eom. ne þurfon ge eow ondrædan.",
        "51": "And he on scyp to him eode. and se wind geswác and hi þæs þe má betwux him wundredon.",
        "52": "ne ongeton hi be þam hlafon; Soðlice heora heorte wæs ablend;",
        "53": "And þa hi ofer-segledon. hi comon to genesár. and þar wicedon.",
        "54": "And þa hi of scipe eodon. sona hi hine gecneowon;",
        "55": "And eall þæt ríce befarende hi on sæccingum bæron þa untruman. þar hi hine gehyrdon;",
        "56": "And swa hwar swa he on wíc oþþe on túnas eode. on stræton hi þa untruman ledon. and hine bædon þæt hi huru his refes fnæd æt-hrinon. and swa fela swa hine æt-hrinon hi wurdon hale."},

    "7":  {
        "1":  "Þa comon to him pharisei and sume boceras cumende fram hierusalem.",
        "2":  "And þa hi ge-sawon sume of his leorning-cnihton besmitenum handum þæt is únþwogenum handum etan. hi tældon hi and cwædon;",
        "3":  "Pharisei and ealle iudeas ne etað buton hi hyra handa gelomlice þwean. healdende hyra yldrena gesetnessa.",
        "4":  "And on stræte hi ne etað buton hi geþwegene beon. and manega oþre synd þe him gesette synt. þæt is calicea frymða. and ceaca. and árfata. and mæstlinga;",
        "5":  "And þa axodon hine pharisei and þa boceras. hwi ne gað þine leorning-cnihtas æfter ure yldrena gesetnysse. ac besmitenum handum hyra hlaf þicgað;",
        "6":  "Ða andswarode he him; Wel witegod isaias be eow licceterum swa hit awriten is; Þis folc me mid welerum wurðað. soðlice hyra heorte is feor fram me.",
        "7":  "on idel hi me wurðiað. and manna láre and bebodu lærað;",
        "8":  "Soþlice ge forlætað godes bebod. and healdað manna laga. þweala ceaca and calica. and manega oþre þylce ðing ge doð;",
        "9":  "Ða sæde he him. wel ge on idel dydon godes bebod þæt ge eower laga healdon;",
        "10": "Moyses cwæð. wurða þinne fæder and þine modor. and se ðe wyrigþ his fæder and his modor. swelte se deaþe;",
        "11": "Soðlice ge cweþað. gif hwa segð his fæder and meder corbán þæt is on ure geðeode gyfu. gif hwylc is of me þe fremað.",
        "12": "And ofer þæt ge ne lætað hine ænig þing dón his fæder oððe meder",
        "13": "toslitende godes bebod. for eower stúntan lage þe ge gesetton. and manega oþre þing ðysum gelice ge doð;",
        "14": "And eft þa menegu he him toclypode and cwæð; Ge-hyraþ me ealle and ongytað;",
        "15": "Nis nán þing of þam men on hine gangende þæt hine besmítan mæge; Ac þa ðing þe of ðam men forð-gað. þa hine besmitað.",
        "16": "gif hwa earan hæbbe gehlyste me;",
        "17": "And þa se hælend fram þære menegu eode his leorning-cnihtas hine án big-spell ahsodon;",
        "18": "Þa cwæð he. and synt ge þus ungleawe ne on-gyte ge. þæt eall þæt utan cymð on þone man gangende. ne mæg hine besmitan.",
        "19": "forþam hit ne gæð on his heortan. ac on his innoð. and on forð-gang gewíteð ealle mettas clænsigende;",
        "20": "Ða sæde he him þæt ða þing ðe of þam men gað. þa hine besmitað;",
        "21": "Innan of manna heortan. yfele geþancas cumað. unriht-hæmedu. and forligeru. manslihtas.",
        "22": "[stala.] gytsung. mán. facnu. sceamleast. yfel gesihð. dysinessa. ofer-modignessa. stuntscipe.",
        "23": "And ealle þas yfelu of þam innoðe cumað and þone man besmitað;",
        "24": "Ða ferde he þanon on þa endas tíri and sidónis. and he in-agán on þæt hús. he nolde þæt hit ænig wiste. and he ne mihte hit be-miðan;",
        "25": "Sona þa án wif be him ge-hyrde. þære dohtor hæfde unclæne gast. heo ineode. and to his fotum hi astrehte;",
        "26": "Soðlice þæt wíf wæs hæðen. sirofenisces cynnes. and bæd hine þæt he ðone deofol of hyre dehter adrife;",
        "27": "Þa sæde he hire; Læt ærust þa bearn beon gefylled. nis na gód þæt man nime þara bearna hlaf. and hundum worpe;",
        "28": "Ða andswarode heo and cþ; Drihten þæt is soð; Witodlice þa hwelpas etað under þære mýsan. of ðara cilda cruman;",
        "29": "Þa sæde he hyre for þære spræce; Ga nú. se deofol of ðinre dehter gewít;",
        "30": "And þa heo on hyre hus eode heo gemette þæt mæden on hyre bedde licgende. and þone deofol ut-gán;",
        "31": "And eft he eode of tíra gemærum and com þurh sidónem to þære galileiscan sæ betwux midde endas decapóleos.",
        "32": "And hi læddon him ænne deafne and dumbne. and hine bædon þæt he his hand him on sette;",
        "33": "Ða nam he hine onsundran of þære menigu. and his fingras on his earan dyde and spætende his tungan onhrán;",
        "34": "And on þone heofon behealdende geómrode and cwæð; Effeta. þæt is on ure geþeode sy þú ontyned;",
        "35": "And sona wurdon his earan geopenode. and his tungan bend wearð unslyped and he rihte spræc;",
        "36": "And he bead him þæt hi hit nanum men ne sædon; Soþlice swa he him swiþor bebead. swa hi swiðor bodedon.",
        "37": "And þæs þe ma wundredon and cwædon; Ealle þing he wel dyde. and he dyde þæt deafe gehyrdon. and dumbe spræcon;"},

    "8":  {
        "1":  "Eft on þam dagum him wæs mid micel menigu and næfdon hwæt hi æton; Þa cwæþ he to-somne geclypedum his leorning-cnihtum;",
        "2":  "Ic ge-miltsige þysse menegu. forþam hi þry dagas me ge-anbidiað and nabbað hwæt hi eton;",
        "3":  "Gif ic hí fæstende to hyra husum læte. be wege hi ge-teorigeað; Sume hi comon feorran.",
        "4":  "And þa andswarodan him his leorning-cnihtas; Hwanon mæg ænig man þas mid hlafum on þisum westene gefyllan;",
        "5":  "Þa axode he hi hu fela hlafa hæbbe ge. hi cwædon seofan;",
        "6":  "Ða het he sittan þa menegu ofer þa eorþan; And nam þa seofon hlafas and gode þancode. and hi bræc and sealde his leorning-cnihtum þæt hi toforan him asetton. and hi swa dydon;",
        "7":  "And hi næfdon buton feawa fixa and he þa bletsode. and het beforan him settan.",
        "8":  "And hi æton and wurdon gefyllede and hi námon þæt of þam brytsenum beláf. seofon wilian fulle;",
        "9":  "Soðlice þa ðe þar æton. wæron fif þusend and he hi þa for-lét;",
        "10": "[A]nd sona he on scyp mid his leorning-cnihtum astah. and com on þa dælas dalmanuða;",
        "11": "And þa ferdon ða pharisei. and ongunnon mid him smeagean and tacen of heofone sohton and his fandedon;",
        "12": "Þa cw. he geomriende on his gaste. hwi secð þeos cneoris tacen; Soþlice ic eow secge ne bið þisse cneorisse tacen geseald.",
        "13": "And hi þa forlætende eft on scyp astah. and ferde ofer þone muðan.",
        "14": "And hi ofergeton þæt hi hlafas ne namon. and hi næfdon on scype mid him buton ænne hláf.",
        "15": "And he him bead and cwæð; Lociað and warniað fram pharisea and herodes hæfe;",
        "16": "Þa þohton hi betwux him and cwædon; Næbbe we náne hlafas.",
        "17": "þa se hælend þæt wiste. he cwæð. Hwæt þence ge forþam ge hlafas nabbað. gýt ge ne oncnawað ne ne ongytað. gyt ge habbað eowre heortan geblende;",
        "18": "Eagan ge habbað and ne ge-seoð. and earan. and ne gehyrað. ne gé ne þencaþ",
        "19": "hwænne ic bræc fíf hlafas and twegen fixas and hu fela wyligena ge namon fulle; Hi cwædon þa twelfe;",
        "20": "And hwænne seofon hlafas feower þusendum. and hu fela wyligena. brytsyna ge namon. hi sædon seofon;",
        "21": "Ða sæde he him hwi ne ongyte ge gýt;",
        "22": "And hi comon þa to bedzaida and hi brohton him þa ænne blindne and hine bædon þæt he hine æthrine.",
        "23": "And þa æthran he þæs blindan hand and lædde hine butan þa wíc. and spætte on his eagan. and his hand onasette and hine axode hwæþer he aht gesawe;",
        "24": "Ða cwæð he þa ða he hine beseah. ic ge-seo men swylce treow gangende;",
        "25": "Eft he asette his handa ofer his eagan and he geseah þa. and wearð ge-edniwod. swa þæt he beorhtlice eall geseah;",
        "26": "Ða sende he hine to his huse. and cwæð gá to þinum huse. and ðeah þu on tún gá nænegum þu hit ne sege;",
        "27": "Ða eode he and his leorning-cnihtas on þæt castel cesareæ philippi. and he on wege his leorning-cnihtas ahsode. Hwæt secgað men þæt ic sy;",
        "28": "Þa andswarodon hi. sume Iohannem þone fulluhtere. sume heliam sume sumne of þam witegum;",
        "29": "Ða cwæð he hwæt secge ge þæt ic sy; Þa andswarude petrus him and cwæð; Ðu eart crist.",
        "30": "And ða bead he him. þæt hi nænegum be him ne sædon;",
        "31": "Ða ongan he hi læran þæt mannes sunu gebyreð fela þinga þolian and beon aworpen fram ealdormannum. and heahsacerdum and bócerum and beon ofslegen. and æfter þrim dagum arísan.",
        "32": "And spræc þa openlice. and þa nam petrus hine and ongan hine þreagean",
        "33": "þa be-wende he hine and cidde petre and cwæð; Gá on-bæc satanas forþam þu nast þa ðing þe synd godes. ac þa ðing þe synd manna;",
        "34": "Þa cwæð he togædere geclypedre menegu mid his leorning-cnihtum; Gif hwa wyle me fyligean wið-sace hine sylfne and nime his cwylminge and folgige mé;",
        "35": "Se ðe wyle his sawle hale gedon se hi for-spilð; Se ðe for-spilð his sawle for me. and for þam godspelle se hi ge-hælð;",
        "36": "Hwæt fremað men ðeah he eallne middan-eard gestryne. and do his sawle forwyrd.",
        "37": "oþþe hwylc gewryxl sylð se man for his sawle;",
        "38": "Soðlice se þe me for-syhð and mine word on þisre unriht-hæmedan and synfulran cneorisse. ðone mannes sunu for-syhþ; Ðonne he cymð on his fæder wuldre mid halgum englum;"},

    "9":  {
        "1":  "Þa sæde he him soðlice ic secge eow. þæt sume synt her wuniende. þe deað ne onbyrigeað. ær hi ge-seon godes rice on mægne cuman;",
        "2":  "Ða æfter syx dagum nam se hælend petrum and iacobum and iohannem and lædde hi sylfe onsundran on sumne heahne munt and wearð beforan him ofer-hiwud.",
        "3":  "And his reaf wurdon glitiniende swa hwite swa snaw. swa nan fullere ofer eorðan ne mæg swa hwite gedón;",
        "4":  "Þa æt-ywde him helias mid moyse and to him spræcon;",
        "5":  "Ða andswarode petrus him and cwæð. lareow gód is þæt we her beon and uton wyrcan her þreo eardung-stowa. þé ane. and moyse ane. and helie ane;",
        "6":  "Soðlice he nyste hwæt he cwæð. he wæs afæred mid ege;",
        "7":  "And seo lyft hi ofer-sceadewude. and stefn com of þære lyfte and cwæð. þes is min leofesta sunu gehyrað hine;",
        "8":  "And sona ða hi besawon hí nanne hi mid him ne gesawon buton þone hælend sylfne mid him;",
        "9":  "And þa hi of þam munte astigon he bead him þæt hi nanum ne sædon þa ðing þe hi ge-sawon buton þonne mannes sunu of deaðe aríse;",
        "10": "Hi þa ðæt word geheoldon betwux him and smeadon hwæt þæt wære þonne he of deaðe arise;",
        "11": "And hi hine ahsodon þa. hwæt secgað pharisei and þa boceras. þæt gebyrað ærest helias cume;",
        "12": "Ða sæde he him andswariende; Helias ealle þing ge-edniwað þonne he cymð. swa be mannes suna awriten is þæt hé fela ðolige and si ofer-hogod;",
        "13": "Ac ic secge eow þæt helias com and hi dydon him swa hwæt swa hi woldon swa be him awriten is;",
        "14": "And þa he com to his leorning-cnihtum he ge-seah mycele menegu abutan hi and boceras mid him sprecende.",
        "15": "And sona eall folc þæne hælend geseonde wearð afæryd and forht. and hine gretende him to urnon;",
        "16": "Þa ahsode he hi. hwæt smeage ge betwux eow;",
        "17": "Him andswarode án of þære menigu; Láreow. ic brohte minne sunu dumbne gast hæbbende",
        "18": "se swa hwær swa he hine gelæcð forgnit hine. and toðum gristbitað and for-scrincþ. and ic sæde þinum leorning-cnihtum þæt hi hine ut adrifon and hi ne mihton;",
        "19": "Ða andswarode he him. eala ungeleaffulle cneorys swa lange swa ic mid eow beo. swa lange ic eow þolige; Bringað hine to me.",
        "20": "þa brohton hi hine. and þa he hine geseah sona se gást hine gedrefde and on eorðan for-gnyden fæmende he tearflode;",
        "21": "And þa ahsode he his fæder. hu lang tid is syððan him þis gebyrede; Þa cwæð he of cildhade.",
        "22": "he hine gelómlice on fyr and on wæter sende þæt he hine for-spilde; Ac gif þu hwæt miht gefylst us ure gemiltsud;",
        "23": "Ða cwæð se hælend. gif þu gelyfan miht ealle þing synd gelyfedum mihtlice;",
        "24": "Ða sona hrymde þæs cildes fæder. and wepende cwæð; Drihten ic gelyfe. gefylst minre ungeleaffulnysse;",
        "25": "And þa se hælend geseah þa to-yrnendan menegu. he bebead þam unclænan gaste þus cweðende; Eala deafa and dumba gast. ic beode þe gá of him and ne ga þu leng on hine;",
        "26": "He ða hrymende and hine swyþe slitende eode of him. and he wæs swylce he dead wære; Swa þæt manega cwædon soðlice he is dead;",
        "27": "Þa nam se hælend his hand and hine up ahóf and he aras þa;",
        "28": "And þa he into þam huse eode his leorning-cnihtas hine digollice ahsodon. hwí ne mihton we hine ut adrifan;",
        "29": "Ða sæde he þis cynn ne mæg of nanum men út gán buton þurh gebedu and on fæstene;",
        "30": "Þa hi þanon ferdon hi forbugon galileam. he nolde þæt hit ænig man wiste;",
        "31": "Soðlice he lærde his leorning-cnihtas and sæde; Soþlice mannes sunu bið geseald on synfulra handa þæt hi hine ofslean. and ofslagen þam ðriddan dæge he arist;",
        "32": "Ða nyston hi þæt word. and hi adredon hine ahsiende;",
        "33": "Þa comon hi to capharnaum and þa hi æt ham wæron he ahsode hí hwæt smeade gé be wege.",
        "34": "And hi suwodon; Witodlice hi on wege smeadon hwylc hyra yldost wære;",
        "35": "Þa he sæt he clypode hi twelfe and sæde him. gif eower hwylc wyle beon fyrmest. beo se eaðmodust and eower ealra þen;",
        "36": "Þa nam he anne cnapan and ge-sette on hyra middele. þa he hine beclypte he sæde him;",
        "37": "Swa hwylc swa anne of þus geradum cnapum on minum naman onfehð. se onfehþ me; And se þe me onfehð he ne onfehþ me. ac þone þe me sende;",
        "38": "Ða andswarode iohannes and cwæð; Lareow sumne we ge-sawon on þinum naman deofol-seocnessa ut adrifende. se ne fyligð us. and we him forbudon;",
        "39": "Þa cwæð he ne for-beode ge him nis nán þe on minum naman mægen wyrce and mæge raðe be me yfele specan;",
        "40": "Se þe nis agen eow se is for eow;",
        "41": "Soðlice se ðe sylð drinc eow calic fulne wæteres on minum naman forþam ge cristes synt. ic eow soþ secge. ne forlyst he his mede;",
        "42": "And swa hwa swa ge-drefð ænne of þyssum lytlingum on me gelyfendum. betere him wære þæt án cweorn-stan wære to his swuran gecnyt and wære on sæ beworpen;",
        "43": "And gif þin hand þe swicað ceorf hi of; Betere þe is þæt þú wanhal to life ga. þonne þu twa handa hæbbe and fare on helle. and on unacwencedlic fýr",
        "44": "þar hyra wyrm ne swylt and fyr ne bið acwenced;",
        "45": "And gif ðin fot swicað þe ceorf hine of. betere þe is þæt þu healt gá. on écé lif þonne þu hæbbe twegen fet and si aworpen on helle un-acwencedlices fyres.",
        "46": "þar hyra wyrm ne swylt ne fyr ne bið adwæsced;",
        "47": "Gif þin eage þe swicað weorp hit út. betere þe is mid anum eagan gán on godes ríce þonne twa eagan hæbbende sy aworpen on helle fyr.",
        "48": "þar hyra wyrm ne swylt. ne fyr ne bið acwenced;",
        "49": "Soðlice ælc man bið mid fyre ge-sylt and ælc offrung bið mid sealte gesylt;",
        "50": "Gód is sealt gif þæt sealt unsealt biþ on þam þe ge hit syltað; Habbað sealt on eow. and habbað sibbe betwux eow;"},

    "10": {
        "1":  "And þanon he com on iudeisce endas of iordane; Þa comon eft menigu to him and swa swa he ge-wunode he hi lærde eft sona;",
        "2":  "Ða ge-nealæhton him pharisei and hine axodon. hwæþer alyfð ænegum men his wif forlætan. his þus fandigende;",
        "3":  "Þa andswarode he him. hwæt bead moyses eow.",
        "4":  "hi sædon; Moyses lyfde þæt man write hiw-gedales boc. and hi for-léte;",
        "5":  "Ða cwæð se hælend. for eower heortan heardnesse he eow wrat þis bebod;",
        "6":  "Fram fruman gesceafte god hi ge-worhte wæpned-man and wimman",
        "7":  "And cwæð. for þam se mann forlæt his fæder and modor and hine his wife geþeot.",
        "8":  "And beoð twegen on anum flæsce. witodlice ne synt na twegen ac án flæsc;",
        "9":  "Þæt god ge-samnode ne syndrige þæt nán man;",
        "10": "And eft innan huse his leorning-cnihtas hine be þam ylcan ahsodon;",
        "11": "Ða cwæð he swa hwylc mann swa his wif forlæt and oþer nimð unriht-hæmed he wyrcð. þurh hi;",
        "12": "And gif þæt wif hire were forlæt and oþerne nimð. heo unriht-hæmð;",
        "13": "And hi brohton him hyra lytlingas þæt he hi æthrine. þa ciddon his leorning-cnihtas þam ðe hi brohton;",
        "14": "Þa se hælend hi ge-seah unwurðlice he hit for-bead and sæde him; Lætaþ þa lytlingas to me cuman and ne for-beode ge him; Soðlice swylcera is heofona ríce;",
        "15": "Soþlice ic secge eow swa hwylc swa godes rice ne onfehð swa lytling ne mæg he [on] þæt;",
        "16": "Ða beclypte he hí. and his handa ofer hi settende bletsode hi;",
        "17": "And þa he on wege eode sum him to arn and gebigedum cneowe toforan him cwæð. and bæd hine; La góda lareow hwæt do ic. þæt ic éce lif age;",
        "18": "Þa cwæð se hælend. hwi segst þu me godne. nis nan mann god buton god ana;",
        "19": "Canst þu ða bebodu. ne unriht-hæm þu. ne slyh þu. ne stel þu. ne sege þu lease gewitnesse. facen ne do ðu. wurða þinne fæder and þine modor;",
        "20": "Ða andswarode hé goda lareow. eall ðis ic geheold of minre geoguðe;",
        "21": "Se hælend hine þa behealdende lufode and sæde him; An þing þe is wana gesyle eall þæt ðu age and syle hit þearfum. þonne hæfst þu gold-hord on heofonum and cum and folga me;",
        "22": "And for þam worde he wæs ge-unret and ferde gnornigende for þam he hæfde mycele æhta;",
        "23": "Þa cwæð se hælend to his leorning-cnihton hine beseonde. swyþe earfoðlice on godes rice gað þa þe feoh habbað;",
        "24": "Ða forhtodon his leorning-cnihtas be his wordum; Eft se hælend him andswariende cwæð. eala cild swyðe earfoðlice þa ðe on heora feo getruwigeað gað on godes rice;",
        "25": "Eaþere ys olfende to farenne þurh nædle þyrel þonne se rica and se welega on godes rice gá;",
        "26": "Hi þæs ðe ma betwux him wundredon and cwædon and hwa mæg beon hal",
        "27": "þa beheold se hælend hi and cwæð; Mid mannum hit is uneaþelic ac na mid gode; Ealle þing mid gode synt eaðelice;",
        "28": "Þa ongan petrus cweþan; Witodlice we ealle þing for-leton and folgodon þe;",
        "29": "Ða andswarode him se hælend. nis nan þe his hus for-læt. oððe gebroþru. oþþe geswustra. oððe fæder. oþþe modor. oððe bearn. oþþe æceras for me and for þam god-spelle",
        "30": "þe hund-feald ne onfó. nu on þisse tide. hus and broðru and swustru. fæder and modor. and bearn. and æceras. mid ehtnessum and on toweardre worulde éce lif;",
        "31": "Manega fyrmeste beoð ytemeste and ytemeste fyrmyste;",
        "32": "Soþlice hi ferdon on wege to hierusalem and se hælend him beforan eode and hi adredon him hine and him fyligdon. and eft he nam hi twelfe and ongan him secgan þa ðing þe him towearde wæron",
        "33": "þæt we nu astigað to hierusalem and mannes sunu bið ge-seald sacerda ealdrum and bocerum and ealdrum. and hi hine deaðe genyþeriað. and hi hine þeodum syllað.",
        "34": "And hi hine bysmriað and hi him on spætað and hine swingað and of-sleað hine. and he arist on þam þriddan dæge;",
        "35": "Him þa ge-nealæhton to. iacobus. and Iohannes Zebedeis suna and cwædon; Lareow. we wyllað þæt þu us do swa hwæt swa we biddað;",
        "36": "Þa cwæð he hwæt wylle gyt þæt ic inc dó.",
        "37": "þa cwædon hi; Syle unc þæt wyt sitton on þinon wuldre. án on þine swyðran healfe and oþer on þine wynstran;",
        "38": "Ða cwæð se hælend. gyt nyton hwæt gyt biddað; Mage gyt drincan þone calic. þe ic drince and beon gefullod on þam fulluhte þe ic beo gefullod;",
        "39": "Þa cwædon hi wyt magon; Ða cwæð se hælend gyt drincað þone calic þe ic drince. gyt beoð gefullode þam fulluhte ðe ic beo gefullod;",
        "40": "Soðlice nis hit na min inc to syllene þæt gyt sitton on mine swyðran healfe oððe on þa wynstran. ac þam þe hit ge-gearwod ys;",
        "41": "Þa ge-bulgon þa týne hi be Iacobe and Iohanne;",
        "42": "Ða clypode se hælend hi and cw; Wite ge þæt þa ðe on þeodum ealdor-scype habbað þæt hyra ealdras anweald ofer hi habbað;",
        "43": "Soðlice on eow hit nis swa. ac swa hwylc swa wyle mid eow yldest beon se byð eower þen.",
        "44": "And se ðe wyle on eow fyrmest beon. se byþ ealra þeow;",
        "45": "Soðlice ne com mannes sunu. þæt him man þenode. ac þæt he þenode. and his sawle sealde for manegra alysednysse;",
        "46": "Þa comon hi to gericho and he ferde fram gericho and his leorning-cnihtas and mycel menegu. timeus sunu bartimeus sæt blind wið þone weg wædla.",
        "47": "þa he ge-hyrde þæt. hit wæs se nazareniscea hælend. he on-gan þa clypian and cweðan; Hælend. dauides sunu gemiltsa me;",
        "48": "Þa budon him manega þæt he suwode. he clypode þa þæs ðe ma miltsa me dauides sunu;",
        "49": "Ða æt-stod se hælend and het hine clypian; Þa sædon hi þam blindan. beo geheortra and arís. se hælend þe clypað;",
        "50": "He þa awearp his reaf and forð ræsde. and to him com;",
        "51": "Ða cwæð se hælend. hwæt wylt þu þæt ic þe dó; þa cwæð he. lareow þæt ic geseo.",
        "52": "þa cwæð se hælend to him. gá þin geleafa þe halne gedyde. and he sona geseah and him fyligde on wege;"},

    "11": {
        "1":  "Ða he ge-nealæhte hierusalem and bethanía to oliuetes dune. he sende his twegen leorning-cnihtas.",
        "2":  "And cwæð to him. faraþ to þam castele þe [ongean] ínc ys and gyt þar sona gemetað assan folan getigedne. ofer þæne nán man gyt ne sæt. untigeað hine and to me gelædað;",
        "3":  "And gyf hwa to ínc hwæt cwyð. secgað þæt drihten hæfð his neode. and he hine sona hider læt.",
        "4":  "And þa hi ut-ferdon hi gemetton þone folan ute on twycenan beforan dura. getigedne. þa untigdon hi hine",
        "5":  "And sume þe þar stodon þus sædon him; Hwæt do gyt þone folan untigende.",
        "6":  "þa cwædon hi; Swa se hælend unc bead and hi leton hi þa;",
        "7":  "Ða læddon hi þone folan to þam hælende and hi hyra reaf on á-ledon and he on sæt;",
        "8":  "Manega hyra reaf on þone weg strehton. sume þa boceras of þam treowum heowon and streowodon on þone weg.",
        "9":  "And þa ðe beforan eodon and þa ðe æfter folgodon cwædon þus osanná sy gebletsod se þe com on drihtnes naman;",
        "10": "Si gebletsod þæt ríce þe com ures fæder dauides osanná on heahnessum;",
        "11": "And he eode þa on hierosolima templ and ealle þing he be-sceawode; Þa æfen tima wæs he ferde to bethaníam mid his twelf leorning-cnihtum;",
        "12": "And oþrum dæge þa hi ferdon fram bethanía hine hingrode;",
        "13": "Ða he feorran geseah an fic-treow þe leaf hæfde he cóm and sohte hwæþer he þar on aht funde þa he him to cóm ne funde he þar buton leaf áne; Soðlice hit wæs þæs fic-treowes tima;",
        "14": "Þa cw he. heonon forð on ecnesse ne ete ænig mann wæstm of þe. and his leorning-cnihtas þæt gehyrdon;",
        "15": "Þa comon hi eft to hierusalem and þa he on þæt templ eode he ongann drifan of þam temple syllende and bicgende. and mynetera þrocu. and heah-setlu þe þa culfran cypton he to bræc.",
        "16": "And hé ne geþafode þæt ænig man ænig fæt ðurh þæt templ bære",
        "17": "And he þa lærende ðus cw to him; Nis hit awriten þæt min hus fram eallum þeodum bið ge-nemned gebed-hus. soðlice ge dydon þæt to sceaðena scræfe;",
        "18": "Ða þæra sacerda ealdras and þa boceras ðis ge-hyrdon. hi þohton hu hi hine for-spildon. þeh hi him adredon hine. forðam eall seo menigu wundrode be his láre;",
        "19": "And þa hit æfen wæs he eode of þære ceastre;",
        "20": "On merigen þa hi ferdon. hi gesawon þæt fic-treow for-scruncen of þam wyrt-ruman;",
        "21": "Þa cwæð petrus. lareow. loca hu for-scranc þæt fic-treow þe ðu wyrigdest;",
        "22": "Ða cwæð se hælend him and-swarigende. habbað godes truwan.",
        "23": "ic secge eow to soðe. swa hwylc swa cwyþ to ðisum munte. si þu afyrred and on sæ aworpen. and on his heortan ne twynað ac gelyfð swa hwæt swa he cwyð gewurðe þis. þæt gewyrð;",
        "24": "Forþam ic eow secge swa hwæt swa ge gyrnende biddað gelyfað þæt ge hit onfoð. and hit eow be-cymð;",
        "25": "And þonne ge standað eow to gebiddenne. forgifaþ gif gé hwæt agén ænigne habbað. þæt eow eower synna forgyfe eower heofonlica fæder se ðe on heofonum ys;",
        "26": "Gif ge ne forgyfað ne eow. eower synna ne forgyfð eower heofonlica fæder;",
        "27": "Ða com he eft to hierusalem. and þa he on þam temple eode him to genealæhton þa heah-sacerdos and boceras and ealdras",
        "28": "And þus cwædon; On hwylcum anwealde dest þu ðas þing. and hwa sealde þe ðisne anweald þæt þu ðis dó;",
        "29": "Þa cwæð se hælend and ic ahsige eow ánre spræce andswariað me. and ic secge eow þonne on hwylcum anwealde ic þis dó;",
        "30": "Hweðer wæs iohannes fulluht þe of heofone. þe of mannum andswariað me;",
        "31": "Ða þohton hi and cwædon betweox him. gif we secgað of heofone. he segð ús hwi ne ge-lyfde ge him.",
        "32": "gif we secgað of mannum. we on-drædaþ þis folc. ealle hi hæfdon iohannem þæt he wære soðlice witega;",
        "33": "Þa andswaredon hi þam hælende and cwædon we nyton; Ða cwæð se hælend. ne ic eow ne secge on hwylcum anwealde ic þas þing dó;"},

    "12":
          {
              "1":  "Ða ongan he him big-spell reccan. sum mann him plantode wingeard and be-tynde hine. and dealf anne seað and getimbrode ænne stypel and gesette hine mid eorð-tilium. and ferde on elþeodignysse;",
              "2":  "Þa sende he to þam tiligum his þeow on tide þæt he þæs wíngeardes wæstm onfenge;",
              "3":  "Ða swungon hi þæne. and forleton hine idel-hende;",
              "4":  "And eft he him sende oðerne þeow. and hi þone on heafde gewundodon and mid teonum geswencton;",
              "5":  "And eft he him sumne sende and hi þæne of-slogon. and manega oþre. sume hi beoton. sume hi of-slogon;",
              "6":  "Þa hæfde he þa gyt ænne leofostne sunu. þa sende he æt nehstan him þæne and cwæð; Witodlice minne sunu hig for-wandiað;",
              "7":  "Ða cwædon þa tilian him be-tweonan; Her is se yrfe-numa. uton ofslean hine. þonne bið ure seo yrfeweardnes;",
              "8":  "Hi þa ofslogon hine. and wurpon wið-utan þone wín-geard;",
              "9":  "Hwæt deð þæs wíngeardes hlaford. he cymð and fordeð þa tiligean. and sylð oþron þone wíngeard;",
              "10": "Ne rædde ge þis gewrit. Se stán þe þa wyrhtan awurpon þes ys geworden on þære hyrnan heafod.",
              "11": "þis ys fram drihtne geworden and hit is wundorlic on uron eagum;",
              "12": "Þa smeadon hi þæt hi gefengon hine and hi ondredon þa menigu. hi on-cneowon þa þæt he þis bigspell to him sæde hi ferdon þa and hine forleton;",
              "13": "Þa sendon hi to him sume of phariseum and herodianum þæt hi befengon hine on his worde;",
              "14": "Ða comon hi and þus mid facne cwædon; Lareow. we witon þæt þu eart soðfæst and þu ne recst be ænegum menn. ne besceawast þu manna ansyne. ac þu godes weg lærst on soð-fæstnysse; Alyfð gaful to syllanne þam casere",
              "15": "hwæðer þe we ne syllað; Þa cwæð he and heora lot-wrenc-ceaste wiste. hwi fandige mín bringað mé þone pening þæt ic hine geseo.",
              "16": "þa brohton hi him þa sæde he him; Hwæs is þeos anlicnys and þis ge-writ. hi cwædon. ðæs caseres;",
              "17": "Ða cwæð se hælend to him. agyfað þam casere þa ðing þe þæs caseres synd. and gode þa ðe godes synd. þa wundrodon hi be þam;",
              "18": "Þa comon him to sad[u]cei þa secgað þæt ærist ne sý and hine ahsodon and þus cwædon;",
              "19": "Lareow. moyses us wrat. gif hwæs broðor dead bið and læfð his wíf and næfð nan bearn. þæt his broðor nime his wíf and his broðor sæd wecce;",
              "20": "Eornostlice seofon gebroþru wæron. and se æresta nam wíf and wearð dead ná læfedum sæde;",
              "21": "And þa nam se oðer hi. and wearð dead. ne sé sæd ne læfde; Gelice se þridda",
              "22": "And ealle seofon hi hæfdon and sæd ne læfdon; Ealra æftemest þa forð-ferde þæt wif;",
              "23": "On þam æriste. hwylces þara seofona bið þæt wíf. hi ealle hi hæfdon;",
              "24": "Þa andswarode him se hælend hu ne dweligað ge. forþam þe ge nyton þa halgan gewritu ne godes mægen;",
              "25": "Soðlice þonne hi of deaðe arisaþ. ne wifiaþ hi. ne ne gyftigeað. ac hi synt swylce godes englas on heofonum;",
              "26": "Be þam deadum þæt hi aríson. ne rædde ge on moyses bec hu god to him cwæþ. ofer þone gorst-beam; Ic eom abrahames god. and isááces god. and iacobes god.",
              "27": "nis god deadra ac he hys lybbendra; Soðlice swyþe ge dweligeað:",
              "28": "Ða genealæhte him án of þam bocerum þe he gehyrde hi smeagende and geseah þæt he him wel andswarode. and ahsode hine hwæt wære ealra beboda mæst;",
              "29": "Þa andswarode he him. þæt is þæt mæste bebod. ealra israhel gehyr urne drihten god. he is [an god]",
              "30": "And lufa þinne drihten god. of ealre þinre heortan. and of ealre þinre sawle. eallum þinum móde. and of eallum þinum mægene. þæt is þæt fyrmeste bebod;",
              "31": "Soðlice is oðer þissum gelic; lufa þinne nehstan swa þe sylfne. nys oðer máre bebod;",
              "32": "Ða cwæþ se bocere. lareow. well þú on soþe cwæde. þæt an god is. and nis oðer butan him",
              "33": "And ðæt he si gelufod of ealre heortan. and of eallum andgyte. and of ealre sawle. and of ealre strengðe. and lufigean his nehstan swa hine sylfne. þæt is mare eallum on-sægdnyssum and offrungum;",
              "34": "Ða se hælend geseah þæt he him wislice andwyrde he sæde him ne art þu feorr fram godes ríce. and hine ne dorste nan mann ahsian;",
              "35": "Ða cwæþ se hælend on þam temple lærende; Hu secgað þa boceras þæt crist sy dauides sunu;",
              "36": "Dauid sylf cwæþ to þam halgan gaste. drihten cwæþ to minum drihtne. síte on mine swyðran healfe. oð ic þíne fýnd asette to fot-sceamole þinra fóta;",
              "37": "Dauid sylf nemde hine drihten. and hwanon is he his sunu; And mycel menegu hine luflice gehyrde.",
              "38": "þa sæde he him on his lare; Warniað fram bocerum. þa wyllað on ge-gyrlum gán and beon on straætum grete.",
              "39": "And on fyrmostum lareow-setlum. sittan on ge-samnungum and þa fyrmestan setl on ge-beor-scipum",
              "40": "þa ðe wudewena hus for-swelgað mid heora langsuman gebede. þa onfoð lengestne dóm;",
              "41": "Ða sæt se hælend ongén þone toll-sceamol and geseah hu þæt folc hyra feoh. torfude on þone toll-sceamul. and manega welige torfudon fela;",
              "42": "Þa com án earm wuduwe. and wearp twegen feorð-lingas;",
              "43": "Ða clypode he his leorning cnihtas and sæde him; Soðlice ic eow secge. þæt þeos earme wuduwe eallinga mæst sealde þara þe on toll-sceamul sealdon;",
              "44": "Ealle sendon of þam þe hi genoh hæfdon; Soðlice þeos of hyre yrmþe eall þæt heo hæfde sealde ealle hyre and-lyfene;"},

    "13":
          {
              "1":  "Ða he of þam temple eode þa cwæð án of his leorning-cnihtum to him. lareow loca hwylce stanas her synt and hwylce getimbrunga þisses temples;",
              "2":  "Þa cwæð se hælend. ne ge-seoge ealle þas mycelan getimbrunga. ne bið her læfed stan ofer stan þe ne beo toworpen;",
              "3":  "Þa hi sæton on oliuetes dúne ongen þæt tempel synderlice hine petrus and iacobus. and iohannes. and andreas. ahsodon;",
              "4":  "Sege us hwænne þas þing ge-wurdon and hwylc tacen bið þænne ealle þas ðing onginnað beon ge-endud;",
              "5":  "Þa ongan se hælend him andswarigende to cweðan; Warniað þæt eow nan mann ne be-swice;",
              "6":  "Soþlice manega cumað on minum naman. and cweþað. ic eom crist and beswicað manega",
              "7":  "And þonne ge gehyrað gefeohtu. and gefeohta hlisan. ne ondræde ge eow. hit gebyrað þæt hit gebelimpe. ac þonne gyt nis ende;",
              "8":  "Soðlice þeod arist ágén þeode. and rice ongén rice and beoð eorþan styrunga geond stowa and hungor. þis synd sara angin;",
              "9":  "Warniað eow sylfe. hi syllað eow on geþeahte and swingað on gesamnungum. and ge standað beforan demum and cyningum. for minum naman him on ge-witnesse",
              "10": "And on ealle þeoda; Ærest ge-byrað beon þæt godspel gebodud.",
              "11": "And þonne hi syllende eow læþað ne fore-smeage ge hwæt ge specan. ac specað þæt eow on þære tide ge-seald bið; Ne synd ge na specende ac se halga gast;",
              "12": "Soðlice se broðor þone broþor to deaðe sylð. and se fæder his sunu. and þa bearn arisað agén hyra magas. and mid deaðe hi ge-wæceað.",
              "13": "And ge beoð eallum on hatunge for minum naman; Soðlice se bið hal se þe oð ende þurh-wunað;",
              "14": "Ðonne ge ge-seoð þære toworpednysse asceonunge standan þar heo ne sceal. þonne ongyte se þe ræt. fleon þonne on muntas þa ðe synt on iudea",
              "15": "And se ðe is ofer þécene ne stige he on his hús ne he in ne ga þæt he aht on his huse nime.",
              "16": "And se ðe bið on æcere ne cyrre he ongean þæt he his reaf nime;",
              "17": "Wá cenne[n]dum on þam dagum.",
              "18": "biddað þæt ðis on wintra ne ge-wurðe;",
              "19": "Soþlice on þam dagum beoð swylce gedrefednessa. swylce ne ge-wurdon. of frymmðe þære gesceafte þe god gesceop. oð nu. ne na ne gewurþað.",
              "20": "And gif drihten þas dagas ne gescyrte. nan flæsc ne wurde hal. ac for þam gecorenum þe he ge-ceas he ge-scyrte þa dagas;",
              "21": "And gif eow hwylc segð witodlice her is crist. witodlice þær he is. ne gelyfe ge;",
              "22": "Soðlice lease cristas. and lease witegan arisað. and wyrcað fore-beacnu. to beswicanne eac gif hit beon mæg þa ge-corenan;",
              "23": "Warniað eow. nu ealle þing. þe ic eow fore-sæde.",
              "24": "Ac on þam dagum æfter þære geswencednysse. bið sunne aþeostrod. and se mona his beorhtnesse ne sylð",
              "25": "And heofones steorran beoð feallende. and beoð astyrode þa megenu þe on heofonum synt;",
              "26": "Ðonne geseoð hi mannes sunu cumendne on ge-nipum mid mycelum mægene and wuldre;",
              "27": "þonne sent he his englas and hi gaderiað his gecorenan of feower windum of eorþan heanesse oþ heofones heahnesse;",
              "28": "Leorniað an bigspell be þam fic-treowe. þonne his twi bið mearu. and leaf beoð acennede. ge witon þæt sumor is gehende.",
              "29": "And wite ge þonne ge þas ðing geseoð þæt he is dura gehende;",
              "30": "Soðlice ic eow secge þæt þeos cneores ne gewit ærþam ealle þas ðing gewurðon.",
              "31": "heofon and eorðe gewitað. witodlice mine word ne ge-witað;",
              "32": "Be þam dæge and þære tide nan mann nat. ne englas on heofone ne mannes sunu buton fæder ána;",
              "33": "Warniað and waciað and gebiddaþ eow. ge nyton hwænne seo tid ys;",
              "34": "Swa se man ælþeodilice ferde forlet his hus and sealde his þeowum þæne anwald gehwylces weorces. and beode þam dure-wearde þæt he wacige;",
              "35": "Eornostlice wacigeað ge nyton hwænne þæs huses hlaford cymð; þe on æfen þe on midre nihte. þe on hancrede. þe on mergen.",
              "36": "þe læs he eow slapende geméte þonne he færinga cymð;",
              "37": "Soðlice þæt ic eow secge eallum ic hit secge waciað."},

    "14": {
        "1":  "Soþlice þa æfter twam dagum wæron eastron and þa sohton þa heah-sacerdas and þa boceras hu hi hine mid facne namon and of-slogon;",
        "2":  "Ða cwædon hi næs na on freols-dæge þe læs þæs folces gehlyd wurde;",
        "3":  "And þa se hælend wæs on bethanía on simones húse anes hreoflan and þar sæt; Þa com an wíf and hæfde hyre sealf-box deorwyrþes nardes. and tobrocenum sealf-boxe. ofer his heafod agét;",
        "4":  "Sume hit unwurðlice forbæron. and betwux him sylfum cwædon; For hwi wæs þisse sealfe forspillednes geworden.",
        "5":  "þeos sealf mihte beon geseald to þrim hund penegum. and beon þearfum geseald. and yrsydon agén hi;",
        "6":  "Ða cwæð se hælend. lætað hi hwi synt ge hire grame. gód weorc heo on me worhte;",
        "7":  "Soðlice symble ge habbað þearfan mid eow. and þonne ge wyllað ge magon him teala dón. me ge symble nabbað;",
        "8":  "Þeos sealde þæt heo hæfde. heo com to smyrianne minne lic-haman on byrgene;",
        "9":  "Soðlice ic eow secge swa hwar swa þis godspell gebodad bið. on eallum middan-earde bið gebodod þæt heo þis on his gemynde dyde;",
        "10": "Ða iudas scarioth þæt is wiþersaca. án of þam twelfum. ferde to þam heah-sacerdum þæt he hine belæwde;",
        "11": "Þa hi þis gehyrdon hi fahnodon and beheton him feoh to syllanne. and he smeade hu he hine digellice sealde;",
        "12": "And þam forman dæge azimorum þa hi eastron offrodon. his leorning-cnihtas him sædon. hwyder wylt þu þæt we faron and gegearwian þe. þæt ðu eastron ete;",
        "13": "Ða sende he twegen of his leorning-cnihtum and sæde him; Gað on þa ceastre and inc agén yrnð. sum man berende sume wæter-flaxan; Folgiað him;",
        "14": "And swa hwyder swa he inn-gæð secgað þæs huses hlaforde; Vre lareow secgð. hwar is min gyst-hús. and min gereord. hwar ete is eastron. mid minum leorning-cnihtum;",
        "15": "And he inc geswutelað mycele healle gedæfte. and ge-ge-earwiað us þara;",
        "16": "Þa ferdon his leorning cnihtas and comon on þa ceastre. and fundon hit eall swa he sæde. and ge-gearwodon þa eastron;",
        "17": "Soðlice þa æfen cóm. him twelfum mid him",
        "18": "sittendum and etendum sæde se hælend; Soðlice ic eow secge þæt eower án þe mid me yt gesylð me;",
        "19": "Ða ongunnon hi beon dreorige and betwux him cweðan. cwyst þu eom ic hit;",
        "20": "Þa sæde he him. án of eow twelfum me sylð. se ðe his hand on disce mid me dypð;",
        "21": "And witodlice mannes sunu gæð swa be him awriten is. wá þam menn þurh þone þe mannes sunu geseald bið. betere him wære þæt se mann acenned nære;",
        "22": "Him þa etendum afeng se hælend hlaf and hine bletsiende bræc. and sealde him and þus cwæð. nimað. ðis ys min lichama.",
        "23": "And onfeng calice. and gode þancas dyde and sealde him. and ealle him ofdruncon;",
        "24": "Þa sæde he him. ðis ys min blod þære niwan cyðnesse þæt bið for manegum agoten;",
        "25": "Soðlice ic eow secge þæt ic heonon forð ne drince of þyses wingeardes cynne. oð þone dæg þonne ic hine niwne drince on godes rice;",
        "26": "And gecwedenum lofe hi ferdon on ele-bergena munt;",
        "27": "Ða cwæð se hælend. ealle ge beoð geuntreowsode on þisse nihte. forþam þe hit awriten is. ic slea þæne hyrde and beon þa scép to-dræfede;",
        "28": "Ac æfter þam þe ic arise. ic cume beforan eow on galileam;",
        "29": "Þa sæde petrus him. þeah ðe ealle swicion ne swicige ic þe ná",
        "30": "Þa cwæð se hælend; Soþlice ic þe secge. þæt ðu on þisse nihte ær hana tuwa crawe. þriwa wið-sæcst mín.",
        "31": "And he þæs ðe mare spræc. and þeah me ge-byrige mid þe to sweltene. ne æt-sace ic þin. and swa hi cwædon ealle;",
        "32": "Þa comon hi to anum tune þæs nama wæs gezemani. and he cwæð to his leorning-cnihton; Sittað her oð þæt ic me gebidde;",
        "33": "And he nam þa mid him petrum and iacobum and iohannem. þa ongan he forhtian and sargian",
        "34": "And sæde him; Unrót is min sawl oð deað. gebidað her and waciað;",
        "35": "Ða he lyt-hwon forð-stóp he astrehte hine ofer þa eorðan. and he bæd. gif hit beon mihte þæt he on þære tide fram him gewite;",
        "36": "And þa cwæð he. abba. þæt is fæder on ure geþeode. ealle þing þe synt mihtiglice. afyrr þysne calic fram me ac na þæt ic wylle ac þæt þu;",
        "37": "Þa com he and funde hi slæpende. and cwæð to petre; Simon. slæpst þu. ne mihtest ðu áne tide wacian.",
        "38": "waciað and gebiddað þæt ge on costnunge ne gán. witodlice se gast is gearu. ac þæt flæsc is untrum;",
        "39": "And eft he ge-bæd þa ylcan spræce.",
        "40": "And þa he hine eft agén bewende. he funde hí slæpende. hyra eagan wæron gehefegode and hi nyston hwæt hi him andswaredon;",
        "41": "Ða com he þriddan siðe and sæde him. slapað nú and restað genoh hit ys. tíma ys cumen nu is mannes sunu geseald on synfulra handa;",
        "42": "Arísaþ. uton gan. nu is gehende se ðe me sylð;",
        "43": "Him þa ða gyt sprecendum com íudas scarioth. þæt ys wiþersaca. án of þam twelfum. and mid him mycel menegeo mid swurdum and mid sahlum. fram heah-sacerdum. bocerum and ealdrum;",
        "44": "Soðlice his læwa him tacen sealde and þus cwæð; Swa hwylcne swa ic cysse he hit is. nimað and lædað hine wærlice.",
        "45": "And sona swa he com he ge-nealæhte him to and cw. lareow. and cyste hine.",
        "46": "And hi hyra handa on hine wurpon. and namon hine;",
        "47": "Soðlice án of þam þe ðar embe-uton stodon his swurde abræd and sloh þæs sacerdes þeow. and his eare of acearf;",
        "48": "Þa cwæð se hælend him andswariende; Swa swa to anum sceaðan ge ferdon mid swurdon and treowum me gefón.",
        "49": "þonne ic dæghwamlice mid eow wæs on temple lærende and ge me ne namon. ac þæt þa gewritu syn gefyllede;",
        "50": "Ða forleton his leorning-cnihtas ealle hine and flugon;",
        "51": "Sum iungling him fyligde mid anre scytan bewæfed nacod and hi namon hine;",
        "52": "Ða aworpenre þære scytan nacod he him fram fleah;",
        "53": "And hi læddon þæne hælend to þam heah-sacerde. and comon ealle sacerdas. and boceras and ealdras togædere;",
        "54": "Petrus him fyligde feorran oþ ðæs heah-sacerdes cafertún and he sæt mid þam ðenum and wyrmde hine æt þam fyre;",
        "55": "Þa heah-sacerdas sohton and eall geþeaht. tale agén þone hælend. þæt hi hine to deaðe sealdon and hi ne fundon;",
        "56": "Manega sædon lease gecyðnysse agén hine. and þa cyðnessa næron þæslice;",
        "57": "Ða arison sume and sædon lease cyðnesse agén hine and þus sædon;",
        "58": "Soðes we ge-hyrdon hine secgan. ic to-wurpe þis hand-worhte tempel and æfter þrim dagum ic oðer unhand-worht ge-timbrie;",
        "59": "And hyra cyþnys næs þæs-lic;",
        "60": "Þa aras sum heah-sacerd on hyra midlene and ahsode þæne hælend. ne andswarast þu nan ðing. agén þæt þas þe onwurpað;",
        "61": "he suwode and naht ne andswarode; Eft hine axode se heah-sacerd. eart þu crist þæs gebletsodan godes sunu;",
        "62": "Ða sæde se hælend. ic eom. and ge geseoð mannes sunu on swyðran healfe sittan his mægenes. and cumende mid heofones genipum;",
        "63": "Þa cw se heah-sacerd. his reaf slitende. hwi ge-wilnige wé gyt cyðera.",
        "64": "ge gehyrdon his bysmer. hwæt þincð eow; Ða hyrwdon hi ealle hine and cwædon þæt he wære deaðes scyldig;",
        "65": "And sume agunnon him on spætan and ofer-wreon his ansyne. and mid fystum hine beoton. and him to cwædon; Aræd. and þa ðenas hine mid handum beoton;",
        "66": "And þa petrus wæs on cafertune þa com to him án þinen þæs heah-sacerdes.",
        "67": "And þa heo geseah petrum wyrmende þa cwæð heo; Þu wære mid ðam nazareniscan hælende;",
        "68": "Ða æt soc he and cwæð. ic nát. ne ne can hwæt þu segst; And he eode þa of þam cafertune and se hana creow;",
        "69": "Eft þa hine gecneow oðer þinen. heo ongan cweðan. to þam þe ðar abutan stodon; Soðlice þes ys of þam;",
        "70": "And he eft ætsóc; and eft þa ymbe lytel þa ðe æt-stodon. cwædon to petre. Soþlice þu eart of ðam. galileisc þu eart;",
        "71": "Þa ongan he æt-sacan and swerian. soðes ne can ic þæne man þe ge secgað.",
        "72": "And þa eft sona creow se hana; Ða gemunde petrus þæs hælendes worde þe he him sæde. ær se hana crawe tua. þriwa ðu me æt-sæcst. þa ongan he wepan;"},

    "15": {
        "1":  "Þa sona on mergen worhton þa heah-sacerdas hyra gemot mid ealdrum. and bocerum and eallum werodum. and læddon þæne hælend gebundenne. and sealdon hine pilato;",
        "2":  "Ða axode pilatus hine. eart þu iudea cynincg; Þa andswarode he him. þu hit segst;",
        "3":  "Ða wregdon hine þa heah-sacerdas on manegum þingum;",
        "4":  "Eft pilatus hine axode. ne andswarast þu nán þing. loca hu mycelum hi þe wregeað;",
        "5":  "Ða ne andswarode se hælend him na mare. swa þæt pilatus wundrode;",
        "6":  "On symmel-dæge wæs his gewuna þæt he him for-geafe ænne gebundenne. swa hwylcne swa hi bædon;",
        "7":  "Þa bædon hi barraban. se wæs gebunden mid þam ræplingum. se þurh swic-cræft. man-slyht geworhte.",
        "8":  "And þa he ferde. þa ongan seo menegeo hine biddan swa heo symle dyde;",
        "9":  "Ða cwæð pilatus; Wylle ge þæt ic eow forgyfe iudea cyning.",
        "10": "he wiste þæt ðurh andan hine sealdon þa heah-sacerdas;",
        "11": "Þa astyredon þa bisceopas þa menegu þæt he him barraban forgefe;",
        "12": "Eft pilatus him andswarode. hwæt do ic be iudea cininge;",
        "13": "Hi eft hrymdon and cwædon. hóh hine;",
        "14": "Ða sæde pilatus. hwæt yfeles dyde he; Hi þæs þe ma clypedon ahóh hine;",
        "15": "Pilatus wolde þa ðam folce gecweman. and for-gef him barraban and sealde him þone hælend beswungenne þæt he á-hangen wære;",
        "16": "Þa læddon þa cempan hine on þæs domernes cafertún; and hi to-somne eall werod clypedon;",
        "17": "And scryddon hine mid purpuran. and him on setton þyrnenne helm awundenne.",
        "18": "And ongunnon hine þus gretan. hal wes þu iudea cyning;",
        "19": "And beoton hine on þæt heafod mid hreode. and spætton him on. and heora cneow bígdon. and hine ge-eaðmeddon;",
        "20": "And syððan hi hine bysmrydon. unscryddon hine þam purpuran. and scryddon hine mid his reafum and læddon hine þæt hi hine ahengon.",
        "21": "And genyddon sumne weg-ferendne simonem cireneum cumende of þam tune alexandres fæder and rufi. þæt he his rode bære.",
        "22": "And hi læddon hine on ða stowe golgoða þæt is on ure geþeode gereht heafod-pannena stow.",
        "23": "And sealdon him gebiterod wín and he hit ne on-feng;",
        "24": "And þa hi hine ahengon hi dældon his reaf. and hlotu wurpon. hwæt gehwa náme;",
        "25": "Þa wæs undern-tíd. and hi ahengon hine.",
        "26": "And ofer-gewrit his gyltes wæs awriten iudea cyning.",
        "27": "And hi ahengon mid him twegen sceaðan anne on his swyðran healfe. and oþerne on his wynstran.",
        "28": "þa wæs þæt ge-writ gefylled. þæt cwyð; and he wæs mid unriht-wisum geteald;",
        "29": "And þa ðe forð-stopon hine gremedon and hyra heafod cwehton. and ðus cwædon; Wala se to-wyrpð þæt tempel. and on þrim dagon eft getimbrað.",
        "30": "gehæl ðe sylfne of þære rode stigende;",
        "31": "Eall-swa þa heah-sacerdas bysmriende betwux þam bocerum cwædon. oðre he hale gedyde. hine sylfne he ne mæg halne gedon;",
        "32": "Críst israhela cyning astige nú of rode þæt we ge-seon and ge-lyfon; And þa ðe him mid hangodon wæron him mid gebundene;",
        "33": "And þære syxtan tide wurdo[n] þystru gewordene geond ealle eorðan. oð nón-tide",
        "34": "And to nón-tide se hælend clypode mycelre stemne. heloi. heloi. lema sabbattani. þæt is on ure geðeode mín god mín god. hwi for-lete þu me;",
        "35": "And sume þe ðar abuton stodon and þis gehyrdon hi cwædon. nu þes clypað heliam.",
        "36": "þa árn hyra án and fylde áne spingan mid ecede. and on hreod sette and him drincan sealde. and cwæð; Lætað þæt we ge-seon hwæðer helias cume hine nyþer to settanne;",
        "37": "Se hælend þa asende his stefne and forð-ferde.",
        "38": "And þæs temples wah-rift wæs tosliten on twa of ufewerdum oð neoþewerd;",
        "39": "Þa se hundred-man þe ðar stod agén geseah þæt se hælend swa clypiende forð-ferde. he cw. soðlice þes man wæs godes sunu;",
        "40": "And þa wíf wæron feorran be-healdende. and betwux þam wæs seo magdalenisce maria. and maria iacobes modor. and salomeæ;",
        "41": "And þa he wæs on galilea hi fylidon him. and him þenedon and manega oðre þe him mid ferdon on hierusalem;",
        "42": "And þa æfen wæs geworden þæt wæs parasceue. þæt is ær sæter-dæge",
        "43": "þa com iosep se æðela gerefa of abarimathia. se sylfa godes rices geanbidode. and he dyrstiglice into pilate eode. and bæd þæs hælendes lic-haman;",
        "44": "Ða wundrode pilatus gif he þa gyt forð-ferde; Þa clypode he þæne hundred-man and hine ahsode hwæðer he dead wære;",
        "45": "Ða he wiste þæt. þa agef he þone lic-haman iosepe;",
        "46": "Þa bohte iosep áne scytan. and hine þar-on befeold. and on byrgene lede. seo wæs of stane aheawen. and wylte anne stan to ðære byrgenne dura;",
        "47": "Ða com maria magdalene and iosepes maria. and be-heoldon hwar he geled wære;"},

    "16":
          {
              "1":  "And ða sæternes dæg wæs agán. seo magdalenisce maria and iacobes maria and salomeæ bohton wyrt-gemang þæt hi comon and hine smyredon;",
              "2":  "And swyðe ær anum reste-dæge comon to þære byrgene up-asprungenre sunnan.",
              "3":  "And cwædon him betwynan; Hwa awylt us ðysne stan of þære byrgene dura;",
              "4":  "Þa hi hi besawon. hi gesawon þæne stan aweg awyltne. soðlice he wæs swyðe mycel;",
              "5":  "And þa hi eodon on þa byrgene hi gesawon anne geongne on þa swyðran healfe sittende hwitum gegyrlan ofer-wrohne; and hi þa forhtodon;",
              "6":  "Ða cwæð he to him ne forhtige ge na. ge secað þæne nazareniscan hælend ahangenne; He arás nis he hér; her is seo stow þær hi hine ledon.",
              "7":  "Ac farað and secgað his leorning-cnihtum. and petre þæt he gæð toforan eow on galileam. þar ge hine geseoð swa he eow sæde;",
              "8":  "And hi ut eodon. and flugon fram þære byrgene. and wæron áfærede for þære gesyhðe þe hi gesawon. and hig nanon men naht ne sædon. soðlice hi him adredon;",
              "9":  "Þa he arás on ærne morgen on reste-dæge. æryst he æt-ywde þære magdaleniscan marian. of ðære he út adraf seofon deofol-seocnyssa.",
              "10": "And heo þa ut eode and hit þam cydde þe mid him wæron heofendum and wependum",
              "11": "þa hi gehyrdon þæt he leofode and hi hine gesawon. þa ne ge-lyfdon hi him.",
              "12": "Æfter þam him twam he wæs æt-ywed on oðrum hiwe. him on þone tún farendum",
              "13": "And hi þa foron and þæt oðrum cyddon. and hi him ne gelyfdon;",
              "14": "Ða æt nehstan he ætywde him twelfum þar hi æt-gædere sæton. and tælde hyra ungeleaffulnesse. and hyra heortan heardnesse. forðam þe hi ne ge-lyfdon þam ðe hine gesawon of deaþe arisan.",
              "15": "And he sæde him. Farað into ealne middan-eard and bodiað god-spell. ealre gesceafte.",
              "16": "Se þe gelyfð and gefullod bið se biþ hal; Soþlice se ðe ne gelyfð. se bið genyðerod;",
              "17": "Þas tacnu fyliað þam ðe ge-lyfað. on minon naman hi deofol-seocnessa ut-drifað; hi sprecaþ niwum tungum.",
              "18": "næddran hi afyrrað and him ne derað þeah hi hwæt dead-bærlices drincan; Ofer seoce hi hyra handa settað and hi beoð hale;",
              "19": "And witudlice drihten hælend syððan he to him spræc. he wæs on heofonum afangen. and he sitt on godes swiðran healfe;",
              "20": "Soþlice hi ða farende æghwar bodedon. drihtne mid-wyrcendum and trymmendre spræce æfter-fyligendum tacnum."
              }}
