john = {"1": {

    "1": "On FRYMÐ WÆ word & þt word wæs mid gode & god wæs þt word.",
    "2": "þt wæs on fruman mid gode",
    "3": "ealle þing wæron geworhte ðurh hyne & nan þing næs geworht butan him.",
    "4": "þt wæs líf þe on him geworht wæs. & þt líf wæs manna leoht",
    "5": "& þt leoht lyht on ðystrum. & þystro þt ne genamon;",
    "6": "Mann wæs fram gode asend. þæs nama wæs iohannes.",
    "7": "ðes cóm to gewitnesse. þt he gewitnesse cyðde be ðam leohte. þt ealle menn þurh hyne gelyfdon;",
    "8": "Næs he leoht. ac þt he gewitnesse forð-bære be þam leohte;",
    "9": "Soð leoht wæs. þt onlyht ælcne cumendne man on þisne middan-eard.",
    "10": "he wæs on middan-earde. & middan-eard wæs geworht þurh hine. & middan-eard hine ne ge-cneow;",
    "11": "To his agenum he cóm. & hig hyne ne under-fengon;",
    "12": "Soðlice swa hwylce swa hyne under-fengon. he sealde him ánweald þt hi wæron godes bearn þam ðe gelyfað on his naman.",
    "13": "ða ne synt acennede of blodum. ne of flæsces willan. ne of weres willan. ac hig synt of gode acennede;",
    "14": "And þt word wæs flæsc geworden & eardode on ús & we gesawon hys wuldor swylce áncennedes wuldor. of fæder þt wæs ful mid gyfe. & soðfæstnysse;",
    "15": "Iohannes cyþ gewitnesse be him & clypaþ þus cweðende. þes wæs þe ic sæde. Se ðe to cumenne is æfter me. wæs geworden beforan me. forðam he wæs ær þonne íc;",
    "16": "And of his gefyllednesse we ealle onfengon gyfe for gyfe.",
    "17": "for-þam þe æ wæs geseald þurh moysen. & gyfu; & soþfæstnes is geworden þurh hælend crist.",
    "18": "Ne geseah næfre nan mann god butan se acenneda sunu hit cyðde se is on his fæder bearme",
    "19": "& þt is Iohannes gewitnes; Ða þa iudeas sendon hyra sacerdas & hyra diaconas fram gerusalem to him þt hi axsodon hine & þus cwædon; Hwæt eart þu.",
    "20": "& he cyðde & ne wið-soc & þus cwæð; Ne eom ic na crist;",
    "21": "And hig axsodon hine & þus cwædon. eart ðu elías & he cwæð ne eom ic hit; Ða cwædon hí. eart ðu witega. & he andwyrde & cwæð níc.",
    "22": "Hig cwædon to him hwæt eart þu þt we andwyrde bringon þam ðe us to þe sendon. hwæt segst þu be þe sylfum;",
    "23": "Hé cwæð. ic eom clypiendes stéfn on westene; Gerihtað drihtnes weg swa se witega isaias cwæð;",
    "24": "And þa þe þær ásende wæron. þa wæron of sundor-halgon.",
    "25": "& hig axsodon hine & cwædon to him. hwi fullast þu. gif þu ne art [cryst]. ne helígas ne wítega;",
    "26": "Iohannes him &swarode. ic fullige on wætere. tomiddes eow stód þe ge ne cunnon.",
    "27": "he is þe æfter me toweard is; Se wæs geworden be-foran me. ne eom ic wyrðe þt ic unbinde his sceo-þwang;",
    "28": "Ðas ðing wæron gewordene on bethanía begeondan iordanen þær iohannes fullode;",
    "29": "Oþre dæg iohannes geseah þone hælend to him cumende & cwæð; Her is godes lámb. her is se þe deð aweg middan-eardes synnæ.",
    "30": "þes is be ðam ic sæde æfter mé cymð wer þe me befóran geworden wæs. forðam þe he wæs ær ðonne ic.",
    "31": "& ic hyne nyste. ac ic cóm & fullode on wætere to ðæm þt he wære geswutelud on israhela folce;",
    "32": "And Iohannes cyþde gewitnesse cweðende þt ic geseah nyðer-cumendne gást of heofenum swa swa culfran. & wunode ofer hine.",
    "33": "& ic hine ne cúðe ac se þe me sende to fullianne on wætere. he cwæð to me ofer ðæne þe ðu gesyhst nyðer-stígendne gast. & ofer hine wuniendne þt is se ðe fyllað on halgum gaste.",
    "34": "& ic geseah & gewitnesse cyðde þt þes is godes sunu;",
    "35": "Eft oðre dæg stod iohannes & twégen of his leorning-cnihtum.",
    "36": "& he cwæð þa he geseah þæne hælend gangende hér is godes lámb;",
    "37": "Ða gehyrdon hyne twegen leorning-cnihtas sprecende & fylidon þam hælende.",
    "38": "þa beseah se hælend & geseah hig him fyliende. & cwæð to him hwæt séce gyt; Hi cwædon to him rabbi þt is gecweden & gereht lareow. hwar eardast ðu.",
    "39": "he cwæþ to him cumað & geseoþ; Hig comon & gesáwon hwar he wunode & mid him wunodon on ðam dæge. hit wæs þa seo teoðe tid;",
    "40": "Andreas simones broþur petrus wæs oþer of þam twam; Þa gehyrdon æt Iohanne & him fyligdon;",
    "41": "Ðes gemette ærost simonem his broðor & cwæð to him. we gemetton messiam þt is gereht críst.",
    "42": "& hig læddon hine to þam hælende; Ða beheold se hælend hyne & cwæþ. þu eart símon iónan sunu þu bist genemned cephás. þt is gereht petrus;",
    "43": "On mergen he wolde faran on galilea. & he gemette philippus. & se hælend cwæð to him fylig me.",
    "44": "Soþlice pHilippvs wæs fram bethzaida andreas ceastre & petres;",
    "45": "philippus gemette nathanael & cwæþ to him. we gemetton ðone hælend iosepes sunu of nazareth. þone wrat moyses & þa witegan on ðære .æ.",
    "46": "& nathanahel cwæð to him. mæg ænig þing godes beon of nazareth; Philippus cwæð to him. cum & geseoh;",
    "47": "Ða geseah se hælend nathanahel to him cumendne & cwæð be him. her is israhelisc wer on ðam nis nan facn;",
    "48": "Ða cwæð nathanahel to him hwanon cuðest ðu me. þa &swarode se hælend & cwæð to him; Ic geseah þe þa þu wære under þam fic-treówe ærðam þe philippus þe clypode;",
    "49": "Him &swarode þa nathanahel & ðus cwæð. rabbí. þu eart godes sunu. & þu eart israhela cing.",
    "50": "þa cwæð se hælend to him. þu gesyhst mare þonne þis sy. forðam þe ðu gelyfdest; Ða ic cwæð þt ic gesawe þe under þam fíc-treowe.",
    "51": "& he sæde him; Soð ic secge eow ge ge-seoð opene heofonas & godes englas úp-stigende; & nyðer-stigende ofer mannes Sunu:"},

"2": {

    "1": "On þam þriddan dæge wæron gyfta gewordene on chanaá galileæ. & þæs hælendes modor wæs þær;",
    "2": "Soþlice se hælend & his leorning-cnihtas wæron gelaðode to þam gyfton.",
    "3": "& þa þt wín geteorude. þa cwæð þæs hælendes modor to him hi nabbað wín;",
    "4": "Þa cwæþ se hælend to hyre la wíf. hwæt is me & þe. gyt min tima ne com;",
    "5": "Ða cwæð þæs hælendes modor to þam þenum. doð swa hwæt swa he eow secge;",
    "6": "Þær wæron soðlice aset six stænene wæter-fatu æfter iudea geclænsunge. æl[c] wæs on twegra sestra gemete oððe on þreora.",
    "7": "Ða bead se hælend þt hig þa fátu mid wætere gefyldon. & hig gefyldon þa oþ þone brerd.",
    "8": "Ða cwæþ se hælend hládaþ nú & berað þære drihte ealdre & hi namon.",
    "9": "Ða se drihte ealdor þæs wínes onbyrigde þe of þam wætere geworden wæs. he nyste hwanon hyt com. þa þenas soðlice wiston þe þt wæter hlódon; Se drihte ealdor clypode þone brydguman",
    "10": "& cwæð to him. ælc man sylþ ærest gód wín. & þonne hig druncene beoð þt þe wyrse byð; Ðu geheolde þt gode wín oð þis.",
    "11": "Ðis wæs þt forme tacn þe se hælend worhte on chanaá galileæ & geswutelode his wuldor. & his leorning-cnihtas gelýfdon on hine;",
    "12": "[Æ]fter þyson he & hys modor & his gebroðru & his leorning-cnihtas foron to capharnaúm & wunedon þar feawa daga;",
    "13": "And hit wæs neah iudea eastron & se hælend for to ierusalem",
    "14": "& gemette on þam temple þa ðe sealdon oxsan & scéap. & culfran. & sittende myneteras.",
    "15": "& he worhte swípan of strengon. & hig ealle of ðam temple adráf ge sceap. ge oxsan. & he agéat þára mýnetera féoh & towéarp hyra mysan;",
    "16": "& sæde þam þe ða culfran cypton. doð þas þing heonon. ne wyrce ge. mines feder hus to mángung-huse;",
    "17": "Þa gemundon his leorning-cnihtas þt ðe awriten is. þínes huses anda me et;",
    "18": "Ða &swaredon him þa iudeas. & cwædon hwylc tacn æt-ywst þu ús forðam þe þu ðas ðing dest;",
    "19": "Se hælend him &swarude & cwæð. to-wurpaþ þis tempel. & ic hít arære binnan þrim dágon;",
    "20": "Ða iudeas cwædon to him. þis tempel wæs getimbrod on six & feowertigon wíntron & á-rærst þú hit on þrym dagon;",
    "21": "Soðlice he hyt cwæð be hys lichaman temple;",
    "22": "Ða he of deaðe arás þa gemundon his leorning-cnihtas þt he hit be him sylfum cwð. And hi gelyfdon halegum gewrite & þære spræce þe se hælend spræc.",
    "23": "ða he wæs on ierusalem on eastron on freols-dæge manega gelyfdon on his naman. þa hi gesawon ða tacna þe he worhte;",
    "24": "Se hælend. ne geswutelode hine sylfne him for-ðam he cuðe hi ealle",
    "25": "& for-þam him næs nan þearf þt ænig man sæde gewitnesse be men. he wiste witodlice hwæt wæs on men;"},

"3": {

    "1": "Soð-lice sum phariseisc man wæs genemned nichodémus. se wæs iudea ealdor;",
    "2": "Ðés com to him on niht. & cwæð to him. rabbi þt is lareow. we witon þt þu cóme fram gode. ne mæg nan man þas tacn wyrcan þe ðu wyrcst buton god beo mid him;",
    "3": "Se hælend him &swarude. & cwæð. Soð ic þe secge buton hwa beo edniwan gecenned. ne mæg he geseon godes rice;",
    "4": "Ða cwæð nichodemus to him. hu mæg man beon eft acenned þonne he bið eald. cwyst ðu. mæg he eft cuman on his modor innoð. & beon eft acenned;",
    "5": "Se hælend him &swarude. & cwæð. Soþ ic þe secge buton hwa beo ge-edcenned of wætere & of haligum gaste. ne mæg he in-faran on godes rice;",
    "6": "Ðæt þe acenned is of flæsce. þt is flæsc. & þt þe of gaste is acenned. þt is gast;",
    "7": "Ne wundra þu forðam. þe ic sæde þe. eow gebyrað þt ge beon acennede edniwan;",
    "8": "Gast oreðað þar he wile. & þu gehyrst his stefne & þu nast hwanon he cymþ. ne hwyder he gæþ. swa is ælc þe acenned is of gaste;",
    "9": "Ða &swarode nichodemus & cwæð. hu magon þas þing þus geweorðan;",
    "10": "Se hælend &swarode & cwæð to him; Ðu eart lareow israhela folce. & þu nast þas ðing.",
    "11": "Soþ ic þe secge þt we sprecað þt we witon. & we cyðað þt we gesawon. & ge ne under-foð ure cyðnesse;",
    "12": "Gif ic eow eorþlice þing sæde & ge ne gelyfað. hu-meta gelyfe ge. gif ic eow heofon-licæ þing secge.",
    "13": "& nan man ne astihð to heofenum buton se ðe nyðer com of heofonum; Mannes sunu. se ðe com of heofonum.",
    "14": "& swa swa moyses þa næddran up-ahóf on þam westene. swa gebyrað þt mannes sunu beo úp-a-háfen.",
    "15": "þt nan þara ne for-wurðe þe on hyne gelyfð ac hæb[b]e þt ece lif;",
    "16": "God lufode middan-eard swa þt he sealde his ancennendan (sic) sunu. þt nán ne forwurðe þe on hine gelyfð. ac hæbbe þt ece líf;",
    "17": "Ne sende god his sunu on middan-earde þt he demde middan-earde Ac þt middan-eard sy ge-hæled þurh hine.",
    "18": "ne biþ þam gedemed ðe on hine gelyfð; Se ðe ne gelyf[ð] him biþ gedemed. for-þam þe he ne gelyfde on ðone naman þæs acennendan (sic) godes suna.",
    "19": "þt is se dóm þt leoht com on middan-eard. & menn lufedon þystro swyþor ðonne þt leoht; Hyra weorc wæron yfele.",
    "20": "ælc ðara þe yfele. deð hatað þt leoht. & he ne cymþ to leohte þt his weorc ne syn gerihtlæhte;",
    "21": "Witodlice se ðe wyrcð soðfæstnesse. cymþ to ðam leohte þt his weorc syn ge-swutelude. for-ðam þe hig synt on gode gedone;",
    "22": "Æfter þyson com se hælend & his leorning-cnihtas to iudea lande. & wunode ðær mid him & fullode.",
    "23": "& iohannes fullode on enón wið salím. forðam þe þær wæron manega wætro. & hi to-gædere comun. & wæron gefullode;",
    "24": "Ða gyt næs iohannes gedon on cwéartern.",
    "25": "þa smeadon iohannes leorni[n]g-cnihtas & þa iudeas be þære clænsunge.",
    "26": "& comon to iohanne & cwædon to him. rabbí. Se ðe mid þe wæs begeondan iordáne be ðam þu cyðdest gewitnesse nu he fullaþ. & ealle hig cumaþ to him.",
    "27": "Iohannes &wurde & cwæð ne mæg mann nan þing u[n]der-fón buton hit beo [hym] of heofonum geseald;",
    "28": "Ge sylfe me synd to gewitnesse. þt ic sæde ne eom ic crist Ac ic eom asend beforan hine;",
    "29": "Se ðe bryde hæfð se is brydguma. Se þe is þæs brydguman freond & stent & gehyrþ hyne. mid gefean he geblissað for þæs brydguman stefne. þés min gefea is gefylled.",
    "30": "hit geburað þt he weaxe. & þt ic wanige.",
    "31": "Se ðe ufenan cóm se is ofer ealle. Se þe of eorðan is. se sprycþ be eorðan. Se þe of heofone cóm se is ofer ealle.",
    "32": "& he cyð þt he geseah & gehyrde. & nan man ne under-fehþ his cyðnesse.",
    "33": "Soðlice se þe [hys] cyðnesse under-fehþ. he getacnað þt god is soðfæstnys;",
    "34": "Se ðe god sende sprycð godes word. ne sylþ god þone gast be gemete;",
    "35": "Fæder lufað þone sunu. & sealde ealle þing on his hand.",
    "36": "Se þe gelyfð on súnu. se hæfð éce lif; Se þe þam suna is ungeleafsum ne gesyhþ he líf. Ac godes yrre wunað ofer hine;"},

"4": {

    "1": "Ða se hælend wyste. þt þa pharisei gehyrdon þt he hæfde ma leorning-cnihta þonne iohannes.",
    "2": "þeah se hælend ne fullode. Ac his leorning-cnihtas;",
    "3": "Ða forlet he iudea land. & for eft on galiléa.",
    "4": "him gebyrode þt he sceolde faran þurh samaria land.",
    "5": "witodlice he cóm on samárian cestre þe is genemned sichár. neah þam tune þe iacob sealde iósepe his suna",
    "6": "þær wæs iacobes wyl; Se hælend sæt æt ðam wylle. þa he wæs werig gegán. & hit wæs mid-dæg.",
    "7": "þa com þær an wif of samária wolde wæter feccan; Ða cwæð se hælend to hyre. syle me drincan;",
    "8": "His leorning-cnihtas ferdon þa to þære ceastre woldon him mete bicgan.",
    "9": "þa cwæð þt samaritanisce wíf to him; Hu-meta bitst þu æt me drincan þonne ðu eart iudeisc. & ic eom samaritanisc wíf. ne brucað iudeas. & samaritanisce metes ætgædere;",
    "10": "Ða &swarode se hælend & cwæð to hyre; Gif þu wistest godes gyfe. & hwæt sé is þe cwið to þe syle me drincan. witodlice þu bæde hine þt he sealde þe lífes wæter;",
    "11": "Ða cwæð þt wíf to him. leof ne ðu næfst nan þing mid to hladene. & þes pyt is déop. hwanon hæfst þu lifes wæter",
    "12": "cwyst ðu. þt þu si mærra þonne úre fæder iacób; Se ðe us þisne pytt sealde & he & his bearn & his nytenu of ðam druncon.",
    "13": "Ða &swarode se hælend & cwæþ to hyre. ælcne ðara þyrst eft þe of ðyson wætere dringð;",
    "14": "Witodlice ælc þara þe drincð of þam wætere þe ic him sylle [...] bið on him will forð-ræsendes wætres on ece líf;",
    "15": "Ða cwæð þt wif to him. hláford. syle me þt wæter þt me ne þyrste. ne ic ne ðurfe her feccan;",
    "16": "Ða cwæþ se hælend to hyre. ga clypa þinne ceorl. & cum hider;",
    "17": "Ða &wurde þt wíf. & cwæð. næbbe ic nanne ceorl; Ða cwæð se hælend to hyre. wel þu cwæde þt þu næfst ceorl.",
    "18": "witodlice þu hæfst fif ceorlas. & se ðe ðu nu hæfst nis ðin ceorl æt þam þu sædest soð;",
    "19": "Ða cwæð þt wif to him. leof. þæs me ðingþ þu eart witega.",
    "20": "ure fæderas hig gebædon on þissere dune. & ge secgað þt on ierusalem sy seo stow. þt man on gebidde;",
    "21": "Ða cwæð se hælend to hyre. la wíf gelyf me. þt seo tid cymð þonne ge ne gebiddaþ fæder ne on þisse dune ne on gerusalem;",
    "22": "Ge gebiddað þt ge nyton. we gebiddaþ þt we witon. forþam þe hæl is of iudeum.",
    "23": "ac seo tid cymð & nu is þonne soþe gebed-men gebiddaþ fæder on gaste. & on soðfæstnesse. witodlice fæder secþ swylce þe hyne gebiddon.",
    "24": "gast is god. & þam þe hyne gebiddað gebyrað þt hig gebiddon. on gaste and on soðfæstnesse;",
    "25": "Ðæt wíf cwæþ to him ic wat þt messias cymð þe is genemned crist. þonne he cymð he cyð us ealle ðing;",
    "26": "Se hælend cwæð to hyre. ic hit eom. þe wið þe sprece.",
    "27": "& þær-rihte comon his leorning-cnihtas. & hig wundredon þt he wiþ þt wíf spræc þeah hyra nan ne cwæð. hwæt segst (sic) þu oððe hwæt sprycst þu wið hig;",
    "28": "Witodlice þt wíf for-let hyre wæter-fæt. & eode to þære byrig & cwæð to þam mannum;",
    "29": "Cumað & geseoð þone man þe me sæde. ealle [þa] þing þe ic dyde. cweðe ge is he crist;",
    "30": "Ða eodon hi ut of ðære byrig & comon to him.",
    "31": "on gemang þam his leorning-cnihtas hine bædon. & þus cwædon lareow et.",
    "32": "Ða cwæð he to him. ic hæbbe þone mete to etene þe ge nyton;",
    "33": "Ða cwædon his leorning-cnihtas him betwynan hwæðer ænig man him mete brohte;",
    "34": "Ða cwæð se hælend to him. min mete is þt ic wyrce þæs willan ðe me sende. þt ic full-fremme his weorc;",
    "35": "Hv ne secge ge þt nu gyt synt feowur monðas ær man ripan mæge nu ic eow secge hebbað upp eowre eagan & geseoð þas eardas þt hig synt scire to ripene.",
    "36": "& se ðe ripð nimð mede & gaderaþ wæstm on ecum life þt æt-gædere geblission se þe sæwþ. & se ðe ripð.",
    "37": "on þyson is witodlice soð word forðam oþer is se ðe sæwþ oþer is se ðe ripþ;",
    "38": "Ic sende eow to ripene þt þt ge ne be-swuncon oðre swuncon & ge eodun on hyra geswinc;",
    "39": "Witodlice manige samaritanisce of ðære ceastre gelyfdon on hyne for þæs wífes wordon þe be him cyþde þt he sæde me ealle þa þing þe ic dyde;",
    "40": "Ða þa samaritaniscean comon to him hig gebædon hine þt he wunode ðæra (sic). & he wunode þær twegen dagas.",
    "41": "& mycle ma gelyfdon for his spæce.",
    "42": "& cwædon to þam wife. ne gelyfe we na for ðinre spræce. we sylfe gehyrdon. & we witon þt he is soþ middan-eardes hælynd;",
    "43": "Soðlice æfter twam dagon he ferde þanone. & for to galilea;",
    "44": "Se hælend sylf cyþde gewitnesse þt nan witega næfð nanne wurð-scype on hys agenum earde.",
    "45": "þa he com to galileam þa under-fengon hi hine þa hi gesawon ealle þa þing þe he worhte on ierusalem on freols-dæge. & hi comun to þam freols-dæge",
    "46": "& he com eft to chanaá galilee. þær he worhte þt wín of wætere; Sum under-cyning wæs. þæs sunu wæs gesyclod on capharnaum.",
    "47": "þa þa se gehyrde þt se hælend for fram iudea to galiléa he com to him & bæd hine þt he fóre & gehælde his sunu; Soðlice he læg æt forð-fore.",
    "48": "Ða cwæþ se hælend to him. buton ge tacna & fore-beacna geseon. ne gelyfe ge;",
    "49": "Ða cwæð se under-cing to him. drihten. far ær min sunu swelte.",
    "50": "& se hælend cwæð. Gá þin sunu leofað; Ða eode he & gelyfde þære spræce þe se hælend him sæde;",
    "51": "Ða he for þa urnon his þeowas ongean hyne & sædon þt his sunu leofode;",
    "52": "Ða axode he to hwylcon timan him bet wære. & hi sædon him gyrstan-dæg to þære seofoþan tide se fefor hine forlet;",
    "53": "Ða ongeat se fæder þt hit wæs on þære tide ðe se hælend cwæð þin sunu leofað. & he gelyfde & eall his hiw-ræden;",
    "54": "Se hælend worhte þis tácen eft oþre siþe þa he com fram iudea lande to galilea;"},

"5": {

    "1": "Æfter þyson wæs iudea freols-dæg & se hælend for to ierusalem;",
    "2": "On gerusalem ys án mére se is genemned on ebreisc betzaida; Se mere hæfð fif porticas",
    "3": "on þam porticon læg mycel menigeo ge-adludra blindra. & healtra. & for-scruncenra & ge-anbidedon þæs wæteres styrunge;",
    "4": "Drihtenes engel com to his timan on þone mere & þt wæter wæs astyred. & se þe raþust. com on þone mere æfter þæs wæteres styrunge wearþ gehæled fram swa hwylcere untrumnysse swa he on wæs;",
    "5": "Ðær wæs sum man eahta & þrittig wintra on his untrumnysse.",
    "6": "þa se hælend geseah þysne licgean & wiste þt he þær lange tide wæs; Ða cwæþ he to him wylt þu hal beon;",
    "7": "Ða &swarode se seoca him & cwæþ. drihten ic næbbe nanne man þt me do on þone mere þonne þt wæter astyred bið. ðonne ic cume þonne biþ oþer beforan me;",
    "8": "Ða cwæð se hælend to him aris nim þin bed & gá.",
    "9": "& se man wæs sona hal & he nam his bed & eode; Hit wæs reste-dæg on ðam dæge;",
    "10": "Ða cwædon þa iudeas to þam þe þar gehæled wæs. hit is reste-dæg nis ðe alyfed þt þu þin bedd bere",
    "11": "he &swarude him & cwæð; Se ðe me gehælde se cwæð to me. nim þin bedd & gá;",
    "12": "Ða áxsodon hi hine hwæt se man wære þe þe sæde nim þin bedd & gá.",
    "13": "Se þe þær gehæled wæs nyste hwa hit wæs; Se hælynd soþlice beah fram þære gegaderunge.",
    "14": "æfter þam se hælynd hine gemette on þam temple & cwæþ to him. nu þu eart hal geworden. ne synga þu. þe-læs þe þe on sumon þingon wyrs getide;",
    "15": "Ða for se man & cyðde hit þam iudean þt hit wære se hælend þe hyne hælde.",
    "16": "forþam þa iudéas ehton þone hælend. forðam þe he dyde þas þing on reste-dæge;",
    "17": "Ða &swarode se hælend him & cwæð. min fæder wyrcð oþ þis nu gýt. & ic wyrce.",
    "18": "þæs þe má. þa iudeas sohton hine to of-sleanne. næs na for-þam anum þe he þæne reste-dæg bræc. Ac forþam þe he cwæð þt god wære his fæder. & hine sylfne dyde gode gelícne.",
    "19": "Witodlice se hælend &swarode & cwæþ to him. soð ic eow secge. ne mæg se sunu nan þing don buton þt he gesyhþ his fæder dón. Ða þing þe he wyrcþ. se sunu wyrcð gelíce;",
    "20": "Se fæder lufað þone sunu. & geswutelað him ealle þa þing þe he wyrcþ. & maran weorc þonne þas sýn he geswutelað him þt ge wundrigeon;",
    "21": "Swa se fæder awecð þa deadan & geliffæst. swa eac se sunu geliffæst þa [ðe] he wyle.",
    "22": "ne se fæder ne demð nanum menn Ac he sealde ælcne dóm þam suna",
    "23": "þt ealle ar-wurþigeon þone sunu. swa swa hig arwurþigeaþ þone fæder; Se ðe ne arwurðaþ þone sunu. ne arwurþaþ he þone fæder þe hine sende;",
    "24": "[S]oð ic secge eow þt se þe min word gehyrð & þam gelyfð þe me sende. Se hæfþ éce líf & ne cymþ æt þam dome. ac færð fram deaðe to life;",
    "25": "Soð ic secge eow þt seo tid cymð & nu is. þonne þa deadan gehyrað godes suna stefne. & þa lybbað þe hig gehyrað.",
    "26": "swa se fæder hæfþ lif on him sylfon swa he sealde þam suna þt he hæfde lif on him syluon.",
    "27": "& sealde him anweald þt he moste deman. for-ðam þe he is mannes sunu;",
    "28": "Ne wundrigeon ge ðæs þt seo tíd cymð þt ealle gehyrað his stefne þe on byrgenum synt.",
    "29": "& þa þe god worhton farað on lifes æreste. & þa þe yfel dydon on domes æreste;",
    "30": "Ne mæg ic nan þing don fram me sylfum ic deme swa swa ic gehyre & min dom is ryht forðam ic ne séce minne willan [ac þæs] þe me sende;",
    "31": "Gif ic ge-witnesse be me cyþe. mín gewitnes nis soð;",
    "32": "Oþer is se ðe cyþ gewitnesse be me. & ic wát þt seo cyðnes is soð þe he cyþ be me.",
    "33": "ge sendon to iohanne & he cyðde soþfæstnesse gewitnesse;",
    "34": "Ic ne onfo gewitnesse fram menn. ac þas þing ic secge þt ge syn hale;",
    "35": "He wæs byrnende leoht-fæt & lyhtende. ge woldon sume hwile geblissian on his leohte;",
    "36": "Ic hæbbe maran gewitnesse þonne iohannes. witodlice þa weorc þe fæder me sealde þt ic hig full-fremme. Ða weorc þe ic wyrce cyþað gewitnesse be me þt fæder me asende.",
    "37": "& se fæder þe me sende cyþ gewitnesse be me; Ne ge næfre his stefne ne gehyrdon. ne ge his hiw ne gesawon;",
    "38": "And ge nabbað his word on eow wunigende. forþam þe ge ne gelyfað þam ðe he sende;",
    "39": "Smeageað halige gewritu forðam þe ge wenað þt ge habbon ece líf on þam. & hig synt þe gewitnesse cyþaþ be me",
    "40": "& ge nellað cuman to me þt ge habbon líf;",
    "41": "Ne under-fo ic nane beorht-nesse æt mannum.",
    "42": "Ac ic gecneow eow þt ge nabbaþ godes lufe on eow;",
    "43": "Ic com on mines fæder naman & ge me ne under-fengon. gyf oþer cymþ on his agenum naman hyne ge under-foð.",
    "44": "hu mage ge gelyfan. þe eow betweonan wuldor under-foð & ne seceaþ þt wuldor þe is fram gode syluum.",
    "45": "ne wene ge þt ic eow wrege to fæder. Se is þe eow wregð. moyses on þone ge ge-hyhtað;",
    "46": "Witodlice gif ge gelyfdon on moyse. ge gelyfdon eac me; Soðlice he wrat be me.",
    "47": "gif ge his stafum ne gelyfað. hu gelyfe ge minum wordum;"},

"6": {

    "1": "Æfter þyson for se hælend ofer þa galileiscan sæ. seo is tiberiádis.",
    "2": "& him fylide mycel folc for-þam þe hig gesawon þa tacna þe he worhte on þam þe wæron ge-untrumode;",
    "3": "Witodlice se Hælend astah on anne munt & sæt þar mid his leorning-cnihton.",
    "4": "hit wæs gehende eastron iudea freolsdæge;",
    "5": "Ða se hælend his eagan up-ahóf & geseah þt micel folc com to him. he cwæð to philippe; Hwær bicge we hlafas þt þas eton.",
    "6": "þt he cwæþ his fandigende he wiste hwæt he don wolde;",
    "7": "Ða &wurde him philippus. & cwæð nabbað hi genoh on twegera hundred penega wurþe hlafes þt ælc sumne dæl nyme;",
    "8": "Ða &wyrde him an his leorning-cnihta andreas simones broþur petres;",
    "9": "Her is an cnapa þe hæfþ fíf berene hlafas & twegen fixas. ac hwæt synt þa þing betwux swa manegum mannum;",
    "10": "Ða cwæð se hælend. doð þt þas men sitton. on þære stowe wæs mycel gers. ðær sæton þa swylce fíf þusendo manna;",
    "11": "Se hælend nam þa hlafas & þanc-wurðlice dyde & hig to-dælde þam sittendum & eall-swa of þam fixum swa mycel swa hig woldon;",
    "12": "Ða hig fulle wæron. þa cwæð he to his leorning-cnihton. gaderiaþ þa brytsena þe þar to lafe wæron þt hig ne losigeon.",
    "13": "hig gegaderedon & fyldon twelf wyligeon fulle þæra brytsena of þam þe þa læfdon þe of þam fif berenan hlafon æton.",
    "14": "Ða men cwædon þa hig gesawon þt he þt tacen worhte. þt þes is soðlice witega þe on middan-geard cymþ.",
    "15": "Ða se hælend wiste þt hig woldon cuman & hine gelæccean & to cynge dón. þa fleah he ana uppon þone munt;",
    "16": "<>",
    "17": "And þa hig eodon on scyp hi comon ofer þa sæ to capharnaum. hit wearð þa þystre & se hælend ne com to him.",
    "18": "mycel wind bleow & hit wæs hreoh sæ;",
    "19": "Witodlice þa hig hæfdon gehrowen swylce twentig furlanga oððe þrittig. þa gesawon hig þone hælend uppan þære sæ gán & þt he wæs gehende þam scype. & hi him ondredon.",
    "20": "he cwæð þa to him; Ic hit eom. ne ondrædað eow;",
    "21": "Hig woldon hyne niman on þt scyp & sona þt scyp wæs æt þam lande þe hig woldon to faran;",
    "22": "Soþlice oþre dæg seo menigeo þe stod begeondan þam mere. geseah þt þær næs butan an scyp. & þt se hælend ne eode on scyp mid his leorning-cnihtan. ac his leor[n]ing-cnihtas sylfe ana foron.",
    "23": "oðre scypu comon fram tiberiade wið þa stowe þar hig þone hlaf æton drihtne þanciende.",
    "24": "Ða seo menigeo geseah þt se hælend þar næs ne his leorning-cnihtas. þa eodon hig on scipu & coman to capharnaum sohton ðone hælend",
    "25": "& þa hig gemetton hyne begeondon þam mere hig cwædon to him; Lareow hwænne com þu hider;",
    "26": "Se hælend him &swarude & cwæð. Soþ ic eow secge ne sece ge me forðam þe ge tacnu gesawon. Ac for-þam þe ge æton of ðam hlafon & synt fulle.",
    "27": "Ne wyrceaþ æfter þam mete þe for-wyrð. Ac æfter þam þe þurh-wunað on ece lif. ðone mannes sunu eow sylþ. þone god fæder getacnode;",
    "28": "Hig cwædon to him. hwæt do we þt we wyrceon godes weorc",
    "29": "þa &swarode se hælend & cwæð to him. þt is godes weorc þt ge gelyfan on ðone þe he sende;",
    "30": "Ða cwædon hig hwæt dest þu to tacne þt we geseon & gelyfon þt þu hit wyrce.",
    "31": "ure fæderas æton heofonlicne mete on westene swa hit awriten is. he sealde him etan hlaf of heofone;",
    "32": "Se hælend cwæð to him. soð ic secge eow ne sealde moyses eow hláf of heofonum. ac min fæder eow sylþ soðne hláf of heofonum",
    "33": "hit is godes hláf þe of heofone com & sylþ middan-earde lif;",
    "34": "Hig cwædon to him. drihten. syle us þysne hláf.",
    "35": "se hælend cwæð to him; Ic eom lifes hlaf ne hingrað þone þe to me cymð & ne þyrst þone næfre ðe on me gelyfð.",
    "36": "ac ic eow sæde þt ge gesawon me & ne gelyfdon;",
    "37": "Eall þt fæder me sylþ cymð to me & ic ne wyrpe ut ðone þe to me cymð.",
    "38": "forþam þe ic ne com of heofonum þt ic minne willan do. ac þæs willan þe me sende;",
    "39": "Ðæt is þæs fæder willa ðe me sende þt ic nan þing ne forleose. of ðam þe he me sealde. ac awecce þt on þam ytemestan dæge;",
    "40": "Ðis is mines fæder willa þe me sende þt ælc þe ðone sunu gesyhþ & on hine gelyfð. hæbbe ece líf & ic hine awecce on þam ytemestan dæge;",
    "41": "Ða murcnodon þa iudeas be him. forþam þe he cwæð ic eom hlaf þe of heofonum com",
    "42": "& hig cwædon; Hu nis þis se hælend iosepes sunu. we cunnon his fæder & his modor. humeta segð þes ic com of heofonum;",
    "43": "Se hælend him &swarode & cwæð to him. ne murcniaþ eow betwynan;",
    "44": "Ne mæg nan man cuman to me buton se fæder þe me sende hyne téo & ic hine arære on ðam ytemestan dæge;",
    "45": "On ðære (sic) witegena bocum is awriten. ealle eaðlære beoð godes; Ælc þe gehyrde æt fæder & leornode. cymð to me;",
    "46": "Ne ge-seah nan man fæder buton se ðe is [of] gode se gesyhþ fæder;",
    "47": "Soð ic secge eow se hæfð ece lif þe on me gelyfð.",
    "48": "ic eom lifes hláf.",
    "49": "ure fæderas æton heofunlicne mete on westene & hig synd deade;",
    "50": "Ðis is se hlaf þe of heofonum com. þt ne swelte se ðe of him ytt;",
    "51": "Ic eom lybbende hlaf þe of heofonum com. swa hwa swa ytt of ðyson hlafe. he leofað on ecnysse. & se hlaf þe ic sylle is min flæsc for middan-eardes life;",
    "52": "Þa iudeas fliton him betwynan & cwædon. hu mæg þes his flæsc us syllan to etene.",
    "53": "Þa cwæþ se hælend to hiM; Soþ ic secge eow næbbe ge lif on eow buton ge eton mannes suna flæsc & his blod drincon;",
    "54": "Se hæfð ece líf þe ytt min flæsc & drincð min blod. & ic hine arære. on þam ytemestan dæge;",
    "55": "Soþlice min flæsc is mete & min blod is drinc.",
    "56": "se ðe ytt min flæsc & drincð min blod he wunað on me. & ic on him.",
    "57": "swa swa lybbende fæder me sende & ic lybbe þurh fæder & se ðe me ytt he leofaþ þurh me.",
    "58": "þis is se hlaf þe of heofonum cóm. na swa swa ure fæderas æton heofonlicne mete & deade wæron; Se þe ytt þysne hlaf he leofað on ecnysse;",
    "59": "Ðas þing he sæde on gesamnunge þa he lærde on capharnaum;",
    "60": "Manega his leorni[n]g-cnihta cwædon þa hig ðis gehyrdon; Heard is þeos spræc hwa mæg hig gehyran;",
    "61": "Ða wiste se hælend þt his leorning-cnihtas murcnedon betweox him sylfon be þison. & he cwæð to him þt eow beswicð.",
    "62": "gyf ge geseoþ mannes sunu astigendne þær he ær wæs",
    "63": "gast is se ðe geliffæst flæsc ne fremað nan þing. þa word þe ic eow sæde synt gast & líf.",
    "64": "Ac sume ge ne gelyfað; Witodlice se hælend wiste æt fruman. hwæt þa gelyfedan wæron & hwa hine belæwon wolde.",
    "65": "& he cwæð; Forþig ic eow sæde þt nan man ne mæg cuman to me buton min fæder hit him sylle;",
    "66": "Syððan manega his leorning-cnihtas (sic) cyrdon. onbæc & ne eodun mid him.",
    "67": "Ða cwæþ se hælynd to þam twelfum. cweðe ge wylle ge fram me.",
    "68": "þa &wyrde him simon Petrus & cwæð; Drihten to hwam ga we þu hæfst eces lifes word",
    "69": "& we gelyfað & witon þt þu eart crist godes sunu;",
    "70": "Se hælend him &swarude & cwæð. hu ne geceas ic eow twelfe & eower an is deofol.",
    "71": "he hyt cwæþ be iuda scarioþe þes hine belæwde þa he wæs an þara TWELFA."},

"7": {

    "1": "Syþþan for se hælend to galilea. he nolde faran to iudea forþam þe þa iudéas hine sohton & woldon hyne ofsléan",
    "2": "hit wæs gehende iudea freols-dæge;",
    "3": "His broðra cwædon to him. far heonon & ga on iudea land. þt þine leorning-cnihtas geseon þa weorc þe þu wyrcst;",
    "4": "Ne deð nan man nan þing on diglum. ac secþ þt hit open sy; Gif ðu þas þing dest geswutela þe sylfne middan-earde;",
    "5": "Witodlice ne his magas ne gelyfdon on hyne;",
    "6": "Ða cwæþ se hælend to him gyt ne cóm min tíd. eower tid is symble gearu.",
    "7": "ne mæg middan-eard eow hatigean ac he hatað me forþam ic cyþe gewitnesse be him þt his weorc synt yfele;",
    "8": "Fare ge to þison freols-dæge. ic ne fare to þison freols-dæge forþam min tid nis gyt gefylled;",
    "9": "He wunede on galilea þa he þas þing sæde;",
    "10": "Eft þa his gebroðru foron þa for he eac to ðam freols-dæge. næs na openlice [ac dygollice.]",
    "11": "Ða iudeas hyne sohton on þam freols-dæge & cwædon. hwar is he.",
    "12": "& mycel gehlyd wæs on þære menigeo be him. Sume cwædon. he is god. oðre cwædon. nése. ac he be-swicð þis folc.",
    "13": "þeah-hwæþere ne spæc nan man openlice be him for þæra iudéa ege;",
    "14": "Þa hit wæs mid dæg þæs freols-dæges þa eode se hælend into þam temple & lærde.",
    "15": "& þa iudeas wundredon & cwædon; Humeta cann þes stafas þonne he ne leornode.",
    "16": "Se hælend him &swarode & cwæþ. mi[n] lar nis na min. ac þæs þe me sende.",
    "17": "gyf hwa wyle his willan don he gecwemð (sic) be þære lare hwæþer heo si of gode hwæþer þe ic be me sylfum spece;",
    "18": "Se þe be him sylfum sprycð secþ his agen wuldor se þe secþ þæs wuldor þe hyne sende. se is soþfæst. & nis nan unrihtwisnys on him;",
    "19": "Hu ne sealde moyses eow .æ. & eower nan ne healt þa .æ. Hwi séce ge me to of-sleanne.",
    "20": "þa &swarode seo menigeo & cwæð. deofol þe sticað on. hwa secð þe to of-sleanne;",
    "21": "Ða &swarode se hælend & cwæð to him. an weorc ic worhte & ealle ge wundrigeaþ.",
    "22": "forðý moyses eow sealde ymbsnydenysse næs na forþi þe heo of moyse sy ac of fæderon. & on reste-dæge ge ymb-sniðaþ mann.",
    "23": "þt moyses .æ. ne sy toworpen. & ge belgaþ wið me forðam þe ic gehælde anne man. on reste-dæge.",
    "24": "ne deme ge be ansyne ac demað rihtne dom;",
    "25": "Sume cwædon þa ðe wæron of ierusalem. hu nis ðis se ðe hi seceaþ to of-sleande.",
    "26": "& nu he spycþ openlice & híg ne cweðaþ nan ðing to him; Cweðe we. hwæþer þa ealdras ongyton þt þis is crist.",
    "27": "ac we witon. hwanon þes is; Ðonne crist cymþ. þonne nat nan mann hwanon he biþ;",
    "28": "Se hælend clypode & lærde on þam temple. & cwæð. Me ge cunnon & ge witon hwanon ic eom. & ic ne com fram me sylfum. ac se is soð þe me sende þone ge ne cunnon;",
    "29": "Ic hyne can. & gif ic secge þt ic hine ne cunne. ic beo leas & eow gelic. Ic hyne can & ic eom of him & he me sende.",
    "30": "hig hine sohton to nimanne & hyra nan hys ne æt-hran. forðam þe his tid ne com þa gyt;",
    "31": "Manega of ðære menigeo gelyfdon on hine & cwædon. Cweþe ge wyrcð crist ma tacna þonne he cymð þonne þes deð.",
    "32": "þa pharisei gehyrdon þa menigeo þus murcnige[n]de be him; Ða ealdras & ða pharisei sendon hyra þenas þt hig woldon hine gefón;",
    "33": "Ða cwæð se hælend gyt ic beo sume hwile mid eow & ic ga to ðam þe me sende;",
    "34": "Ge secað me & ne findaþ. & ge ne magon cuman þar ic eom.",
    "35": "þa iudeas cwædon betweonan him sylfum hwyder wyle þes faran þt we hine ne findon. cwyst þu wyle he faran on ðeoda todræfednysse & hig læran;",
    "36": "Hwæt is ðeos spræc þe he sprycð ge seceaþ me & ne findaþ. & ge ne magon cuman þar ic eom;",
    "37": "On þam æftemestan mæran freols-dæge stod se hælend & clypode. cume to me se ðe hine þyrste & drince;",
    "38": "Se þe gelyfþ on me swa þt ge-writ cwyð. lybbendes wætres flod flowað of his innoðe.",
    "39": "þt he cwæð be þam gaste þe þa sceoldon under-fon þe on hyne gelyfdon. þa gyt næs se gast geseald. forþam þe se hælend næs ða gyt gewuldrud;",
    "40": "Of ðære tide seo menigeo cwæð þa heo gehyrde ðas his spræce. ðes is soð witega",
    "41": "sume cwædon he is crist; Sume cwædon cweðe ge cymþ crist fram galilea.",
    "42": "hu ne cyð (sic) þt ge-writ þt crist cymð of dauides cynne & of bethleem ceastre. þar þar dauid wæs;",
    "43": "Witodlice ungeþwærnes wæs geworden on þære menigeo for him;",
    "44": "Sume hig woldon hine niman. ac hyra nan his næ æt-hran.",
    "45": "þa þenas comon to þam bisceopum & to þam phariseon & hig cwædon to him; For hwi ne brohton ge hine hider.",
    "46": "þa &wyrdon þa þenas & cwædon; Ne spræc næfre nan man swa þes man sprycþ.",
    "47": "Þa cwædoN þa pharisei to him. synt ge beswicene.",
    "48": "cweðe ge gelyfde ænig þæra ealdra oððe þæra pharisea on hyne.",
    "49": "ac þeos menigeo þe ne cyþe þa æ. hig synt awyrgede;",
    "50": "Ða cwæð nichodemus to him; Se þe com to him on nyht se wæs hyra án.",
    "51": "cwyst þu demð ure æ. ænine man buton hyne man ær gehyre & wite hwæt he do;",
    "52": "Hig &swaredon & cwædon to him. cwyst þu. þt þu si galileisc. smea & geseoh þt nan witega ne cymð fram galilea.",
    "53": "& hig cyrdon ealle ham;"},

"8": {

    "1": "Se hælend for on oliuetes dune.",
    "2": "& com eft on dæg-red to þam temple. & eall þt folc com to him. & he sæt & lærde hig;",
    "3": "Ða læddon þa pharisei & ða boceras to him an wif seo wæs aparod on unriht-hæmede & setton hig to-middes hyra",
    "4": "& cwædon to him; Láreow. þis wif wæs afundyn on unriht-on hæmede;",
    "5": "Moyses us bebead on þære .æ. þt we sceoldon þus gerade mid stanum of-torfian. hwæt cwyst þu;",
    "6": "Ðis hig cwædon his fandiende þt hig hine wrehton. Se hælend abeah nyþer & wrat mid his fingre on þære eorþan.",
    "7": "þa hig þurh-wunedon hine axsiende þa aras he upp & cwæð to him; Loca hwylc eower si synleas wurpe ærest stan on hi.",
    "8": "& he abeah eft & wrat on þære eorþan;",
    "9": "Ða hig þis gehyrdon þa eodon hig ut an æfter anum. & he gebad þar sylf & þt wif stod þær on middan;",
    "10": "Se hælend aras upp & cwæð to hyre. wif hwær synd þa ðe þe wregdon ne fordemde þe nan man.",
    "11": "& heo cwæð ná drihten. & se hælend cwæð. ne ic þe ne fordeme. do ga & ne synga þu næfre ma;",
    "12": "Eft se hælend spræc þas þing to him & cwæð. ic eom middan-eardes leoht; Se þe me fyliþ ne gæð he na on þystro ac he hæfð lifes leoht;",
    "13": "Ða pharisei cwædon to him. Þu cystþ (sic) gewitnesse be ðe sylfon. nis ðin gewitnes soð;",
    "14": "Se hælend &swarede. & cwæð to him; Gif ic cyþe gewitnesse be me sylfum min gewitnes is soþ. forþam þe ic wat hwanon ic com & hwyder ic ga. ge nyton hwanon ic com ne hwyder ic ga.",
    "15": "ge demað æfter flæsce. ic ne deme nanum men",
    "16": "& gif ic deme. min dom is soð; Forðam þe ic ne eom ána. ac ic & se fæder þe me sende;",
    "17": "And [on] eowre .æ. is awriten þt twegra manna gewitnes is soð;",
    "18": "Ic eom þe cyþe gewitnesse be me sylfum. & se fæder þe me sende cyþ ge-witnesse be me;",
    "19": "Witodlice hig cwædon to him hwar is þín fæder; Se hælend him &swarude & cwæð. ne cunne ge me ne minne fæder; Gyf ge me cuþon wen is þt ge cuþon minne fæder;",
    "20": "Ðas word he spæc æt cep-sceamule & nan man hyne ne nam. forþam þe hys tid ne com þa gyt.",
    "21": "witodlice eft se hælend cwæþ to HIM; Ic fare & ge me seceað. & ge sweltaþ on eowre synne. ne mage ge cuman þyder ic fare;",
    "22": "Ða cwædon þa iudeas. cweðe ge. of-slyhþ he hine sylfne forþam he segð. ge ne magon cuman þyder ic fare;",
    "23": "Ða cwæþ he to him ge synt nyþane. & ic eom ufane. ge synt of þison middan-earde; Ic ne eom of þissan middan-earde;",
    "24": "Ic eow sæde þt ge sweltað on eowrum synnum gif ge ne gelyfað þt ic hit sý. ge sweltað on eowre synne;",
    "25": "Ða cwædon hi to him hwæt eart þu; Se hælend cwæð to him. ic eom fruma þe to eow sprece.",
    "26": "ic hæbbe fela be eow to sprecenne & to demenne; Ac se þe me sende is soðfæst. & ic sprece on middan-earde þa þing þe ic æt him gehyrde.",
    "27": "& hig ne under-geton þt he tæalde him god to fæder;",
    "28": "Se hælend cwæð to him þonne ge mannes sunu upp ahebbaþ þonne gecnawe ge þt ic hit eom. & ic ne do nan þing of me sylfum. ac ic sprece þas þing swa fæder me lærde.",
    "29": "& se ðe me sende is mid me. & he ne forlæt me anne forþam þe ic wyrce symble þa þing þe him synt gecweme.",
    "30": "ða he ðas ðing spræc manega gelyfdon ON HIM;",
    "31": "Witodlice se hælend cwæð to þam iudeon þe him gelyfdon. gif ge wunegeað on minre spæce. soðlice ge beoð mine leorning-cnihtas.",
    "32": "& ge oncnawað soðfæstnysse. & soþ-fæstnes eow alyst;",
    "33": "Ða &swarodon hi him & cwædon. we synt abrahames cynnes. & ne þeowedon we nanum men næfre. humeta cwyst þu ge beoð frige;",
    "34": "Se hælend him &swarude & cwæð soþ ic eow secge þt ælc þe synne wyrcð is þære synne þeow;",
    "35": "Witodlice se þeow ne wunaþ on huse on ecnesse; Se sunu wunaþ on ecnesse.",
    "36": "gif se sunu eow alyst ge beoð soðlice frige.",
    "37": "Ic wat þt ge synt abrahames bearn. ac ge seceað me to of-sleanne forþam min spæc ne wunaþ on eow;",
    "38": "Ic sprece þt þe ic mid fæder geseah. & ge doð þa þing þe ge mid eowrum fæder gesawon;",
    "39": "Ða &swarodon hig & cwædon to him. abraham is ure fæder; Ða cwæð se hælend to him. gif ge abrahames bearn synt wyrceað abrahames weorc.",
    "40": "nu ge seceað me to of-sleanne þone man þe eow sæde soðfæstnesse þa þe ic gehyrde of gode; Ne dyde abraham swa",
    "41": "ge wyrceað eowres fæder weorc; Hig cwædon witodlice to him. ne synt we of forlire acennede. we habbað anne god to fæder;",
    "42": "Witodlice se hælend cwæþ to him gif god wære eowre fæder. witodlice ge lufedon me. Ic com of gode ne com ic na fram me sylfon ac he me sende;",
    "43": "Hwi ne gecnawe ge mine spræce. [forþam þe ge ne magon gehyran mine spæce.]",
    "44": "ge synt deofles bearn. & ge wyllaþ wyrcean eowres fæder willan. he wæs fram frymþe mán-slaga & he ne wunode on soðfæst-nesse forðam þe soðfæstnes nis on him; Ðonne he sprycð leasunga he sprycþ of him sylfum. forþam þe he is leas & his fæder eac;",
    "45": "Witodlice ge ne gelyfað me forþam þe ic secge eow soðfæstnysse;",
    "46": "Hwylc eower ascunað me for synne gif ic soð secge. hwi ne gelyfe ge me;",
    "47": "Se þe is of gode gehyrð [godes] word. forþig ge ne gehyrað. forþam þe ge ne synt of gode;",
    "48": "Witodlice þa iudeas &swaredon & cwædon to him; Hwi ne cweþe we wel þt ðu eart samaritanisc & eart wód.",
    "49": "Se hælend &swarude & cwæð. Ne eom ic wód ac ic arwurþige minne fæder. & ge unarwurðedon me.",
    "50": "witodlice ne sece ic min wuldor. se is. þe secð & demð;",
    "51": "Soðlice ic secge eow gif hwa mine spræce gehealt ne gesyhþ he deað næfre;",
    "52": "Ða cwædon þa iudeas nu we witon þt þu eart wód. abraham wæs dead & þa witegan. & þu cwyst gif hwa mine spræce gehealt ne bið he næfre dead;",
    "53": "Cwyst þu þt þu sy mærra þonne ure fæder abraham. se wæs dead & þa witegan wæran (sic) deade. hwæt þincð þe þt þu sy;",
    "54": "Se hælend him &swarode. gif ic wuldrige me sylfne nis min wuldor naht. min fæder is þe me wuldrað. be þam ge cweðaþ þt he sy ure god",
    "55": "& ge ne cuðon hine; Ic hyne cánn. & gif ic secge þt ic hine ne cunne. ic beo leas & eow gelic. ac ic hyne cann & ic healde his spræce;",
    "56": "Abraham eower fæder geblissode þt he gesawe minnæ (sic) dæg & he geseah & geblissode;",
    "57": "Ða iudeas cwædon to him. gyt þu ne eart fiftig wintre & gesawe þu abraham;",
    "58": "Se hælend cwæð to him. ic wæs ærþam þe abraham wæs;",
    "59": "hig namon stánas to þam þt hig woldon hyne torfian. Se hælend Hine bedilegode & eode of ðam temple."},

"9": {

    "1": "Ða se hælend fór þa geseah he anne man þe wæs blind geboren.",
    "2": "& his leorning-cnihtas hine axodon & cwædon; Láreow. hwæt syngode þes. oððe his magas þt he wære blind geboren;",
    "3": "Se hælend &swarude & cwæð. ne syngode he ne his magas. ac þt godes weorc wære geswutelod on him;",
    "4": "Me gebyrað to wyrceanne þæs weorc þe me sende þa hwile þe hit dæg is niht cymþ þonne nan man wyrcan ne mæg;",
    "5": "Ic eom middan-eardes leoht þa hwile þe ic on middan-earde eom.",
    "6": "Ða he þas þing sæde. þa spættes he on þa eorþan & worhte fenn of his spatle. & smyrede mid þam fenne ofer his eagan",
    "7": "& cwæð to him; Gá & þweah þe on syloes mere he for & þwoh hine & com geseonde;",
    "8": "Witodlice his neah-geburas & þa þe hine gesawon þa he wædla wæs cwædon hu nis þis se ðe sæt & wædlode.",
    "9": "Sume cwædon he hyt is; Sume cwædon nese. ac is him gelíc; He cwæþ soðlice. ic hit eom;",
    "10": "Ða cwædon hig to him. hu wæron þine eagan geopenede.",
    "11": "he &swarode & cwæð; Se man þe is genemned hælend worhte fenn & smyrede mine eagan. & cwæð to me; Gá to syloes mere & þweah þe. & ic eode. & þwoh me & geseah;",
    "12": "Ða cwædon hig to him. hwar is he. þa cwæð he. ic nat;",
    "13": "Hig læddon to þam phariseon þone þe þar blind wæs.",
    "14": "hit wæs reste-dæg þa se hælend worhte þt fenn. & his eagan untynde;",
    "15": "Eft þa pharisei hyne axsedon hu he gesawe. he cwæð to him he dyde fenn ofer mine æagan & ic þwoh & ic geseo;",
    "16": "Sume þa pharisei cwædon nis ðes man of gode þe reste-dæg ne healt; Sume cwædon hu mæg synful mann þas tacn wyrcean. & hig fliton him betweonan;",
    "17": "Hig cwædon eft to þam blindan. hwæt segst þu be þam þe þine eagan untynde. he cwæð he is witega;",
    "18": "Ne gelyfdon þa iudeas be him. þt he blind wære & gesawe ærþam þe hig clypodon his magas þe gesawon",
    "19": "& axodon hig. & cwædon; Is ðis eower sunu þe ge secgað þt blind wære acenned. hu-meta gesyhþ he nu;",
    "20": "Hys magas him &swaredon & cwædon we witon þt þes [is] ure sunu & þt he wæs bli[n]d acenned.",
    "21": "we nyton hu-mete he nu gesyhþ ne hwa his eagan untynde; Ahxsiað hine sylfne. yllde he hæfð. sprece for hine sylfne;",
    "22": "His magas spæcon þas þing forþam þe hig ondredon þa iudeas; Ða gedihton þa iudeas gif hwa crist andette þt he wære butan hyra geferrædene.",
    "23": "forþam cwædon his magas. he hæfþ ylde axiað hine sylfne;",
    "24": "Ða clypodon hig eft þone mann þe ær blind wæs. & cwædon to him; Sege gode wuldor. we witon þt he is synful.",
    "25": "& he cwæð gif he synful is. þt ic nat. an þing ic wat þt ic wæs blind. & þt ic nu geseo;",
    "26": "Ða cwædon hig to him hwæt dyde he þe. hu ontynde he þine eagan.",
    "27": "he &swarode him & cwæð. ic eow sæde ær & ge gehyrdon. hwi wylle ge hyt eft gehyran. cweðe ge wylle ge beon his leorning-cnihtas;",
    "28": "Þa wyrigdon hig hine & cwædon. si þu his leorning-cniht we synt moyses leorning-cnihtas.",
    "29": "we witon þt god spæc wiþ moyses. nyte wé hwanon þes is;",
    "30": "Se man &swarode & cwæð to him. þt is wundorlic þt ge nyton hwanon he is & he untynde mine eagan.",
    "31": "we witon soþlice þt god ne gehyrþ synfulle. ac gif hwa is gode gecoren & his willan wyrcð. þone he gehyrð;",
    "32": "Ne gehyrde we næfre on worulde þt ænig ontynde þæs eagan þe wære blind geboren.",
    "33": "ne mihte þes nan þing don gif he nære of gode;",
    "34": "hig &swaredon & cwædon to him. eall þu eart on synnum geboren & þu lærst us. & hig drifon hine ut;",
    "35": "Ða se hælend gehyrde þt hig hyne drifon út. þa cwæð he to him þa he hine gemitte gelyfst þu on godes sunu.",
    "36": "he &swarude & cwæð. hwylc is drihten þt ic on hine gelyfe;",
    "37": "And se hælend cwæð to him. þu hine gesawe. & se ðe wið þe sprycð se hit is;",
    "38": "Ða cwæþ he drihten. ic gelyfe. & he feoll nyþer & ge-eaðmedde hyne.",
    "39": "& se hælend cwæð to him; Ic com on þysne middan-eard to demenne þt þa sceolon geseon. þe ne geseoð. & beon blinde þa þe geseoð;",
    "40": "Ða þt gehyrdon þa pharisei þe mid him wæron; Ða cwædon hig to hym; Cwyst þu synt we blinde.",
    "41": "& se hælend cwæð to him. gif ge blinde wæron næfde ge nane synne; Nu ge secgað. þt þt ge geseon. þt is eowre synn;"},

"10": {

    "1": "Soþ ic secge eow se þe ne gæð æt þam gete into sceapa falde. ac styhþ elles ofer he is þeof & sceaða;",
    "2": "Se þe in-gæþ æt þam geate. he is sceapa hyrde",
    "3": "þæne se geat-weard læt in. & þa sceap gehyrað his stefne. & he nemð his agene sceap be naman [&] læt hig ut.",
    "4": "& þonne he his agene sceap læt út he gæð beforan him. & þa sceap him fyligeað forþam þe hig gecnawað his stefne;",
    "5": "Ne fyligeaþ hig uncuþum ac fleoð fram him. forðam þe hig ne gecneowun úncuðra stefne;",
    "6": "Ðis bigspell se hælend him sæde. hig nyston hwæt he spræc to him;",
    "7": "Eft se hælend cwæð to him; Soþ ic eow secge. ic eom sceapa geat.",
    "8": "ealle þa þe comun wæron þeofas & sceaþan. ac þa sceap hig ne gehyrdon.",
    "9": "ic eom geat swa hwylc swa þurh me gæð byþ hal. & gæð in & út & fint læse.",
    "10": "þeof ne cymð buton þt he stele & sléa. & fordo; Ic com to þam þt hig habbon líf & habbon genoh;",
    "11": "Ic eom god hýrde. god hyrde sylþ his lif for his sceapon;",
    "12": "Se hýra se þe nis hyrde. & se þe nah þa sceap. þonne he þone wulf gesyhþ þonne flyhð he & forlæt þa sceap. & se wulf nimð & todrif[ð] ða sceap;",
    "13": "Se hýra flyhþ forþam þe he bið ahýrod. & him ne gebyrað to þam sceapum;",
    "14": "Ic eom god hyrde & ic gecnawe mine sceap & hig gecnawað me;",
    "15": "Swa min fæder can me. ic can minne fæder.",
    "16": "& ic hæbbe oðre sceap þa ne synt of ðisse heorde. & hit gebyrað þt ic læde þæge & hig gehyrað mine stefne & hyt byþ an heord & an hyrde",
    "17": "forþam fæder me lufað. forþam þe ic sylle mine sawle & hig eft nime;",
    "18": "Ne nimð hig nan man æt me. ac læte hig fram me sylfum; Ic hæbbe anweald mine sawle to alætane & ic hæbbe anweald hig eft to nimanne. þis bebod ic nam æt minum fæder;",
    "19": "Eft wæs ungeðwærnes geworden be-twyx þam iudeum for þysum spræcum.",
    "20": "manega hyra cwædon. deofol is on him & he cwæð (sic) hwi hlyste ge him;",
    "21": "Sume cwædon ne synt na þis wodes mannes word. cwyst þu. mæg wod man blindra manna eagan ontynan;",
    "22": "Þa wæron templ-halgunga on ierusalem & hit wæs winter",
    "23": "& se hælend eode on þam temple on salomones portice;",
    "24": "Ða bestodon þa iudeas hyne utan & cwædon to him. hu lange gælst þu úre líf. Sege us openlice hwæþer þu crist sy;",
    "25": "Se hælend him &swarode & cwæþ. ic spece to eow & ge ne gelyfað. þa weorc þe ic wyrce on mines fæder naman. þa cyþaþ gewitnesse be me.",
    "26": "ac ge ne gelyfað. forþam þe ge [ne] synt of minum sceapum;",
    "27": "mine sceap gehyraþ mine stefne. & ic gecnawe hig. & hig folgiað me.",
    "28": "& ic him sylle éce líf & hig ne forwurðaþ næfre & ne nimð hig nan man of minre handa",
    "29": "þt þe min fæder me sealde is mærre þonne ænig oðer ðing. & ne mæg hit nan man niman of mines fæder handa.",
    "30": "ic & fæder synt an;",
    "31": "Ða iudeas namon stanas þt hig woldon hyne torfian;",
    "32": "Se hælend him &swarode & cwæð. manega gode weorc ic eow æt-eowde be minum fæder for hwylcum þære weorca wylle ge me hænan.",
    "33": "þa iudeas him &swaredon & cwædon. ne hæne we ðe for godum weorce ac for þinre bysmor-spæce & forþam þe þu eart man & wyrcst þe to gode;",
    "34": "Se hælend [him] &swarode & cwæð hu nys hit awriten on eowre æ. þt ic sæde ge synt godas.",
    "35": "gif he þa tealde godas þe godes spæc to wæs geworden & þt halige gewrit ne mæg beon awend",
    "36": "þe fæder gehalgode & sende on middan-eard. ge secgað þt þu bysmor spycst forþam ic sæde ic eom godes sunu;",
    "37": "Gif ic ne wyrce mines fæder weorc. ne gelyfað me;",
    "38": "Gif ic wyrce mines fæder weorc & gif ge me nellað gelyfan. gelyfað þam weorcum. þt ge oncnawun & gelyfon þt fæder ys on me & ic on fæder;",
    "39": "Hig smeadon witodlice embe þt hig woldon hine gefon & he eode ut fram him;",
    "40": "& he for eft ofer iordanén to þære stowe þe iohannes wæs. & ærest on fullode & he wunode þar.",
    "41": "& manega comon to him & cwædon. witodlice ne worhte iohannes nan tacn. ealle þa þing þe iohannes sæde be þyson wæron soðe",
    "42": "& manega gelyfdon on hyne."},

"11": {

    "1": "Witodlice sum seoc man wæs genemned lazarus of bethania of marian ceastre & of martham his swustra.",
    "2": "hit wæs séo maría þe smyrede drihten mid þære sealfe & drigde his fet mid hyre loccon; Lazarus hyre broðor wæs ge-yfled.",
    "3": "his swustra sendon to him & cwædon dríhten. nu is seoc se ðe þu lufast.",
    "4": "Ða se hælend þt gehyrde. þa cwæð he to him; Nys þeos untrumnys na for deaðe. ac for godes wuldre þt godes sunu si gewuldrod þurh hyne;",
    "5": "Soðlice se hælend lufode martham. & hyre swustor maríam & lazarum hyra broðor;",
    "6": "Witodlice he wæs twegen dagas on ðære sylfan stowe þa he gehyrde þt he seoc wæs;",
    "7": "Æfter þisson he cwæð to his leorning-cnihton uton faran eft to iudea lande.",
    "8": "his leorning-cnihtas cwædon to him. láreow. nu þa iudeas sohton ðe þt hig woldon þe hænan. & wylt þu eft faran ðyder;",
    "9": "Se hælend him &swarode & cwæð. hu ne synt twelf tida þæs dæges. gif hwa gæð on dæg ne æt-spy[r]nð he forþam he gesyhþ þyses middan-eardes leoht;",
    "10": "Gif he gæð on niht he æt-spyrnð forþam þe leoht nis on hyre;",
    "11": "Ðas ðing he cwæð & syððan he cwæð to him. lazarus ure freond slæpð. ac ic wylle gan & awreccan (sic) hyne of slæpe;",
    "12": "His leorning-cnihtas cwædon. drihten gif he slæpð. he byþ hal;",
    "13": "Se hælend hit cwæð be his deaþe. hi wendon soðlice þt he hyt sæde be swefnes slæpe;",
    "14": "Ða cwæð se hælend openlice to him. Ladzarus ys dead.",
    "15": "& ic eom bliþe for eowrum þingon þt ge gelyfon forþam ic næs þara ac uton gán to him;",
    "16": "Ða cwæð thomas to hys geferan. uton gan & sweltan mid him;",
    "17": "Ða for se hælend & gemette þt he wæs forð-faren & for feower dagon bebyrged;",
    "18": "Bethanía ys gehende ierusalem ofer fyftyne furlang;",
    "19": "Manega þara iudea comon to martham & to marían þt hig woldon hi frefrian for hyra broðor þingon;",
    "20": "Ða martha gehyrde þt se hælend cóm. þa arn heo ongean hyne. & maría sæt æt ham;",
    "21": "Ða cwæð martha to þam hælende; Drihten. gif þu wære her nære min broðor dead.",
    "22": "& ec ic wat nu þa þt god þe sylð swa hwæt swa ðu hyne bitst;",
    "23": "Ða cwæð se hælend to hyre þin broðor arist;",
    "24": "& martha cwæþ to him. ic wat þt he arist on þam ytemestan dæge;",
    "25": "& se hælend cwæð to hyre. ic eom æryst & líf se ðe ge-lyfð on me þeah he dead sy he leofað.",
    "26": "& ne swylt nan þara þe leofað & gelyfð on me; Gelyfst þu þyses.",
    "27": "heo cwæð to him. witodlice drihten ic gelyfe þt þu eart crist godes sunu þe on middan-eard cóme;",
    "28": "& þa heo ðas þing sæde. heo eode & clypode diglice marian hyre swustor þus cweþende. her is ure lareow & clypað þe;",
    "29": "Ða heo þt gehyrde heo arás raðe & com to him.",
    "30": "þa gyt ne com se hælend binnan þa ceastre ac wæs ða gyt on ðære stowe þar martha him ongean com;",
    "31": "Þa iudeas þe wæron mid hyre on huse & hi frefrodon þa hig gesawon þt maría arás & mid ofste ut-eodon hig fyligdon hyre ðus cweþende; Heo gæð to his byrgenne þt heo wepe þara;",
    "32": "Ða maría com þar se hæle[n]d wæs & heo hine geseah heo feoll to his fotum & cwæð to him; Drihten. gif ðu wære her nære min broðor dead;",
    "33": "Ða se hælend geseah þt heo weop & þt þa iudeas weopon þe mid hyre cómon. he geomrode on hys gaste & gedrefde hyne sylfne",
    "34": "& cwæð hwar lede ge hine; Hig cwædon to him. drihten ga & geseoh.",
    "35": "& se hælend weop",
    "36": "& þa iudeas cwædon loca nu hu he hyne lufode;",
    "37": "Sume hi cwædon. ne mihte ðes þe ontynde blindes eagan. don eac þt þes nære dead;",
    "38": "Eft se hælend geomrode on him sylfum & com to þære byrgenne hit wæs án scræf & þar wæs an stán on-uppan geled;",
    "39": "And se hælend cwæð doð aweg þone stan; Ða cwæð martha to him þæs swustor þe þar dead wæs; Drihten nu he stingð (sic) he wæs for feowur dagon dead;",
    "40": "Se hælend cwæð to hyre. ne sæde ic ðe þt þu gesyhst godes wuldor gif ðu gelyfst.",
    "41": "þa dydon hig aweg þone stan; Se hælend ahof upp his eagan & cwæð. fæder ic do þe þancas forþam þu gehyrdest [me];",
    "42": "Ic wat þt þu me symle gehyrst ac ic cwæð for þam folce þe her ymbutan stent þt hig gelyfon þt þu me asendest;",
    "43": "Ða he ðas þing sæde. he clypode mycelre stefne. Lazarus gá út",
    "44": "& sona stop forð se ðe dead wæs gebunden handan & fotan & hys nebb wæs mid swat-line gebunden; Ða cwæð se hælend to him unbindað hine & lætað gán.",
    "45": "manega þara iudea þe comon to marían & gesawon ða þing þe he dyde gelyfdon on hine;",
    "46": "Hi sume foron to þam phariseon & sædon him þa ðing þe se hælend dyde;",
    "47": "Witodlice þa bisceopas & þa pharisei gaderydon gemot & cwædun; Hwæt do we. forþam þes man wyrcð mycel tacn.",
    "48": "gif we hine forlætaþ ealle gelyfað on hine; & romane cumað & nimað ure land & urne þeod-scipe;",
    "49": "Hyra an wæs genemned caiphas se wæs ða on gere bisceop & cwæð to him. ge nyton nan þing",
    "50": "ne ne geþenceað þt us ys betere þt an man swelte for folce & eall þeod ne forwurðe;",
    "51": "Ne cwæð he þt of him sylfum. ac þa he wæs þt ger bisceop he witgode þt se hælend sceolde sweltan for ðære þeode.",
    "52": "& na synderlice for þære ðeode ac þt he wolde gesomnian togædere godes bearn þe todrifene wæron.",
    "53": "Of þam dæge hig þohton þt hi woldon hyne ofslean",
    "54": "þa ne for se hælend na openlice gemang ðam iudeon. ac for on þt land wið þt westen on þa burh þe ys ge-nemned effrem. & wunode þær myd his leorning-cnihton;",
    "55": "Iudea eastron wæron gehende & manega foron of ðam lande to ierusalem ær þam eastron þt hig woldon hig sylfe gehalgian.",
    "56": "hig sohton þone hælend & spræcon him betwynan ðær hig stodon on ðam temple & þus cwædon; Hwæt wene ge. þt he ne cume to freols-dæge.",
    "57": "þa bisceopas & þa pharisei hæfdon be-boden gif hwa wiste hwar he wære þt he hyt cydde þt hig mihton hine niman;"},

"12": {

    "1": "Se hælend com syx dagon ær þam eastron to bethanía þar lazarus wæs dead þe se hælend awrehte;",
    "2": "Hig wrohton him þær beor-scipe. & marða þenode; Ladzarus wæs an þæra þe mid him sæt.",
    "3": "maría nam án pund deorwyrðre sealfe mid þam wyrt-gemange þe hig nardus hatað. & smyrede ðæs hælendes fét & drigde mid hyre loccon. & þt hus wæs gefylled of ðære sealfe swæcce;",
    "4": "þa cwæð an his leorning-cnihta iudas scarioð þe hine belæwde;",
    "5": "Hwi ne sealde heo þas sealfe wiþ þrim hundred penegon þt man mihte syllan þearfon;",
    "6": "Ne cwæð he na þt forþig þe him gebyrode to þam þearfon. ac forþam þe he wæs þéof & hæfde scrin & bær þa ðing þe man sende;",
    "7": "Ða cwæð se hælend. læt hig þt heo healde þá of þæne dæg þe man me bebyrge;",
    "8": "Ge habbað symle þearfan mid eow. ac ge nabbað me symle;",
    "9": "Micel menio þara iudea gecneow þt he wæs ðær. & hig comon næs na for þæs hælendes þingon syndorlice ac þt hig woldon geseon ladzarum þe he awehte of deaðe;",
    "10": "Ðara sacerda ealdras þohton þt hig woldon lazarum ofslean",
    "11": "forþam þe manega foron fram þam iudeon for his þingon & gelyfdon on þone hælend;",
    "12": "On mergen mycel menio þe com to þam freols-dæge. þa hig gehyrdon þt se hælend com to ierusalem",
    "13": "hi namon palm-trywa twígu & eodon út ongean hine & clypedon; Si israhela cing hal & gebletsod þe com on drihtnes naman;",
    "14": "& se hælend gemette anne assan & rad on-uppan þam swa hit awriten ys.",
    "15": "ne ondræd þu siones dohtor nu þin cing cymþ uppan assan folan sittende;",
    "16": "Ne undergeton hys leorning-cnihtas þas þing ærest. ac þa se hælend wæs gewuldrod. þa gemundon hig þt þas þing wæron awritene be him. & þas þing hig dydon him;",
    "17": "Seo menio þe wæs mid him þa he ladzarum clypode of ðære byrgene & hine awehte of deaðe cyðde gewitnesse.",
    "18": "& forði him com seo menio ongean forðam þe hi gehyrdon þt he worhte þt tacn.",
    "19": "Ða pharisei cwædon bet[w]ux him sylfon. we geseoð þt we nan þing ne frémiað. nu wyle eall middan-eard æfter him;",
    "20": "Sume ðæge wæron hæðene þe foron þt hig woldon hi gebiddan on ðam freols-dæge;",
    "21": "Ða genealæhton to philippe se wæs of þære galileiscean bethsaida & hi bædon hine & cwædon leof we wyllað geseon þone hælend;",
    "22": "Ða eode philippus & sæde hit andree. & eft andreas & philippus hit sædon þam hælende;",
    "23": "Se hælend him & swarode & cwæð.seo tid cymð þt mannes sunu byð geswutelod:",
    "24": "Soðlice ic secge eow þt hwætene corn wunað ana buton hyt fealle on eorþan & sy dead; Gif hit [byð] dead hit bringð mycelne wæstm;",
    "25": "Se þe lufað his sáwle forspilþ hig. & se þe hataþ his sawle on þison middan-earde gehylt hi on éceon life;",
"26": "Gif hwa þenige me fylige me. & min þen bið þær þær ic eom; Gif me hwa þenað min fæder hine wurðað;",
"27": "Nu min sawl ys gedrefed & hwæt secge ic; fæder. gehæl me of ðisse tide. ac for ðam ic com on þas tíd;",
"28": "Fæder gewuldra þinne naman; Ða com stefn of heofone þus cweðende. & ic gewuldrode & eft ic gewuldrige;",
"29": "Seo menio þe þær stod & þt gehyrde sædon þt hyt þunrode. sume sædon þt engel spæce wið hyne;",
"30": "Se hælend him &swarode & cwæð. ne com þeos stef[en] for minon þingon ac for eowrum þingon;",
"31": "Nu ys middan-eardes dom nu byð ðyses middan-eardes ealdor út-aworpen.",
"32": "& gif ic beo úpp-ahafen fram eorðan. ic teo ealle þing to me sylfon;",
"33": "Ðæt he sæde & tacnode hwylcum deaðe he wolde sweltan;",
"34": "Seo menio him &swarode & cwæð. we gehyrdon on þore (sic) .æ. þt crist bið on ecnysse. & humeta segest þu hit gebyrað þt mannes sunu beo úpp-ahafen. hwæt ys þes mannes sunu.",
"35": "þa cwæð se hælend; Nu gyt ys lytel leoht on eow. gaþ þa hwile þe ge leoht habbað. þt þystro eow ne befon; Se þe gæð on þystro he nat hwyder he gæð.",
"36": "þa hwile þe ge leoht habbon gelyfað on leoht þt ge syn leohtes bearn; Ðas þing se hælend him sæde. & eode & bediglode hine fram him;",
"37": "Ða he swa mycele tacn dyde beforan him. hí. ne gelyfdon on hyne.",
"38": "þt ðæs witegan word ysaías wære gefylled þe he cwæð; Drihten. hwa gelyfde þæs þe we gehyrdon. & hwam wæs drihtnes stréncð geswutelod.",
"39": "forþi hi ne mihton gelyfan forþam ysaías cwæþ eft",
"40": "he ablende hyra eagan. & ahyrde hyra heortan þt hi ne geseon mid hyra æagon & mid hyra heortan ne ongyton. & syn gecyrrede & ic hig gehæle;",
"41": "Ysaias sæde ðas þing þa he geseah hys wuldor & spræc be him.",
"42": "& þeah manega of ðam ealdron gelyfdon on hyne; Ac hi hit ne cyddon for þæra pharisea þingon þe-læs hig ma[n] út-adrife of hyra gesomnunge;",
"43": "Hi lufodon manna wuldor swiðor þonne godes wuldor.",
"44": "Se hælend clypode & cwæð to him; Se þe gelyfð on me ne gelyfþ he na on me. ac on þæne þe me sende.",
"45": "& se ðe me gesyhþ gesyhð þæne þe me sende;",
"46": "Ic com to leohte on middan-eard. & nan ðara þe gelyfð on me ne wunað on þystron.",
"47": "& gif hwa gehyrð mine word & ne gehylt. ne deme ic hine; Ne com ic middan-eard to demanne ac þt ic gehæle middan-eard;",
"48": "Se þe me for-higð & mine wórd ne under-fehð. he hæfþ hwa him deme; Seo spæc þe ic spæc seo him demð on þam ytemestan dæge",
"49": "forþam þe ic ne spece of me sylfon ac se fæder þe me sende he me bebead hwæt ic cweþe & hwæt ic spece.",
"50": "& ic wat þt his bebod ys éce líf. þa þing þe ic sprece. ic sprece swa fæder me sæde;"},

"13": {

    "1": "Ær þam esterfreols-dæge se hælend wiste þt his tíd com þt he wolde gewítan of þyson middan-earde to his fæder þa he lufode his leorning-cnihtas þe wæron on middan-earde an (sic) ende he hig lufode;",
    "2": "& þa drihtnes þenung wæs gemacud þa for se deofol on iudas heortan scariothes þt he hine belæwde;",
    "3": "He wiste þt fæder sealde ealle þing on his handa & þt he com of gode & cymð to gode.",
    "4": "he aras fram his þenunge & lede his reaf & nam linen hrægel & begyrde hyne.",
    "5": "æfter þam he dyde wæter on fæt & þwoh his leorning-cnihta fet & drigde hig mid þære lin-wæde þe he wæs mid begyrd;",
    "6": "Ða com he to simone petre. & petrus cwæð to him; Drihten scealt þu ðwean mine fet.",
    "7": "se hælend &swarode & cwæð to him. þu nast nu þt ic do ac þu wast syððan;",
    "8": "Petrus cwæð to him. ne þwyhst þu næfre mine fét; Se hælend him &swarode & cwæþ. gif ic þe ne þwea næfst þu nanne dæl myd me;",
    "9": "Ða cwæð símón petrus to him; Drihten. ne þweh þu na mine fet áne. ac ec min heafod & mine handa;",
    "10": "Ða cwæð se hælend to him. Se þe clæne byþ ne beðearf buton [þt] man his fet þwea ac ys eall clæne; & ge synt sume clæne næs na ealle.",
    "11": "he wiste witodlice hwa hyne sceolde belæwan. forþam he cwæð. ne synt ge ealle clæne;",
    "12": "Syððan he hæfde hyra fét aþwogene. he nam his reaf & þa he sæt he cwæð eft to him. wite ge hwæt ic eow dyde;",
    "13": "Ge clypiað me lareow & drihten. & wel ge cweðaþ. swa ic eom soþlice.",
    "14": "Gif ic þwoh eowre fét. [ic þe eom eower lareow. & eower hlaford. ge sceolon þwean eower ælc oðres fet;]",
    "15": "ic eow sealde bysene þt ge don swa ic eow dyde;",
    "16": "Soþlice ic eow secge nys se ðeowa furðra þonne his hlaford. ne ærenddraca nys mærra þonne se þe hyne sende.",
    "17": "Gif ge þas þing witod (sic) ge beoð eadige. gif ge hig doð;",
    "18": "Ne secge ic be eow eallon. ic wat hwylce ic geceas ac þt þt halige gewrit sy gefylled þe cwyþ; Se þe ytt hlaf myd me ahefþ hys hó ongean me.",
    "19": "nu ic eow secge ærþam þe hyt gewurþe þt ge gelyfon þonne hyt geworden bið þt ic hit eom;",
    "20": "Soð ic eow secge se ðe under-fehð þæne þe ic sende. under-fehþ me. Se þe under-fehþ me under-fehþ ðæne ðe me sende;",
    "21": "Ða se hælend þas þing sæde he wæs gedrefed on gaste & cyðde & cwæð. Soð ic eow secge þt eower án me belæwð;",
    "22": "Ða leorning-cnihtas beheold hyra ælc oðerne & him twynode be hwam he hit sæde;",
    "23": "An þæra leorni[n]g-cnihta hlinode on þæs hælendes bearme þæne se hælend lufode;",
    "24": "Symon petrus bicnode to þyson & cwæð to him; Hwæt is se ðe he hyt big segð.",
    "25": "Witodlice þa he hlinode ofer ðæs hælendes breostum he cwæð to him; Drihten hwæt ys he.",
    "26": "Se hælend him &swarode & cwæð. He ys se ðe ic ræce bedyppedne hlaf; & þa þa he bedypte þæne hlaf he sealde hyne iudas scarióthe;",
    "27": "& þa æfter þam bitan satanas eode on hyne; Ða cwæð se hælend to him. do raðe þt þu don wylt.",
    "28": "nyste nan þara sittendra to hwam he þt sæde;",
    "29": "Sume wendon forþam iudas hæfde scrin þt se hælend hit cwæde be him. bige þa þing þe us þearf sy to þam freols-dæge oððe þt he sealde sum þing þearfendum mannum;",
    "30": "Ða he nam þæne bitan. he eode út þar-rihte hit wæs niht",
    "31": "þa he ut eode. & se hælend cwæð. nu ys mannes sunu geswutelod. & god ys geswutelod on him;",
    "32": "Gif god ys geswutelod on him & god geswutelað hine on hym sylfum;",
    "33": "La bearn nu gyt ic eom gehwæde tid mid eow. ge me seceað & swa ic þam iudeon sæde ge ne magon faran þyder þe ic fare; & nu ic eow secge",
    "34": "ic eow sylle niwe bebod. þt ge lufion eow betwynan swa ic eow lufode;",
    "35": "Be þam oncnawað ealle menn þt ge synt mine leorning-cnihtas. gif ge habbað lufe eow betwynan;",
    "36": "Simon petrus cwæð to him drihten. hwyder gæst þu; Se hælend him &swarode & cwæð. ne miht þu me fylian þyder ic nu fare. þu færst eft æfter me;",
    "37": "Petrus cwæð to him. hwi ne mæg ic þe nu fylian. ic sylle min líf for ðe;",
    "38": "Se hælend him &swarode & cwæð. ðin lif þu sylst for me; Soð ic þe secge. ne cræwð se cocc ær ðu wið-sæcst me þriwa"},

"14": {

    "1": "& he cwæð to his leorning-cnihton; Ne sy eower heorte gedrefed ge gelyfað on god. & gelyfað on me;",
    "2": "On mines fæder huse synt manega eardung-stowa ne sæde ic eow. hyt ys lytles wana þt ic fare & wylle eow eardung-stowe gearwian;",
    "3": "& gif ic fare & eow eardung-stowe ge-gearwige; Eft ic cume & nime eow to me sylfon þt ge syn þær ic eom;",
    "4": "& ge witon hwyder ic fare & ge cunnon þæne weg.",
    "5": "Thomas cwæð to him. Drihten. we nyton hwyder þu færst & hu mage we þæne weg cunnan;",
    "6": "Se hælend cwæð to him. ic eom weg & soðfæstnys & líf. ne cymþ nan to fæder butan þurh me;",
    "7": "Gif ge cuðon me. witodlice ge cuðon minne fæder & heonon-forð ge hyne gecnawað & ge hine gesawon;",
    "8": "Philippus cwæð to him. Drihten. æt-yw us þone fæder. & we habbaþ genoh.",
    "9": "Se hælend cwæð to him. philippus swa lange tid ic wæs mid eow & ge ne gecneowun me; Se þe mé gesyhð. gesyhð minne fæder; Humeta cwyst þu æt-ýw ús þinne fæder",
    "10": "ne gelyf[s]t þu þt ic eom on fæder & fæder ys on me; Ða word þe ic to eow sprece. ne sprece ic hi of me sylfon; Se fæder þe wunað on me. he wyrcð þa weorc.",
    "11": "ne gelyfe ge þt ic eom on fæder & fæder ys on me. gelyfað for þam weorcon;",
    "12": "Soð ic eow secge. se ðe gelyfð on me he wyrcð þa weorc þe ic wyrce & he wyrcð maran þonne þæge synt forþam þe ic fare to fæder.",
    "13": "& ic do swa hwæt swa ge biddað on minon naman þt fæder si gewuldrod on suna",
    "14": "gif ge hwæt me biddaþ on minum naman þt ic do;",
    "15": "Gif ge me lufiað. healdað mine beboda",
    "16": "& ic bidde fæder & he sylþ eow oðerne frefriend þt beo æfre mid eow;",
    "17": "Soðfæstnysse gast þe ðes middan-eard ne mæg under-fon; He ne cann hyne forðam þe he ne gesyhþ hyne; Ge hyne cunnon forþam he wunað mid eow. & bið on eow;",
    "18": "Ne læte ic eow steopcild. ic cume to eow;",
    "19": "nu gyt ys an lytel fyrst & middan-eard me ne gesyhþ; Ge me geseoð forþam ic lybbe & ge lybbað;",
    "20": "On þam dæge ge ge-cnawaþ þt ic eom on minum fæder & ge synt on me & ic eom on eow;",
    "21": "Se þe hæfð mine bebodu & ge-hylt þa. he ys þe me lufað; Min fæder lufað þæne þe me lufað & ic lufige hyne & geswutelige him me sylfne;",
    "22": "Iudas cwæð to him næs na sé scarioth. drihten hwæt ys geworden þt þu wylt þe sylfne ge-swuteligan us næs middanearde;",
    "23": "Se hælend &swarode & cwæð to him; Gif hwa me lufað he hylt mine spræce. & min fæder lufað hine & we cumað to him & we wyrceað eardung-stowa mid him;",
    "24": "Se ðe me ne lufað ne hylt he mine spræce. & nis hyt min spræc þe ge gehyrdon. ac ðæs fæder þe me sende;",
    "25": "Ðas þing ic eow sæde þa ic mid eow wunode;",
    "26": "Se haliga frofre gast þe fæder sent on minum naman eow lærð ealle þing. & he lærð eow ealle þa þing þe ic eow secge;",
    "27": "Ic læfe eow sibbe. ic sylle eow mine sibbe. Ne sylle ic eow sibbe swa middan-eard sylþ; Ne sy eower heorte gedrefed ne ne forhtige [ge].",
    "28": "Ge gehyrdon þt ic eow sæde. ic gá & ic cume to eow; Witodlice gif ge me lúfedon ge geblissodon. for-þam þe ic fare to fæder forþam fæder ys mara þonne ic;",
    "29": "& nu ic eow sæde ærðam þe hit ge-wurðe þt ge gelyfon þonne hit geworden bið;",
    "30": "Ne sprece ic nu na fela wið eow; Ðyses middan-eardes ealdor cymð & he næfð nan ðing on me;",
    "31": "Ac þt middan-eard oncnawe þt ic lufige fæder. & ic do swa fæder me bebead; Arisað uton gan heonon;"},

"15": {

    "1": "[I]c eom soð wín-eard. & min fæder ys eorð-tilia;",
    "2": "He deð ælc twig aweg on me þe blæda ne byrð; & he feormað ælc þara þe blæda byrþ þt hyt bere blæda ðe swiðor.",
    "3": "Nu ge synt clæne for þære spræce þe ic to eow spræc.",
    "4": "wuniað on me & ic on eow; Swa twig ne mæg blæda beran him-sylf. buton hit wunige on win-earde. swa ge ne magon eác buton ge wunion on me;",
    "5": "Ic eom wín-eard & ge synt twigu; Se ðe wunað on me & ic on him. se byrð mycle blæda. forðam ge ne magon nan ðing don butan me;",
    "6": "Gif hwa ne wunað on me. he byð aworpen út swa twig & for-druwað; & hig gaderiað þa & doð on fýr. & hig for-byrnaÐ;",
    "7": "Gyf ge wuniað on me & mine word wuniað on eow. biddað swa hwæt swa ge wyllon & hyt byð eower;",
    "8": "On ðam ys min fæder geswutelod þt ge beron mycle blæda & beon mine leorning-cnihtas;",
    "9": "& ic lufode eow swa fæder lufode me. wuniað on minre lufe;",
    "10": "Gif ge mine bebodu gehealdað ge wuniað on minre lufe; Swa ic geheold mines fæder bebodu. & ic wunige on hys lufe.",
    "11": "Ðas þing ic eow sæde þt min gefea sy on eow & eower gefea sy gefulled.",
    "12": "Ðis ys min bebod. þt ge lufion eow gemænelice swa ic eow lufode;",
    "13": "Næfð nán man maran lufe þonne ðeos ys. þt hwá sylle his líf for his freondum;",
    "14": "Ge synt mine frynd gif ge doð þa þing þe ic eow bebeode;",
    "15": "Ne telle ic eow to ðeowan. forþam se ðeowa nat hwæt se hlafor[d] deð; Ic tealde eow to freondum. forþam ic cyðde eow ealle þa þing þe ic gehyrde æt minum fæder;",
    "16": "Ne gecure ge me ac ic geceas eow; & ic sette eow þt ge gan & blæda beron & eowre blæda gelæston. þt fæder sylle eow swa hwæt swa ge biddað on minum naman;",
    "17": "Ðas þing ic eow beode þæt ge lufion eow gemænelice;",
    "18": "Gif middan-eard eow hatað witað þt he hatede me ær eow;",
    "19": "Gif ge of middan-earde wæron. middan-eard lufode þt his wæs; Forþam þe ge ne synt of middan-earde. ac ic eow geceas of middan-earde. forði middan-eard eow hatað;",
    "20": "Gemunað minre spræce þe ic eow sæde. Nis se ðeowa mærra þonne his hlaford; Gif hi me ahton (sic). hi wyllað ehtan eower; Gif hi mine spræce heoldon hi healdað eac eowre;",
    "21": "Ac ealle þas þing hi doð eow for minum naman. forþam hi ne cunnon þæne þe me sende;",
    "22": "Gif ic ne come & to him ne spræce næfdon hig nane synne; Nu hi nabbað nane lade be hyra synne;",
    "23": "Se þe me hatað hatað minne fæder;",
    "24": "Gif ic náne weorc ne worhte on him þe nan oðer ne worhte næfdon hi nane synne; Nu hi gesawon & hi hatedon ægðer ge mé ge minne fæder;",
    "25": "Ac þt seo spræc sy gefylled þe on hyra .æ. awriten ys þt hi hatedon me buton gewyrhton;",
    "26": "Ðonne se frefriend cymð þe ic eow sende fram fæder soðfæstnysse gast þe cymð fram fæder. he cyð gewitnesse be me.",
    "27": "& ge cyðað gewitnesse forðam ge wæron fram fruman mid mé;"},

"16": {

    "1": "Ðas ðing ic eow sæde þt ge ne swicion.",
    "2": "hi doð eow of gesomnungum; Ac seo tid cymð þt ælc þe eow of-slyhð wenþ þt he þenige gode.",
    "3": "& þas ðing hig doð forþam þe hi ne cuþon minne fæder ne me;",
    "4": "Ac þas þing ic eow sæde þt ge gemunon þonne hyra tid cymð þt ic hit eow sæde; Ne sæde ic eow þas ðing æt fruman forþam þe ic wæs mid eow;",
    "5": "Nu ic fare to ðam þe me sende & eower nan ne ahsað me hwyder ic fare;",
    "6": "Ac forþam þe ic spræc ðas þing to eow unrotnyss gefylde eowre heortan;",
    "7": "Ac ic [eow] secge soðfæstnysse. eow fremað þt ic fare; Gif ic ne fare. ne cymð se frefriend to eow; Witodlice gif ic fare. ic hyne sende to eow.",
    "8": "& þonne he cymð he þywþ þysne middan-eard be synne. & be rihtwisnysse & be dome;",
    "9": "Be synne forþam hi ne gelyfdon on me.",
    "10": "be rihtwisnysse forþam ic fare to fæder & ge me ne geseoð;",
    "11": "Be dóme. forþam þyses middan-eardes ealdur ys gedemed;",
    "12": "Gyt ic hæbbe eow fela to secgenne ac ge hyt ne magun nú acuman;",
    "13": "Ðonne þære soþfæstnysse gast cymð. he lærð eow ealle soþfæstnysse; Ne sprycð he of him sylfon. ac he sprycð þa þing þe he gehyrð. & cyð eow ða þing þe towearde synt.",
    "14": "he me geswutelað for-þam he nimð of mínum & cyð eow;",
    "15": "Ealle þa þing þe min fæder hæfð synt míne. forþig ic cwæð þt he nimð of minum & cyþ eow;",
    "16": "Nu ymbe alytel ge me ne geseoð. & eft embe lytel ge me geseoþ forþam þe ic fare to fæder;",
    "17": "Ða cwædon his leorning-cnihtas him betwynan. hwæt ys þt he us segð. ymbe lytel ge me ne geseoð. & eft embe lytel & ge me geseoð & þt ic fare to fæder;",
    "18": "Hig cwædon witodlice hwæt ys þt he cwyþ embe lytel we nytan hwæt he sprycð;",
    "19": "Se hælend wiste þt hi woldon hyne ahsian. & he cwæð to him. be þam ge smeageað betwynan eow forþam ic sæde. embe lytel ge me ne geseoð. & eft embe lytel ge me geseoð;",
    "20": "Soð ic eow secge þt ge heofiað & wepað; Middan-eard geblissað. & ge beoð unrote. ac eower unrotnys byð gewend to gefean;",
    "21": "Ðænne wíf cenð. heo hæfð unrotnysse forþam þe hyre tid com. þonne heo cenð cnapan ne geman heo þære hefinysse for geféan forþam mann byð acenned on middan-eard.",
    "22": "& witodlice ge habbað nu unrotnysse; Eft ic eow geseo & eower heorte geblissað. & nan man ne nimþ eowerne gefean fram eow;",
    "23": "& on þam dæge ge ne biddað me nanes þinges; Soð ic eow secge gif ge hwæt biddað minne fæder on minum naman he hyt sylþ eow;",
    "24": "Oþ þis ne bæde ge nán þing on minum naman; Biddað. & ge underfoð þt eower gefea sy full;",
    "25": "Ðas þing ic eow sæde on big-spellum. Seo tid cymð. þænne ic eow ne sprece on big-spellum ac ic cyðe eow openlice be minum fæder;",
    "26": "On ðam dæge ge biddað on minum naman. & ic eow ne secge forþam ic bidde minne fæder be eow;",
    "27": "Witodlice se fæder eow lufað forþam þe ge lufedon me & gelyfdon þt ic com of gode.",
    "28": "ic for fram fæder. & com on middan-eard; Eft ic for-læte middan-eard & fare to fæder;",
    "29": "His leorning-cnihtas cwædon to him. nu ðu sprycst openlice. & ne segst nan big-spell;",
    "30": "Nu we witon þt þu wast ealle ðing. & þe nis nan þearf þt ænig þe axie; On ðyson we gelyfað þt þu come of gode;",
    "31": "Se hælend him &swarode. & cwæð; Nu ge gelyfað.",
    "32": "nu cóm tíd & cymð þt ge tofaron æg-hwylc to his agenon & for-læton mé anne & ic ne eom ána forþam min fæder is mid me;",
    "33": "Ðas þing ic eow sæde þt ge habbon sibbe on me; Ge habbað hefige byrðene on middan-earde. ac getruwiað. ic forswiðde middan-eard;"},

"17": {

    "1": "Ðas þing se hælend spræc. & ahof úpp his eagan to heofenum & cwæð; Fæder tíd ys cumen geswutela þinne sunu þt þin sunu geswutelige þe.",
    "2": "& swa þu him sealdest anweald ælces mannes þt he sylle éce lif eallum þam þe þu him sealdest;",
    "3": "Ðis ys soðlice éce líf þt hi oncnawon þt þu eart án soþ god. & se ðe þu sendest hælynde crist;",
    "4": "Ic þe geswutelode ofer eorþan; ic ge-endode þt weorc þt þu me sealdest to donne;",
    "5": "& nu ðu fæder gebeorhta me mid þe sylfon ðære beorhtnysse þe ic hæfde myd þe ærðam þe middan-eard wære;",
    "6": "Ic geswutolode þinne naman þam mannon þe ðu me sealdest of middan-earde; Hig wæron þíne & þu hy sealdest me. & hi geheoldon þine spræce;",
    "7": "Nu hi gecneowon þt ealle þa þing þe þu me sealdest synd of ðé.",
    "8": "forþam ic sealde him þa word ðe ðu sealdest mé; & hig under-fengon & oncneowon soðlice þt ic eom of þe. & hig gelyfdon þt þu me sendest;",
    "9": "Ic bidde for hig. ne bidde ic for middan-earde. ac for þa þe ðu me sealdest. forþam hi synt þíne.",
    "10": "& ealle mine synt þine & þíne synt mine. & ic eom geswutelod on him;",
    "11": "& nu ic ne cóm on middan-earde. & hi synt on middan-earde & ic cume to Ðe. On ðære tide se hælend beheold his leorning-cnihtas & cwæð; Haliga fæder heald on ðinum naman þt þu me sealdest þt hi syn án. swa wyt synt",
    "12": "þa ic wæs mid him ic heold hi on þinum naman. ic heold þa þe þu me sealdest. & ne for-wearð hyra nán buton forspillydnysse bearn. þt þt halige gewrit sy ge-fylled;",
    "13": "Nu ic cume to þe & ðas þing ic sprece on middan-earde þt hi habbon minne gefean gefyllydne on him sylfon;",
    "14": "Ic sealde him þine spræce. & middan-eard hi hæfde on hatunge. forþam hi ne synt of middan-earde. swa ic eac ne eom of middan-earde;",
    "15": "Ne bidde ic þt þu hi nyme of middan-earde. ac þt þu hi gehealde of yfele;",
    "16": "Ne synt hi of middan-earde swa ic ne eom of middan-earde;",
    "17": "Ge-halga him soþfæstnysse. þin spræc ys soðfæstnyss;",
    "18": "Swa þu me sendest on middan-eard. ic sende hi on middan-eard.",
    "19": "& for hig ic halgige me sylfne þt hig syn eac gehalgode on soðfæstnysse;",
    "20": "Witodlice ne gebidde ic for hi áne ac éac for ða þe gyt sceolon gelyfan. þurh hyra word on me.",
    "21": "þt ealle sýn án. swa þu fæder eart on me. & ic eom on ðe þt hig syn eác án on unc þt middan-eard gelyfe þt þu me sendest;",
    "22": "& ic sealde him þa beorhtnysse þe ðu me sealdest þt hi syn án swa wyt syn án;",
    "23": "Ic eom on him & þu eart on me þt hi syn ge-endode on án. þt middan-eard on-cnawe þt þu me sendest & lufodest [hig. swa þu me lufodest.]",
    "24": "Fæder. ic wylle þt þa þe þu me sealdest syn mid me þar ic eom. þt hig geseon mine beorht-nysse þe þu me sealdest forþam þu lufodest me. ær middan-eard gesett wæs;",
    "25": "La riht-wísa fæder middan-eard þe ne gecneow. witodlice ic ðe gecneow & hi oncneowon þt þu me sendyst.",
    "26": "& ic him cyðde ðinne naman & gyt wylle cyþan þt seo lufu ðe þu me lufodest sy on him & ic eom on him."},

"18": {

    "1": "Þa se hælend þas þing cwæð þa eode he ofer ða burnan cedron ðær wæs án wyrtun. in-to þam he eode & his leorning-cnihtas;",
    "2": "Witodlice iudas þe hyne belæwde wiste þa stowe forþam þe se hælend oft-rædlice com ðyder mid his leorning-cnihton.",
    "3": "Þa under-feng iudas þt folc & þa þegnas æt þam bisceopum. & æt ðam phariseon. & cóm þyder mid leoht-fatum. & mid blasum. & mid wæpnum;",
    "4": "Witodlice se hælend wiste ealle þa þing þe him towearde wæron; He eode ða forð & cwæð to him. hwæne sece ge;",
    "5": "Hig &swaredon him & cwædon ðone nazareniscean hælend; Se hælend cwæð. ic hit éom. soðlice iudas þe hine belæwde stod mid him.",
    "6": "ða he openlice sæde ic hit eom; Ða eodon hig underbæc & feollon on ða eorþan;",
    "7": "Eft he hi axode. hwæne sece ge. hi cwædon. þone nazareniscean hælend;",
    "8": "Se hælend him &swarode. ic sæde eow þt ic hit eom; Gif ge witodlice mé seceað. lætað þas faran",
    "9": "þt seo spræc wære gefylled þe he cwæð. þt ic nanne þæra ne for-spille þe ðu me sealdest;",
    "10": "Witodlice simón Petrus ateah his swurd. & sloh ðæs bisceopes þeowan. & acerf him of þt swyðre eare. þæs þeowan nama wæs malchus;",
    "11": "Ða cwæð se hælend to petre dó þin swurd on scæaðe. þone calic þe min fæder me sealde ne drince ic hine;",
    "12": "Ðæt folc & se ealdor & þæra iudea ðegnas namon ðæne hælend & bundon hine.",
    "13": "& læddon hine ærest to annan. se wæs caiphas sweor. & se caiphas wæs ðæs geares bisceop;",
    "14": "Witodlice kaiphas dihte ðam iudéon. & cwæð þt hyt wære betere þt an man swulte for folc;",
    "15": "Simon petrus fylide þam hælende & oðer leorning-cniht; Se oðer leorning-cniht wæs ðam bisceope cuð. & he eode inn mid þam hælende on ðæs bisceopes cauer-tun;",
    "16": "Petrus stod æt ðære dura þær-úte. þa eode se leorning-cniht út þe wæs ðæs bisceopes cuða & cwæð to ðære dure-þinene. & lædde petrum inn;",
    "17": "Ða cwæð seo duru-ðinen to petre. cwyst ðu. eart ðu of ðyses leorning-cnihtum; Ða cwæð he. nicc ne eom ic;",
    "18": "Ða þeowas & ða þegnas stodon æt ðam glédon & wyrmdon hig forþam hit was ceald; Witodlice petrus stod mid him & wyrmde hyne;",
    "19": "Se bisceop axode þone hælend embe his leorning-cnihtas & embe his láre;",
    "20": "Ða &swarode se hælend & cwæð; Ic sprece openlice to middan-earde & ic lærde symble on gesomnunge. & on temple þar ealle iudeas togædere comon. & ic ne spæc nan þing digelice.",
    "21": "Hwi axast ðu me. axa þa þe gehyrdon hwæt ic to him spræce. hi witon þa ðing þe ic him sæde;",
    "22": "Ða he þis cwæð. þa sloh án ðæra þena þe ðar stodon ðæne hælend mid his handa & cwæð; &swarast ðú swa ðam bisceope;",
    "23": "Se hælend &swarode him & cwæð; Gif ic yfele spræce cyð gewittnysse be yfele. gif ic wel spræce hwi beatst þu me;",
    "24": "Ða sende annas hine to þam bisceope gebundene",
    "25": "& symón petrus stod & wyrmde hyne; Ða cwædon hi to him. cwyst þu. eart þu of his leorning-cnihton; He wið-sóc & cwæð ic ne eom;",
    "26": "Ða cwæð an ðæs bisceopes þeowena hys cuða þæs eare sloh petrus óf; Hu ne geseah ic ðe on ðam wyrtune mid hym;",
    "27": "petrus þa eft wið-soc. & sona se cocc creow;",
    "28": "Ða gelæddon hi þone hælend to caiphán on þt domern. hit wæs þa morgen. & hig sylue ne eodon into ðam domerne þt hyg næron besmitene. ac þt hi æton hyra eastron;",
    "29": "Þa eode pilatus ut to him & cwæð. hwylce wrohte bringe ge ongean þysne man.",
    "30": "hig &swaredon & cwædon to him; Gif he nære yfeldæde. ne sealde we hine ðe;",
    "31": "þa cwæð pilatus to him; Nimað hine & demað him be eowre .æ. Ða cwædon þa iudeas to him. us nis na alyfed þt we ænine mann ofslean",
    "32": "þt þæs hælendes spræc wære gefylled þe he cwæð þa he geswutelode. hwylcon deaðe he swulte;",
    "33": "Ða eode pilatus eft into þam domerne. & clypode ðæne hælend & cwæð to him; Eart ðu iudea cining;",
    "34": "Ða &swarode se hælend him & cwæð; Cwyst þu þis of ðe sylfum. hwæðer ðe hyt þe oðre sædon;",
    "35": "Pilátus him &swarode & cwæð; Cwyst þu. eom ic iudeisc. þín þeod & þine bisceopas ðe sealdon me. hwæt dydest ðu;",
    "36": "Ða cwæð se hælend. mín ríce nys of ðyson middan-earde gif min ríce wære of ðyson middan-earde; Witodlice mine þegnas fuhton þt ic nære geseald iudeon; Nis min ríce of ðyson middan-earde;",
    "37": "Ða cwæð pilatus to him; Eart ðu witodlice cyning; Se hælend him &swarode & cwæð; Ðu hit segst þt ic eom cyng; On ðam ic eom geboren & to þam ic com on middan-eard. þt ic cyðe soþfæstnysse; Ælc þæra þe ys on soðfæstnysse gehyrð mine stefne;",
    "38": "Ða cwæð pilatus to him. hwæt ys soðfæstnyss; & þa he ðis cwæð þa eode he eft ut to þam iudeon & cwæð to him; Ne funde ic nanne gylt on ðyson menn.",
    "39": "hit ys eowor gewuna þt ic forgyfe eow anne mann on eastron. wylle ge þt ic forgyfe eow iudea cyning;",
    "40": "Hig clypodon ealle & cwædon. na ðysne. ac barrabbán. witodlice barrabbas wæs þeof;"},

"19": {

    "1": "Ða nam pilatus þone hælend & swang hyne",
    "2": "& þa þenas wundon þyrnenne cyne-helm. & asetton hyne on his héafod & scryddon hyne mid purpuran reafe",
    "3": "& hi comon to hym. & cwædon; Hál beo ðu iudea cyning & hi plætton hyne mid hyra handum;",
    "4": "Ða eode pilatus eft út & cwæð; Nu ic hyne læde hider út to eow þt ge ongyton þt ic ne funde nanne gylt on him;",
    "5": "Þa eode se hælend út & bær þyrnenne cyne-helm & purpuren reaf & sæde him. her is mann.",
    "6": "witodlice þa þa bisceopas. & ða þegnas hine gesawon. ða clypodon hig & cwædon; Hóh hyne hóh hyne; Ða cwæð pilatus to him. Nime ge hine & hoð. Ic ne funde nanne gylt on him",
    "7": "þa iudeas him &swaredon & cwædon; We habbað .æ. & be ure .æ. he sceal sweltan forþam þe he cwæð þt he wære godes sunu;",
    "8": "þa pilatus gehyrde þas spræce. þa on-dred he him þæs þe swiðor",
    "9": "& eode eft into þam domerne & cwæð to ðam hælende; Hwanon eart ðu. witodlice se hælend him ne sealde nane &sware;",
    "10": "Þa cwæð pilatus to him. hwí ne sprycst ðu wiþ me; Nast þu þt ic hæbbe mihte þe to honne. & ic hæbbe mihte þe to forlætene;",
    "11": "Se hælend him &swarode; Næfst þu nane mihte ongean me buton hyt wære þe ufan geseald. forþam se hæfð maran synne se ðe me þe sealde;",
    "12": "& syððan sohte pilatus hu he hyne forlete; Ða iudeas clypodon. & cwædon; Gif þu hine forlætst ne eart ðu þæs caseres freond; Ælc þæra þe hyne to cynge deð. ys þæs caseres wiðer-saca;",
    "13": "Ða pilatus þas spræce gehyrde. þa lædde he ut þone hælend. & sæt æt-foran þam dóm-setle on ðære stowe þe is genemned lithostrátós. & on ebreisc gabbatha;",
    "14": "Hit wæs þa eastra gegearcung-dæg & hyt wæs seo syxte tid ða cwæð he to ðam iudeon. her ys eower cyning.",
    "15": "Hi clypodon ealle & cwædon. nim hyne nim hyne. & hóh; Ða cwæð pilatus. sceal ic hón eowerne cyning. him &swaredon þa bisceopas & cwædon. Næbbe we nanne cyning buton kasere;",
    "16": "Ða sealde he hyne hym to ahónne; Ða namon hy þone hælend & tugon hine út",
    "17": "& bæron his rode mid him on þa stowe þe ys genemned heafodpannan stów. & on ebreisc golgotha",
    "18": "þær hi hyne ahengon. & twegen oðre mid him on twa healfa & þæne hælend on middan;",
    "19": "witodlice pilatus wrat ofer-gewrit. & sette ofer his róde þær wæs ongewriten. þis ys se nazareniscea hælend iudea cyning;",
    "20": "Manega ðæra iudea ræddon þiss gewrit forþam þe þeo stow wæs gehende þære ceastre þær se hælend wæs ahangen; Hit wæs awriten ebreisceon stafon & grecisceon. & leden stafon;",
    "21": "Ða cwædon þa bisceopas to pilate; Ne wrít ðu iudea cyng ac þt he cwæde ic eom iudea cyning;",
    "22": "Ða cwæð pilatus. ic wrat þt ic wrat;",
    "23": "Ða þa cempan hine ahengon hi namon his reaf & worhton feower dælas ælcon cempan anne dæl & tunecan; Seo tunece wæs unasiwod & wæs eall awefen;",
    "24": "Ða cwædon hi him betweonan. ne slite we hy ac uton hleotan hwylces ures heo sy. þt þt halige gewrit sy gefylled þe þus cwyþ. hi to-dældon. him míne reaf. & ofer mine reaf hi wurpon hlott; Witodlice þus dydon þa cempan;",
    "25": "Ða stodon wið þa róde þæs hælendes módor & his modor swustor maria cleophe & maria magdalenisce;",
    "26": "Ða se hælend geseah his módor & þæne leorning-cniht standende þe he lufode þa cwæþ he to his meder; Wíf her ys þin sunu.",
    "27": "eft he cwæð to þam leorning-cnihte Her ys þin módor; & of þære tide se leorning-cniht hi nam to him;",
    "28": "Æfter ðyson þa se hælend wiste þt ealle ðing wæron ge-endode þt þt halige gewrit wære gefylled. þa cwæð he me þyrst.",
    "29": "Ða stod án fæt full ecedes hi bewundon áne springan (sic) mid ysopo seo wæs full ecedes. & setton to his muðe.",
    "30": "þa se hælend onfeng þæs ecedes. ða cwæð he. hyt ys ge-endod. & he ahylde his heafod & agef his gast;",
    "31": "Ða iudeas bædon pilatum þt man for-bræce hyra sceancan. and lete hi nyðer for-þam þe hit wæs gegearcung-dæg. þt þa lichaman ne wunodon on róde o[n] reste-dæge; Se dæg wæs mære reste-dæg;",
    "32": "Ða comon þa cempan & bræcon ærest ðæs sceancan þe mid him ahangen wæs.",
    "33": "þa hi to þam hælende comon & gesawon þt he dead wæs ne bræcon hi na his sceancan;",
    "34": "Ac an þære cempena ge-openode his sídan mid spere & hrædlice þár fléow blod út & wæter",
    "35": "& seðe hit geseah cyðde gewitnesse. & his gewitnes is soð. & he wat þt he soð sæde þt ge gelyfon;",
    "36": "Ðas þing wæron gewordene þt þt gewrit wære gefylled. ne for-bræce ge nán bán on him.",
    "37": "hig geseoð on hwæne hig onfæstnodon;",
    "38": "Witodlice iosep fram arimathéa bæd pilatus þt He moste niman þæs hælendes lichaman. for-þam þe he wæs þæs hælendes leorning-cniht. þis he dyde dearnunga for þære iudea ege. & pilatus him lyfde; Ða com he & nam þæs hælendes lichaman",
    "39": "& nichodemus cóm ðyder se þe ærest cóm to þam hælende on niht & brohte wyrt-gemang & alewan swylce hund-teonti boxa",
    "40": "hig namon þæs hælendes lichaman & bewundon hine mid linenum claðe mid wyrt-gemangum swa iudea þ[e]aw ýs to bebyrgenne;",
    "41": "Witodlice þar wæs wyrtún on ðære stowe þar se hælend ahangen wæs. & on þam wyrtune wæs niwe byrgen. on þære þa gyt nan mann næs aléd.",
    "42": "Soðlice þar hig ledon þone hælend for-þam þæra iudea gearcung wæs wið þa byrgene."},

"20": {

    "1": "Witodlice on ánon reste-dæge seo magdalenisce maria cóm on mergen ær hit leoht wære to þære byrgenne & heo geseah þt se stan aweg anumen wæs fram þære byrgynne.",
    "2": "Ða arn heo & com to simone petre & to þam oðron leorni[n]g-cnihte þe se hælend lufode; & heo cwæð to him. hi namon drihten of byrgene & we nyton hwar hi hyne lédon;",
    "3": "Petrus eode út & se oðer leorning-cniht & comun to þære byrgene;",
    "4": "Witodlice hig twegen urnon æt-gædere & se oðer leorning-cniht for-árn petrus forne & com raðor to ðære byrgenne;",
    "5": "& þa he nyðer-abeah he geseah þa lin-wæda licgan; & ne eode þeah in;",
    "6": "Witodlice simón petrus com æfter him & eode into ðære byrgene; & he geseah lin-wæda licgean.",
    "7": "& þt swat-lin þe wæs uppan his heafde. ne læg hyt na mid þam linwædon ac onsundron gefealden on ánre stowe;",
    "8": "Ða eode eac in se leorning-cniht þe ærest cóm to ðære byrgene & geseah & gelyfde;",
    "9": "Witodlice þa gyt hi ne cuðon hali gewrit þt hit gebyrede þt he sceolde fram deaðe arísan;",
    "10": "Ða foron eft þa leorning-cnihtas to þam oðron.",
    "11": "Witodlice maria stod þar-úte æt ðære byrgyne & weop; & þa heo weop heo abeah nyðer & beseah innan þa byrgene",
    "12": "& geseah twegen englas sittan mid hwiton reafe. anne æt þam heafdon & oðerne æt þam fotum. þær ðæs hælendes líc aled wæs;",
    "13": "Hi cwædon to hyre. wíf hwi wepst þu. þa cwæð heo to hym. forþam hi namon minne drihten. & ic nat hwar hi hine ledon;",
    "14": "Ða heo þas þing sæde þa bewende heo hí on-bæc & geseah hwar se hælend stod & heo nyste þt hyt se hælend wæs;",
    "15": "Ða cwæð se hælend to hyre; Wíf hwi wepst ðu. hwæne secst þu. heo wende þt hit se wyrt-weard wære & cwæð to him; Leof gif þu hine name sege me hwar þu hine ledest & ic hine nime;",
    "16": "Ða cwæð se hælend to hyre. maría heo bewende hi & cwæð to him; Rabboni þt ys gecweden láreow;",
    "17": "Ða cwæð se hælend to hyre. ne æt-hrin þu min. nu gyt ic ne astah to minon fæder; Gang to minon broþron & sege him. ic astige to minon fæder and to eowron fæder. & to minon gode & to eowron gode;",
    "18": "Ða com seo magdalenisce maría & cyðde þam leorning-cnihton & cwæð; Ic geseah drihten & þas þing he me sæde;",
    "19": "Ða hit wæs æuén on anon þæra reste-daga & ða dure wæron belocene ðær þa leorning-cnihtas wæron gegaderode for ðæra iudea ege; Se hælend cóm & stod to-middes hyra & cwæð to him; Si sibb mid eow.",
    "20": "& þa he þt cwæð he æt-ywde him his handa & his sidan; Ða leorning-cnihtas wæron bliþe þa hi hæfdon drihten gesewen;",
    "21": "He cwæð eft to him. si sib mid eow. swa swa fæder me sende ic sénde eow;",
    "22": "Ða he þt cwæð. þa bleow he on hi & cwæð to him. under-foð haline gast",
    "23": "þæra synna þe ge forgyfað hig beoð him forgyuene. & þara þe ge healdað. hig beoþ gehealdene;",
    "24": "Witodlice thomás án of þam twelfon þe ys gecweden didimus þt ys gelicust on ure geþeode. he næs mid him þa se hælend com;",
    "25": "Ða cwædon ða oðre leorning-cnihtas to him. we gesawon drihten; Ða cwæð he to him. ne gelyfe ic buton ic geseo þæra nægela fæstnunge on his handa & ic do minne finger on ðære nægela stede & do mine hand to his sidan;",
    "26": "& eft æfter eahta dagun his leorning-cnihtas wæron inne & þomás mid him; Se hælend cóm belocenum duron & stod to-middes him & cwæð. sy eow sib;",
    "27": "Syððan he sæde þomé do ðinne finger hider & geseoh mine handa. & nim þine hand & do on mine sidan & ne beo þu unge[le]affull [ac geleafful];",
    "28": "Ðomás &swarode & cwæð to him; þu [eart] min god & min drihten;",
    "29": "Se hælend cwæð to him. þu gelyfdest forþam þu me gesawe. þa synt eadige þe ne ge-sawon & gelyfdon;",
    "30": "Witodlice manega oðre tacen se hælend worhte on his leorning-cnihta gesyhþe þe ne synt an þysse bec awritene;",
    "31": "Witodlice þas þing synt awritene þt ge gelyfon þt se hælend ys crist godes sunu; & þt ge habbað éce líf þonne ge gelyfaþ on his naman;"},

"21": {

    "1": "Eft æfter þan se hælend hine geswutelode þus æt ðære tiberiadiscan sæ;",
    "2": "Simón petrus & thomás ðe ys gecweden gelicost. wæron æt-gædere. & nathanaél se wæs of chaná galilææ. & zebedeus suna & oðre twegen þæra leorning-cnihta;",
    "3": "Ða cwæð simón petrus to him. ic wylle gan on fixað; Þa cwædon hi to him & we wyllað gan mid þe. & hi eodon út & eodon on scip & ne fengon nan þing on þære nihte;",
    "4": "Witodlice on ærne mergen se hælend stod on þam stránde. ne gecneowon þeah ða leorning-cnihtas þt hit se hælend wæs;",
    "5": "Ða cwæð se hælend to him. Cnapan. cweðe ge hæbbe ge sufol; Hig &swarodon him & cwædon. nese;",
    "6": "He cwæð to him. lætað þt nett on þa swiðran healfe þæs rewettes & ge gemetaþ; Hig leton witodlice & ne mihton hit ateon for ðæra fixa mænigu;",
    "7": "Witodlice se leorning-cniht þe se hælend lufode cwæð to petre. hit ys drihten; Ða petrus gehyrde þt hit drihten wæs. þa dyde he on his tunecan & be-gyrde hine; Witodlice he wæs ær nacod & scét innan sæ;",
    "8": "Ða oðre leorning-cnihtas reowon þar-to. hi wæron unfeor fram lande. swylce hit wære twa hund elna & tugon hyra fisc-nett;",
    "9": "Ða hig on land eodun hi gesawon licgan gleda & fisc þær on fyr & hláf;",
    "10": "Ða cwæð se hælend to him. bringað þa fixas þe ge nu ge-fengon;",
    "11": "Simón petrus eode úpp & teh his nett on land micelra fixa full þæra wæs hund-teontig & ðreo & fiftig; & ða hyra swa fæla wæs. næs þt net tobrocen;",
    "12": "Ða cwæð se hælend to him. gað hider & étað; And nán þæra þe þar sæt ne dorste hine axian hwæt he wære. hi wiston þt hit wæs drihten;",
    "13": "& se hælend cóm & nam hlaf & eac físc & sealde him;",
    "14": "On ðyson wæs se hælend þriwa geswutelud his leorning-cnihton þa he aras of deaðe;",
    "15": "Ða hi æton þa cwæð se hælend to símóne petre; Simón iohannis lufast ðu me. swiðor þænne ðas; He cwæð to him. gea drihten þu wast þt ic þe lufige he cwæð to him. heald mine lámb;",
    "16": "He cwæð eft to him; Simón iohannis lufast ðu me. he cwæð to him gea drihten þu wast þt ic ðe lufige; Ða cwæð he to him heald mine lamb;",
    "17": "He cwæð þriddan siðe to him. simón iohannis lufast ðu me. Ða wæs petrus sarig. forþam þe he cwæð þriddan siðe to him lufast þu me; And he cwæð to him. drihten þu wast ealle þing. þu wast þt ic þe lufige; Ða cwæð he to him heald mine sceap;",
    "18": "Soð ic secge þe. þa þu gingra wære. þu gyrdest þe & eodest þær þu woldyst. Witodlice þonne þu ealdast þu strecst þine handa & oðer þe gyrt. & læt þyder þe þu nelt;",
    "19": "Ðæt he sæde witodlice & tacnude hwylcon deaðe he wolde god geswuteligan; And þa he þt sæde þa cwæð he to him. fylig me;",
    "20": "Ða petrus hine bewende þa geseah he þt se leorning-cniht him fylide þe se hælend lufode. se þe hlinode on gebeorscype ofer his breost & cwæð; Drihten. hwæt ys se ðé belæwð;",
    "21": "Witodlice þa petrus þysne geseah. þa cwæð he to þam hælende. Drihten. hwæt sceal þes;",
    "22": "Ða cwæð se hælend to him. ic wylle þt he wunige ðus oð ic cume. cwæð (sic; over erasure) to þe. fylig ðu me;",
    "23": "Witodlice ðeos spræc cóm út gemang broþrum þt se leorning-cniht ne swylt. & ne cwæð se hælend to him ne swylt he. ac ðus ic wylle þt he wunige oð ic cume cwæð (sic; over erasure) to þe;",
    "24": "Þis ys se leorning-cniht þe cyð ge-witnysse be þyson & wrat ðas þing; And [we] witon þt hys gewrit ys soð;",
    "25": "Witodlice oðre manega þing synt þe se hælend worhte gif ða ealle awritene wæron. ic wene ne mihte þes middan-eard ealle þa bec befon. Amen."
} }