mark = {
"1": {
"1": "[H]er ys godspellys angyn Hælyndes cristes godes suna.",
"2": "Swa áwriten is on þæs witegan béc isaiam. nu ic asénde minne engel be-foran þinre ansyne. Se ge-gearwað þinne weg be-foran ðe.",
"3": "clypiende stefn on þam westene ge-gearwiað drihtnes weg. doð rihte his siðas;",
"4": "Iohannes wæs on westene fulligende & bodiende dædbote fulwiht on synna for-gyfenesse.",
"5": "& to him ferde eall iudeisc rice. & ealle hierosolima-ware. & wæron fram him gefullode. on iordanes flode hyra synna anddetenne;",
"6": "And iohannes wæs gescryd mid oluendes hærum. & fellen gyrdel wæs ymbe his lendenu. & gærstapan & wudu hunig he æt.",
"7": "& he bodude & cwæð. strengra cymð æfter me. þæs ne eom ic wyrðe þt ic his sceona þwanga bugende uncnytte.",
"8": "Ic fullige eow on wætere. he eow fullað on halgum gaste.",
"9": "& on ðam dagum cóm se hælend fram nazareth galilee & wæs ge-fullod on iordané fram iohanne.",
"10": "& sona of ðam wætere he geseah opene heofonas. & haligne gast swa culfran astigende & on him wunigende.",
"11": "& þa wæs stefn of heofenum geworden. þu eart min ge-lufoda sunu on þe ic gelicode;",
"12": "And sona gast hine on westen genydde.",
"13": "& he on wéstene wæs feowertig daga & feowertig nihta. & he wæs fram satane gecostnod. & he mid wilddeorum wæs & him englas þenodon;",
"14": "Syððan iohannes geseald wæs. com se hælend on galileam godes rices. godspell bodigende",
"15": "& þus cweðende. witodlice tíd is gefylled & heofena ríce genealæcð. doð dæd-bote & gelyfaþ þam godspelle.",
"16": "& þa he ferde wið þa galileiscan sæ. he geseah simonem & andream his broðor hyra nett on þa sæ lætende. Soðlice hi wæron fisceras;",
"17": "And þa cwæð se hælend cumað æfter me & ic dó inc þt gyt beoð sawla onfonde.",
"18": "& hi þa hrædlice him fyligdon. & for-leton heora net.",
"19": "& ðanon hwón agán he geseah iacobum & zebedei & iohannes his broðor. & hi on heora scype heora nett logodon.",
"20": "& he hi sona clypode. & hi heora fæder zebedeo on scipe forleton. mid hyrlingum.",
"21": "& ferdon to cafarnaum & sona reste-dagum he lærde hi on gesamnunge. ingancgende",
"22": "& hi wundredon be his láre; Soþlice he wæs hi lærende swa se þe anweald hæfð. næs swa boceras.",
"23": "& on heora gesamnunge wæs sum man. on unclænum gaste & he hrymde",
"24": "& cwæð eala nazarenisca hælend hwæt is us & þe. com ðu us to for-spillanne. ic wat þu eart godes halga;",
"25": "Ða cidde se hælend him & cwæð adumba. & gá of þisum men.",
"26": "& se unclæna gast hine slitende & mycelre stefne clypiende him of eode;",
"27": "Þa wundredon hi ealle swa þt hi betwux him cwædon. hwæt ys þis. hwæt is þeos niwe lár. þt he on anwealde unclænum gastum bebyt. & hi hyrsumiað him.",
"28": "& sona ferde his hlísa to galilea rice;",
"29": "Hrædlice of hyra gesamnunge hi comon on simonis & andreas hus. mid iacobe & Iohanne;",
"30": "Soðlice þa sæt simonis swegr hriðigende & hi him be hyre sædon.",
"31": "& ge-nealæcende he hi up ahóf hyre handa ge-gripenre. & hrædlice se fefor hi forlet. & heo þenode him;",
"32": "Soðlice þa hit wæs æfen geworden þa sunne to setle eode. hi brohton to him ealle þa unhalan. & þa ðe wóde wæron.",
"33": "& eall seo burh-waru wæs ge-gaderod to þære duran.",
"34": "& he manega gehælde þe missenlicum ádlum gedrehte wæron. & manega deofol-seocnyssa he ut adraf. & hi sprecan ne lét. forþam hi wiston þt he crist wæs;",
"35": "And swiðe ær arisende he ferde. on wéste stowe & hine þar gebæd",
"36": "& him fyligde simon. & þa ðe mid him wæron.",
"37": "& þa hi hine gemetton hi sædon him. eall þis folc ðe secð;",
"38": "Þa cwæð he fare we on ge-hende túnas & ceastra. þt ic ðar bodige. witodlice to ðam ic com.",
"39": "& he wæs bodigende on heora ge-samnungum & ealre galilea. & deofol-seocnessa ut adrifende;",
"40": "And to him com sum hreofla hine biddende. & gebigedum cneowum him to cwæþ; Drihten. gif þu wylt ðu miht ge-clænsian me;",
"41": "Soðlice se hælend him ge-miltsode. & his hand aþenode & hine æt-hrinende & þus cwæð; Ic wylle. beo ðu geclænsod.",
"42": "& þa he ðus cwæð sona seo hreofnys him fram ge-wát. & he wæs geclænsod.",
"43": "& sona he bead him",
"44": "& cwæð. warna þt ðu hit nanum men ne secge. ac gá & æt-yw ðe þara sacerda ealdre. & bring for ðinre clænsunga þt moyses bebead him on ge-witnesse.",
"45": "& he þa ut-gangende ongan bodian & widmærsian þa spræce; Swa þt he ne mihte openlice on þa ceastre gán. ac beon úte on westum stowum & hi æghwanon to him comon."},

"2": {
"1": "& eft æfter dagum he eode into cafarnaum. & hit wæs ge-hyred þt he wæs on huse",
"2": "& manega togædere comon. & he to heom spræc.",
"3": "& hi comon anne laman to him berende. þone feower men bæron.",
"4": "& þa hí ne mihton hine inbringan for þære mænigu. hi openodon þone hróf þar se hælend wæs. & hi þa in-asendan. þt bed þe se lama on læg;",
"5": "Soðlice ða se hælend geseah heora geleafan. he cwæð to þam laman; Sunu þe synt þine synna for-gyfene.",
"6": "Þar wæron sume of ðam bocerum sittende. & on heora heortum þencende",
"7": "hwí spycð þes þus. he dysegað. hwa mæg synna for-gyfan buton god ána;",
"8": "Ða se hælend þt on his gaste oncneow. þt hi swa betwux him þohton. he cwæð to him. hwi ðence ge þas ðing on eowrum heortan.",
"9": "hwæðer is eðre to secgenne to þam laman. þe synd ðine synna forgyfene. hwæðer þe cweðan arís nim ðín bed & gá.",
"10": "þt ge soðlice witon þt mannes sunu hæfð anweald on eorðan; synna to for-gyfanne; He cwæð to þam láman",
"11": "þe ic secge arís. nim þin bed. & gá to þinum huse",
"12": "& he sona aras. & be-foran him eallum eode; Swa þt ealle wundredon & þus cwædon. næfre wé ær þyllic ne ge-sawon.",
"13": "eft he ut eode to ðære sæ. & eall seo menigeo him to com & he hi lærde.",
"14": "& þa he forð eode he ge-seah leuin alphei. sittende æt his cep-setle. & he cwæð to him folga mé. þa aras he & folgode him.",
"15": "& hit gewearð þa he sæt on his húse þt manega manfulle. sæton mid þam hælende & his leorning-cnihtum; Soðlice manega þa ðe him fyligdon wæron",
"16": "boceras & farisei. & cwædon. witodlice he ýtt mid mánfullum & synfullum. & hi cwædon to his leorning-cnihtum. hwi ytt eower lareow & drincð. mid manfullum & synfullum;",
"17": "Þa se hælend þis ge-hyrde he sæde him. ne beþurfon na ða halan læces. ac ða þe untrume synt; Ne com ic na þt ic clypode riht-wise ac synfulle.",
"18": "& þa wæron Iohannes leorning-cnihtas & pharisei fæstende. & þa comon hi & sædon him; Hwi fæstað iohannes leorning-cnihtas & phariseorum. & þine ne fæstað;",
"19": "Ða .cw. se hælend. cweðe ge sceolan þæs brydguman cnihtas fæstan swa lange swa se brydguma mid him is. ne magon hi fæstan swa lange tíde swa hi ðone brydguman mid him habbað;",
"20": "Soðlice þa dagas cumað þonne se brydguma him bið fram acyrred. & þonne hi fæstað; On þam dagum",
"21": "nán man ne síwaþ níwne scýp to ealdum reafe elles he afyrð þone níwan scyp. of þam ealdan reafe. & biþ mare slite.",
"22": "& nán man ne deð niwe win on ealde bytta. elles þt wín tobrycð þa bytta. & þt wín bið agoten. & þa bytta forwurðaþ; Ac niwe wín sceal beon gedon on níwe bytta. þonne beoð butu gehealden;",
"23": "Eft wæs geworden þa he reste-dagum þurh æceras eode. his leorning-cnihtas ongunnon þa éár pluccigean.",
"24": "þa cwædon pharisei to him. loca nu hwæt þine leorning-cnihtas doð. þt him alyfed næs. on reste-dagum;",
"25": "Þa sæde he him ne rædde ge næfre. hwæt dyde dauid þa hine hingrode. & þa ðe mid him wæron.",
"26": "hu he in godes huse eode. under abiathár þara sacerda ealdre. & he æt þa ofrung-hlafas. þe him ne alyfede næron to etanne. buton sacerdon anum. & he sealde þam ðe mid him wæron.",
"27": "& he sæde him. reste-dæg wæs geworht for þa men. næs se man for ðam reste-dæge;",
"28": "Witodlice drihten is mannes sunu eac swylce reste-dæges;"},

"3": {
"1": "And eft he eode on ge-samnunge & þar wæs án man for-scruncene hand hæbbende",
"2": "& hi gymdon hwæþer he on reste-dagum gehælde. þt hi hine gewregdon;",
"3": "Ða cwæð he to ðam men þe for-scruncene hand hæfde. arís gemang him.",
"4": "þá cwæð he alyfð reste-dagum wel to dónne hweþer ðe yfele. sawla ge-hælan. hweþer ðe for-spillan. & hí suwodon.",
"5": "& hi besceawiende mid yrre ofer hyra heortan blindnesse ge-unrét cwæð to þam men; Aþene þine hand. & he aþenede hi. þa wearð his hand ge-hæled sona;",
"6": "Þa pharisei mid herodianiscum utgangende þeahtedon ongen hine. hu hi hine fordon mihton.",
"7": "& þa ferde se hælend to þære sæ. mid his leorning-cnihton. & mycel menigeo him fyligde fram galilea. & iudea.",
"8": "& hierusalem. & fram iudea & be-geondan iordane & to him com mycel menegeo ymbe tírum & sidóne gehyrende þa ðing þe he worhte.",
"9": "& he cwæð to his cnihtum þt hi him on scipe þenodon. for þære menigu þt hi hine ne ofþrungon;",
"10": "Soþlice manega he ge-hælde; Swa þt hi æt-hrinon his. & swa fela swa untrumnessa",
"11": "& unclæne gastas hæfdon; Þa hi hine gesawon. hi to-foran him astrehton. & þus cweðende clypedon. þu eart godes sunu.",
"12": "& he him swyðe forbead. þt hi hine ne ge-swutelodon.",
"13": "& on anne munt he ferde & to him ge-clypode þa ðe he wolde & hi to him comon",
"14": "& he dyde þt hi twelfe mid him wæron. & he hi asende godspell to bodigenne.",
"15": "& he him anweald sealde untrumnessa to hælanne. & deofol-seocnessa út to adrifanne.",
"16": "& he nemde simon petrum",
"17": "& iacobum zebedei. & iohannem his broðor & him naman onsette. boaneries þt is ðunres bearn.",
"18": "& andream. & philippum. & bartholomeum & thomam. & iacobum alphei. & taddeum. & simonem chananeum.",
"19": "& iudam scarioth. se hine sealde.",
"20": "& eft him to com. swa micel menigu. þt hi næfdon hlaf to etanne",
"21": "& þa hi hine gehyrdon hi ferdon þt hi hine namon & þus cwædon; Soðlice he is on hat-heortnesse gewend.",
"22": "& þa boceras þe wendon fram hierusalem cwædon; Soþlice he hæfð beelzebub & on deofla ealdre he deoful-seocnessa ut adrífð.",
"23": "& he hi togædere geclypode. & on bigspellum him to cwæð; Hu mæg satanas satanan ut adrifan.",
"24": "& gif his rice on him sylfum bið to-dæled hu mæg hit standan",
"25": "& gif þt hus ofer hit sylf ys to-dæled. hu mæg hit standan",
"26": "& gif satanas winð ongen hine sylfne he bið to-dæled & he standan ne mæg ac hæfð ende;",
"27": "Ne mæg man þone strangan his æhta & his fatu be-reafian & on his hus gan, buton man þone strangan ærest gebinde. & þonne his hus reafige;",
"28": "Soðlice ic eow secge þt ealle synna synd manna bearnum forgyfene. & bysmorunga þam ðe hi bysmeriað;",
"29": "Soþlice ic eow secge se þe ðone halgan gast bysmerað. se næfð on ecnysse forgyfenesse; Ac bið éces gyltes scyldig.",
"30": "forþam þe hi cwædon he hæfð unclænne gast.",
"31": "Þa com to him his modor & his gebroðra. & þar-ute stodon & to him sendon. & to him clypedon.",
"32": "& mycel menigu ymb hine sæt and to him cwædon. her is þin modor & þine gebroðra úte & secaþ þe;",
"33": "He þa him andswarode & cwæð. hwylc is min modor & mine gebroþru.",
"34": "& he cwæþ ða behealdende þe him abuton sæton. her is min modor & mine gebroðru;",
"35": "Soðlice se ðe déþ godes willan se is min modor & min broðor & swustor."},

"4": {
"1": "& eft he ongan hi æt þære sæ læran. & him wæs mycel menegu togegaderod; Swa þt he on scip eode. & on þære sæ wæs. & eall seo menegu ymbe þa [sæ] wæron on lande.",
"2": "& he hi fela on bigspellum lærde. & him to cwæð on his lare.",
"3": "gehyrað; +Ut eode se sædere his sæd to sawenne.",
"4": "& þa he sew sum feoll wið þone weg. & fugelas comon & hit fræton;",
"5": "Sum feoll ofer stan-scyligean þar hit næfde mycele eorðan. & sona úp eóde. & forþam hit næfde eorþan þiccnesse.",
"6": "þa hit up-eode. Seo sunne hit forswælde. & hit forscranc. forþam hit wyrt-ruman næfde.",
"7": "& sum feoll on þornas. þa stigon ða þórnas & forðrysmodon þt. & hit wæstm ne bær.",
"8": "& sum feoll on god land & hit sealde upp-stigende & wexende wæstm; & án brohte þritig-fealdne; Sum syxtig-fealdne; Sum hund-fealdne;",
"9": "And he cwæð. gehyre se ðe earan hæbbe to gehyranne.",
"10": "& þa he ana wæs hine axodon þt bigspell þa twelfe þe mid him wæron.",
"11": "& he sæde him. eow is geseald to witanne godes ríces gerýnu; Þam þe úte synt ealle þing on bigspellum gewurþað.",
"12": "þt hi geseonde geseon & na ne ge-seon & gehyrende gehyren & ne ongyten þe læs hi hwænne sýn gescyrede. & him sín hyra synna forgyfene;",
"13": "Ða sæde he him. ge nyton þis bigspell. & hu mage ge ealle bigspell witan;",
"14": "Se þe sæwð. word he sæwð;",
"15": "Soðlice þa synt wið þone weg þar þt word is gesawen. & þonne hi hit gehyrað; Sona cymð satanas & afyrð þt word þe on heora heortan asawen ys.",
"16": "& þa synt gelice þe synt ofer þa stan-scylian gesawen; Sona þænne hi þt word gehyrað. & þt mid blisse onfoð.",
"17": "& hi nabbað wyrtruman on him. ac beoð unstaðolfæste. & syþþan upcymð deofles costnung & his ehtnys for þam worde;",
"18": "Hi synd on þornum gesawen. þt synd þa ðe þt word gehyrað.",
"19": "& of-yrmðe & swicdome worold-welene. & oðra gewilnunga þt word of-þrysmað. & synt buton wæstme gewordene.",
"20": "& þa ðe gesawene synt ofer þt gode land. þa synd þe þt word gehyrað & onfoð. & wæstm bringað. Sum þritig-fealdne. sum syxtig-fealdne. & sum hund-fealdne;",
"21": "He sæde him cwyst þu cymð þt leoht-fæt þt hit beo under bydene asett. oððe under bedde. witegere þt hit sy ofer candel-stæf asett;",
"22": "Soðlice nis nan ðing behydd þe ne sy geswutelod; ne nis digle geworden. ac þt hit openlice cume;",
"23": "Gehyre gif hwa earan hæbbe to gehyranne.",
"24": "& he cwæð to him warniað hwæt ge gehyran. & on þam gemete. þe ge metað eow bið gemeten & eow bið ge-ict.",
"25": "þam bið geseald þe hæfð & þam ðe næfð. eac þt he hæfð him bið æt-broden.",
"26": "& he cw. godes rice ys swylce man wurpe god sæd on his land",
"27": "& sawe & arise dæges & nihtes. & þt sæd. growe & wexe þonne he nat;",
"28": "Soðlice sylf-willes seo eorðe wæstm berað ærest gærs syððan ear. syþþan fullne hwæte on þam eare;",
"29": "And þonne se wæstm hine forð-bringð. sona he sent his sícol forþam þt rip æt is.",
"30": "& eft he cwæð. for hwam geanlicie we heofena ríce. oððe hwylcum bigspelle wið-mete we hit;",
"31": "Swa swa senepes sæd. þonne hit bið on eorðan gesawen. hit is ealra sæda læst þe on eorðan synt.",
"32": "& þonne hit asawen bið hit astihþ. & bið ealra wyrta mæst & hæfð swa mycele bógas þt heofenes fugelas eardian magon under his sceade.",
"33": "& manegum swylcum bigspellum he spræc to him þæt hi mihton gehyran;",
"34": "Ne spæc he na butan bigspelle. eall he his leorning-cnihtum asundron rehte.",
"35": "& sæde him þonne æfen bið uton faran agen;",
"36": "And þas menigu forlætan; hi onfengon hine swa he on scipe wæs. & oþre scipu wæron mid him.",
"37": "& þa wæs mycel ýst windes geworden. & yþa he awearp on þt scyp þt hit gefylled wæs",
"38": "& he wæs on scipe ofer bolster slapende. & hi awehton hine & cwædon. ne be-limpð to þe þt we forwurþað.",
"39": "& he arás & þam winde bebead. & cwæð to ðære sæ; Suwa & gestille. & se wind geswac þa. & wearð mycel smyltnes.",
"40": "& he sæde him hwi synt ge forhte. gyt ge nabbað geleafan.",
"41": "& hi micclum ege him ondredon. & cwædon ælc to oðrum hwæt wenst þu hwæt is ðes þt him [wyndas &] sæ hyrsumiað;"},

"5": {
"1": "Ða comon hi ofer þære sæs muðan on þt ríce. hierasenórum",
"2": "& him of scipe gangendum him sona agen árn án man of þam byrgenum on unclænum gaste;",
"3": "Se hæfde on byrgenum scræf & hine nán man mid racenteagum ne mihte gebindan.",
"4": "forþam he oft mid fot-coppsum & racenteagum gebunden. toslat þa raceteaga & þa fot-coppsas tobræc. & hine nán man gewyldan ne mihte.",
"5": "& symle dæges & nihtes he wæs on byrgenum and on muntum. hrymende & hine sylfne mid stanum ceorfende;",
"6": "Soðlice ða he þone hælend feorran geseah. he árn & hine gebæd.",
"7": "& mycelre stemne hrymende & þus cw. eala mæra hælend godes sunu hwæt is me & þe. Ic halsige þe ðurh god þt ðu me ne þreage;",
"8": "Þa cwæð se hælend. eala unclæna gast. ga of ðysum men;",
"9": "Ða ahsode he hine hwæt is þin nama. þa cwæð he min nama is legio. forþam we manega synt.",
"10": "& he hine swyðe bæd þt he hine of þam rice ne dyde.",
"11": "þar wæs embe þone munt mycel swyna heord læsgende.",
"12": "& þa unclænan gastas hine bædon & cwædon; Send ús on þas swyn þt we [on] hi gegán.",
"13": "& þa lyfde se hælend sona. & ða eodon þa unclænan gastas on þa swýn. & on myclum hryre seo heord wearð on sæ besceofen. twa þusendo & wurdon adruncene. on ðære sæ;",
"14": "Soþlice þa ðe hi heoldon flugon & cyddon on þære ceastre & on lande & hí ut eodon þt hi ge-sawon hwæt þar gedón wære.",
"15": "& hi comon to þam hælende & hi gesawon þone ðe mid deofle gedreht wæs. gescrydne sittan. [&] hales modes. & hi him ondredon.",
"16": "& hi rehton him þa ðe hit gesawon hu hit gedón wæs. be þam ðe deofol-seocnesse hæfde & be þam swynum.",
"17": "& hi bædon þt he of hyra ge-mærum fore;",
"18": "Þa he on scip eode hine ongan biddan se ðe ær mid deofle gedreht wæs. þt he mid him wære;",
"19": "Him þa se hælend ne getiðode. ac he sæde him ga to þinum huse to þinum híwum & cyð him hu mycel drihten gedyde & he ge-miltsode þe;",
"20": "And he ða ferde & ongan bodigean on decapolim hu fela se hælend him dyde. & hig ealle þæs wundredon;",
"21": "And þa se hælend eft on scype ferde ofer þone muþan him com to mycel menigu & wæs ymbe þa sæ.",
"22": "& ða com sum of heah-gesamnungum iáirus hatte; & þa he hine geseah he astrehte hine to his fotum",
"23": "& hine swyðe bæd. & he cwæð; Min dohtor is on ytemestum siðe. cum & sete þine hand ofer hi þt heo hal sy & lybbe;",
"24": "Ða ferde he mid him & him fyligde mycel menigeo & þrungon hine;",
"25": "& þa þt wíf ðe on blodryne twelf winter wæs.",
"26": "& fram manegum læcum fela þinga þolode. & dælde eall þt heo ahte. & hit naht ne fremode. ac wæs þe wyrse;",
"27": "Þa heo be ðam hælende gehyrde heo com wið-æftan þa menigu & his reaf æt-hrán;",
"28": "Soðlice heo cwæð gif ic fúrþon his reafes æt-hríne ic beo hál;",
"29": "And þa sona wearð hyre blodes ryne adruwod. & heo on hire gefredde þt heo of þam wíte gehæled wæs;",
"30": "And þa se hælend on-cneow on him sylfum þt him mægen of-eode. he cwæð bewend to þære menigu; Hwa æthran mines reafes.",
"31": "þa cwædon his leorning-cnihtas þu ge-syxst þas menigu þe ðringende. & þu cwyst hwa æt-hran me;",
"32": "And þa beseah he hine þt he ge-sawe þæne ðe þt dyde;",
"33": "Ðat wíf þa ondrædende & forhtigende com & astrehte hi be-foran him & sæde him eall þt riht;",
"34": "Þa cwæð se hælend. dohtor þin geleafa þe hale gedyde. ga þe on sibbe & beo of ðisum hal;",
"35": "Him þa gyt sprecendum hi comon fram þam heah-gesamnungum & cwædon; Ðín dohtor is dead. hwi drecst þu leng þone lareow;",
"36": "Þa he ge-hyrde þt word þa cwæð se hælend ne ondræd þu ðe gelyf for án;",
"37": "And he ne lét him ænigne fyligean. buton petrum. & iacobum. & iohannem. Iacobes broðor",
"38": "& hi comon on þæs heah-ealdres hus. & he ge-seah mycel gehlyd wepende & geomriende;",
"39": "And þa he ineode he cw. hwi synd ge gedrefede & wepað. nis þis mæden na dead ac heo slæpð;",
"40": "Ða tældon hi hine; He þa eallum út adrifenum. nam petrum & þæs mædenes modor. & þa ðe mid him wæron. & inn-eodon suwiende þar þt mæden wæs.",
"41": "& hire hand nam & cwæð. thalim-tha cumi. þt is on ure geþeode gereht. mæden þe ic secge arís;",
"42": "& heo sona aras & eode; Soðlice heo wæs twelf wintre. & ealle hi wundredon mycelre wundrunge.",
"43": "& he him þearle bebead þt hi hyt nanum men ne sædon & he het hire etan syllan;"},

"6": {
"1": "And þa he ðanon eode he ferde on his eðel. & him folgodon his leorning-cnihtas;",
"2": "& gewordenum reste-dæge he ongann on gesamnunge læran & manege gehyrdon & wundrodon on his láre & cwædon; Hwanon synd þyssum ealle þas ðincg and hwæt is se wisdom þe him ge-seald is. & swylce mihta þe ðurh his handa gewordene synd;",
"3": "Hu nys [þys] se smið marian sunu. iacobes broðor. & Iosepes. & iude [&] simonis. hu ne synt his swustra her mid ús. & þa wurdon hi gedrefede.",
"4": "þa cwæð se hælend; Soðlice nis nán witega buton wurðscipe. buton on his eðele & on his mægðe. & on his húse;",
"5": "And he ne mihte þar ænig mægen wyrcan. buton feawa untrume on-asettum his handum he ge-hælde.",
"6": "& he wundrode for heora ungeleafan; He ða lær[en]de þa castel be-ferde.",
"7": "& him twelfe togeclypode. & agan hi sendan twam & twam. & him anweald sealde unclænra gasta.",
"8": "& him bebead þt hi naht on wege ne namon. buton gyrde áne. ne codd ne hlaf. ne feoh on heora gyrdlum;",
"9": "Ac ge-sceode mid calcum & þt hi mid twam tunecum gescrydde næron;",
"10": "And he cwæð to him; Swa hwylc hús swa ge ingað. wuniað þar oð þt ge út-gan.",
"11": "& swa hwylce swa eow ne ge-hyrað. þonne ge þanon út gað ásceacað þt dust of eowrum fotum. him on ge-witnesse;",
"12": "And út-gangende hi bodedon þt hi dædbote dydon",
"13": "& hi manega deofol-seocnessa út-adrifon. & manega untrume mid ele smyredon & gehældon;",
"14": "And þa gehyrde herodes se cyng þæt; Soþlice his nama wæs swutol geworden & he cwæð; Witodlice Iohannes se fulluhtere of deaðe aras. & on him synd forþam mægenu geworht;",
"15": "Sume cwædon he is elias. sume cwædon he is witega swylce án of þam witegum;",
"16": "Ða herodes þt ge-hyrde he cwæð; Se iohannes þe ic be-heafdode se aras of deaðe;",
"17": "Soðlice herodes sende & hét iohannem gebindan on cwerterne. for þære herodiadiscan his broðar láfe philippus. for þam ðe he nam hi;",
"18": "Þa sæde Iohannes heróde. nys þe alyfed to hæbbenne þines broðer wíf;",
"19": "Ða syrwde herodias ymbe hine & wolde hine of-slean & heo ne mihte;",
"20": "Soðlice herodes on-dred Iohannem & wiste þt he wæs rihtwis. & halig. & he heold hine on cwerterne. & he ge-hyrde þt he fela wundra worhte & he luflice him hyrde;",
"21": "Þa se dæg com herodes gebrydtíde he ge-gearwode mycele feorme his ealdor-mannum. & þam fyrmestum on galilea.",
"22": "& þa ða þære herodiadiscan dohtor inneode & tumbode. hit licode heróde. & eallum þam ðe him mid sæton; Se cing cwæð þa to ðam mædene. bide me swa hwæt swa þu wylle & ic þe sylle;",
"23": "And he swór hire. soðes ic þe sylle swa hwæt swa þu me bitst. þeah þu wylle healf min rice;",
"24": "Ða heo út eode heo cwæð to hyre meder; Hwæs bidde ic; Þa cwæþ heo. iohannes heafod þæs fulluhteres;",
"25": "Sona þa heo mid ofste inn to þam cinincge eode. heo bæd & þus cwæð; Ic wylle þt ðu me hrædlice on anum disce sylle iohannes heafod;",
"26": "Þa wearð se cinincg geunrét for þam aðe. & for þam ðe him mid sæton; Nolde þeah hi ge-unretan.",
"27": "ac sende ænne cwellere & bebead þt man his heafod on ánum disce brohte; And he hine þa on cwerterne beheafdode.",
"28": "& his heafod on disce brohte & hit sealde þam mædene. & þt mæden hit sealde hire meder;",
"29": "Ða his cnihtas þt ge-hyrdon hi cómon & his líc namon. & hine on byrgene ledon;",
"30": "Soðlice þa ða apostolas togædere comon. hi cyddon þam hælende eall þt hi dydon & hi lærdon.",
"31": "& he sæde him; Cumað & uton gán onsundron on weste stowe. & us hwon restan; Soðlice manega wæron þe comon & agén-hwyrfdon & fyrst næfdon þt hi æton.",
"32": "& on scyp stigende. hi fóron onsundran on weste stowe.",
"33": "& gesawon hi farende. & hi ge-cneowon manega; And gangende of þam burgum þyder úrnon. & him beforan comon;",
"34": "And þa se hælend ðanon eode. he geseah mycele menegu. & he ge-miltsode him for þam þe hi wæron swa swa scép þe nanne hyrde nabbað; And he ongan hi fela læran.",
"35": "& þa hit mycel ylding wæs. his leorning-cnihtas him to comon & cwædon. þeos stow is wéste & tíma is forð agán.",
"36": "forlæt þas menegu. þt hi faran on ge-hende tunas. & him mete bicgan. þt hi eton;",
"37": "Þa cwæð he sylle ge him etan; Ða cwædon hi uton gan. & mid twam hundred penegon hlafas bicgan. & we him etan syllað;",
"38": "Ða cwæð he hu fela hlafa hæbbe ge. gað & lociað. & þa hi wiston hi cwædon. fif hlafas & twegen fixas.",
"39": "& þa be-bead se hælend þt ðæt folc sæte ofer þt grene hig.",
"40": "& hi þa sæton hundredon & fiftigon.",
"41": "& fif hlafum. & twam fixum onfangenum he on heofon locode & hi bletsode. & þa hlafas bræc. & sealde his leorning-cnihtum. þt hi toforan him asetton. & twegen fixas him eallon dælde",
"42": "& hi æton þa ealle & gefyllede wurdon;",
"43": "And hi namon þara hlafa. & fixa lafe. twelf wilian fulle;",
"44": "Soðlice fif þusend manna þara etendra wæron;",
"45": "Ða sona he nydde his leorning-cnihtas on scyp stígan. þt hi him beforan foron ofer þæne muþan to bethsaida. oþ he þt folc for-lete;",
"46": "And þa he hi for-let he ferde on þone munt & hine ana þar gebæd;",
"47": "And þa æfen wæs þt scyp wæs on middre sæ. & he ana wæs on lande",
"48": "& he ge-seah hi on rewette swincende. him wæs wiðer-weard wind; And on niht embe þa feorþan wæccan he com to him ofer þa sæ gangende. & wolde hi for-bugan;",
"49": "Þa hi hine gesawon ofer þa sæ gangende hi wendon þt hit unfæle gast wære. & hi clypedon;",
"50": "Hi ealle hine gesawon. & wurdon gedrefede & sona he spræc to him & cwæð; Gelyfaþ ic hit eom. ne þurfon ge eow ondrædan.",
"51": "& he on scyp to him eode. & se wind geswác & hi þæs þe má betwux him wundredon.",
"52": "ne ongeton hi be þam hlafon; Soðlice heora heorte wæs ablend;",
"53": "And þa hi ofer-segledon. hi comon to genesár. & þar wicedon.",
"54": "& þa hi of scipe eodon. sona hi hine gecneowon;",
"55": "And eall þt ríce befarende hi on sæccingum bæron þa untruman. þar hi hine gehyrdon;",
"56": "And swa hwar swa he on wíc oþþe on túnas eode. on stræton hi þa untruman ledon. & hine bædon þt hi huru his refes fnæd æt-hrinon. & swa fela swa hine æt-hrinon hi wurdon hale."},

"7": {
"1": "Þa comon to him pharisei & sume boceras cumende fram hierusalem.",
"2": "& þa hi ge-sawon sume of his leorning-cnihton besmitenum handum þt is únþwogenum handum etan. hi tældon hi & cwædon;",
"3": "Pharisei & ealle iudeas ne etað buton hi hyra handa gelomlice þwean. healdende hyra yldrena gesetnessa.",
"4": "& on stræte hi ne etað buton hi geþwegene beon. & manega oþre synd þe him gesette synt. þt is calicea frymða. & ceaca. & árfata. & mæstlinga;",
"5": "And þa axodon hine pharisei & þa boceras. hwi ne gað þine leorning-cnihtas æfter ure yldrena gesetnysse. ac besmitenum handum hyra hlaf þicgað;",
"6": "Ða andswarode he him; Wel witegod isaias be eow licceterum swa hit awriten is; Þis folc me mid welerum wurðað. soðlice hyra heorte is feor fram me.",
"7": "on idel hi me wurðiað. & manna láre & bebodu lærað;",
"8": "Soþlice ge forlætað godes bebod. & healdað manna laga. þweala ceaca & calica. & manega oþre þylce ðing ge doð;",
"9": "Ða sæde he him. wel ge on idel dydon godes bebod þt ge eower laga healdon;",
"10": "Moyses cwæð. wurða þinne fæder & þine modor. & se ðe wyrigþ his fæder & his modor. swelte se deaþe;",
"11": "Soðlice ge cweþað. gif hwa segð his fæder & meder corbán þt is on ure geðeode gyfu. gif hwylc is of me þe fremað.",
"12": "& ofer þt ge ne lætað hine ænig þing dón his fæder oððe meder",
"13": "toslitende godes bebod. for eower stúntan lage þe ge gesetton. & manega oþre þing ðysum gelice ge doð;",
"14": "And eft þa menegu he him toclypode & cwæð; Ge-hyraþ me ealle & ongytað;",
"15": "Nis nán þing of þam men on hine gangende þt hine besmítan mæge; Ac þa ðing þe of ðam men forð-gað. þa hine besmitað.",
"16": "gif hwa earan hæbbe gehlyste me;",
"17": "And þa se hælend fram þære menegu eode his leorning-cnihtas hine án big-spell ahsodon;",
"18": "Þa cwæð he. & synt ge þus ungleawe ne on-gyte ge. þt eall þæt utan cymð on þone man gangende. ne mæg hine besmitan.",
"19": "forþam hit ne gæð on his heortan. ac on his innoð. & on forð-gang gewíteð ealle mettas clænsigende;",
"20": "Ða sæde he him þt ða þing ðe of þam men gað. þa hine besmitað;",
"21": "Innan of manna heortan. yfele geþancas cumað. unriht-hæmedu. & forligeru. manslihtas.",
"22": "[stala.] gytsung. mán. facnu. sceamleast. yfel gesihð. dysinessa. ofer-modignessa. stuntscipe.",
"23": "& ealle þas yfelu of þam innoðe cumað & þone man besmitað;",
"24": "Ða ferde he þanon on þa endas tíri & sidónis. & he in-agán on þt hús. he nolde þt hit ænig wiste. & he ne mihte hit be-miðan;",
"25": "Sona þa án wif be him ge-hyrde. þære dohtor hæfde unclæne gast. heo ineode. & to his fotum hi astrehte;",
"26": "Soðlice þt wíf wæs hæðen. sirofenisces cynnes. & bæd hine þt he ðone deofol of hyre dehter adrife;",
"27": "Þa sæde he hire; Læt ærust þa bearn beon gefylled. nis na gód þt man nime þara bearna hlaf. & hundum worpe;",
"28": "Ða &swarode heo & cþ; Drihten þt is soð; Witodlice þa hwelpas etað under þære mýsan. of ðara cilda cruman;",
"29": "Þa sæde he hyre for þære spræce; Ga nú. se deofol of ðinre dehter gewít;",
"30": "And þa heo on hyre hus eode heo gemette þt mæden on hyre bedde licgende. & þone deofol ut-gán;",
"31": "And eft he eode of tíra gemærum & com þurh sidónem to þære galileiscan sæ betwux midde endas decapóleos.",
"32": "& hi læddon him ænne deafne & dumbne. & hine bædon þt he his hand him on sette;",
"33": "Ða nam he hine onsundran of þære menigu. & his fingras on his earan dyde & spætende his tungan onhrán;",
"34": "& on þone heofon behealdende geómrode & cwæð; Effeta. þt is on ure geþeode sy þú ontyned;",
"35": "And sona wurdon his earan geopenode. & his tungan bend wearð unslyped & he rihte spræc;",
"36": "And he bead him þt hi hit nanum men ne sædon; Soþlice swa he him swiþor bebead. swa hi swiðor bodedon.",
"37": "& þæs þe ma wundredon & cwædon; Ealle þing he wel dyde. & he dyde þt deafe gehyrdon. & dumbe spræcon;"},

"8": {
"1": "Eft on þam dagum him wæs mid micel menigu & næfdon hwæt hi æton; Þa cwæþ he to-somne geclypedum his leorning-cnihtum;",
"2": "Ic ge-miltsige þysse menegu. forþam hi þry dagas me ge-anbidiað & nabbað hwæt hi eton;",
"3": "Gif ic hí fæstende to hyra husum læte. be wege hi ge-teorigeað; Sume hi comon feorran.",
"4": "& þa &swarodan him his leorning-cnihtas; Hwanon mæg ænig man þas mid hlafum on þisum westene gefyllan;",
"5": "Þa axode he hi hu fela hlafa hæbbe ge. hi cwædon seofan;",
"6": "Ða het he sittan þa menegu ofer þa eorþan; And nam þa seofon hlafas & gode þancode. & hi bræc & sealde his leorning-cnihtum þt hi toforan him asetton. & hi swa dydon;",
"7": "And hi næfdon buton feawa fixa & he þa bletsode. & het beforan him settan.",
"8": "& hi æton & wurdon gefyllede & hi námon þt of þam brytsenum beláf. seofon wilian fulle;",
"9": "Soðlice þa ðe þar æton. wæron fif þusend & he hi þa for-lét;",
"10": "[A]nd sona he on scyp mid his leorning-cnihtum astah. & com on þa dælas dalmanuða;",
"11": "And þa ferdon ða pharisei. & ongunnon mid him smeagean & tacen of heofone sohton & his fandedon;",
"12": "Þa cw. he geomriende on his gaste. hwi secð þeos cneoris tacen; Soþlice ic eow secge ne bið þisse cneorisse tacen geseald.",
"13": "& hi þa forlætende eft on scyp astah. & ferde ofer þone muðan.",
"14": "& hi ofergeton þt hi hlafas ne namon. & hi næfdon on scype mid him buton ænne hláf.",
"15": "& he him bead & cwæð; Lociað & warniað fram pharisea & herodes hæfe;",
"16": "Þa þohton hi betwux him & cwædon; Næbbe we náne hlafas.",
"17": "þa se hælend þt wiste. he cwæð. Hwæt þence ge forþam ge hlafas nabbað. gýt ge ne oncnawað ne ne ongytað. gyt ge habbað eowre heortan geblende;",
"18": "Eagan ge habbað & ne ge-seoð. & earan. & ne gehyrað. ne gé ne þencaþ",
"19": "hwænne ic bræc fíf hlafas & twegen fixas & hu fela wyligena ge namon fulle; Hi cwædon þa twelfe;",
"20": "And hwænne seofon hlafas feower þusendum. & hu fela wyligena. brytsyna ge namon. hi sædon seofon;",
"21": "Ða sæde he him hwi ne ongyte ge gýt;",
"22": "And hi comon þa to bedzaida & hi brohton him þa ænne blindne & hine bædon þt he hine æthrine.",
"23": "& þa æthran he þæs blindan hand & lædde hine butan þa wíc. & spætte on his eagan. & his hand onasette & hine axode hwæþer he aht gesawe;",
"24": "Ða cwæð he þa ða he hine beseah. ic ge-seo men swylce treow gangende;",
"25": "Eft he asette his handa ofer his eagan & he geseah þa. & wearð ge-edniwod. swa þt he beorhtlice eall geseah;",
"26": "Ða sende he hine to his huse. & cwæð gá to þinum huse. & ðeah þu on tún gá nænegum þu hit ne sege;",
"27": "Ða eode he & his leorning-cnihtas on þt castel cesareæ philippi. & he on wege his leorning-cnihtas ahsode. Hwæt secgað men þt ic sy;",
"28": "Þa andswarodon hi. sume Iohannem þone fulluhtere. sume heliam sume sumne of þam witegum;",
"29": "Ða cwæð he hwæt secge ge þt ic sy; Þa andswarude petrus him & cwæð; Ðu eart crist.",
"30": "& ða bead he him. þt hi nænegum be him ne sædon;",
"31": "Ða ongan he hi læran þt mannes sunu gebyreð fela þinga þolian & beon aworpen fram ealdormannum. & heahsacerdum & bócerum & beon ofslegen. & æfter þrim dagum arísan.",
"32": "& spræc þa openlice. & þa nam petrus hine & ongan hine þreagean",
"33": "þa be-wende he hine & cidde petre & cwæð; Gá on-bæc satanas forþam þu nast þa ðing þe synd godes. ac þa ðing þe synd manna;",
"34": "Þa cwæð he togædere geclypedre menegu mid his leorning-cnihtum; Gif hwa wyle me fyligean wið-sace hine sylfne & nime his cwylminge & folgige mé;",
"35": "Se ðe wyle his sawle hale gedon se hi for-spilð; Se ðe for-spilð his sawle for me. & for þam godspelle se hi ge-hælð;",
"36": "Hwæt fremað men ðeah he eallne middan-eard gestryne. & do his sawle forwyrd.",
"37": "oþþe hwylc gewryxl sylð se man for his sawle;",
"38": "Soðlice se þe me for-syhð & mine word on þisre unriht-hæmedan & synfulran cneorisse. ðone mannes sunu for-syhþ; Ðonne he cymð on his fæder wuldre mid halgum englum;"},

"9": {
"1": "Þa sæde he him soðlice ic secge eow. þt sume synt her wuniende. þe deað ne onbyrigeað. ær hi ge-seon godes rice on mægne cuman;",
"2": "Ða æfter syx dagum nam se hælend petrum & iacobum & iohannem & lædde hi sylfe onsundran on sumne heahne munt & wearð beforan him ofer-hiwud.",
"3": "& his reaf wurdon glitiniende swa hwite swa snaw. swa nan fullere ofer eorðan ne mæg swa hwite gedón;",
"4": "Þa æt-ywde him helias mid moyse & to him spræcon;",
"5": "Ða andswarode petrus him & cwæð. lareow gód is þt we her beon & uton wyrcan her þreo eardung-stowa. þé ane. & moyse ane. & helie ane;",
"6": "Soðlice he nyste hwæt he cwæð. he wæs afæred mid ege;",
"7": "And seo lyft hi ofer-sceadewude. & stefn com of þære lyfte & cwæð. þes is min leofesta sunu gehyrað hine;",
"8": "And sona ða hi besawon hí nanne hi mid him ne gesawon buton þone hælend sylfne mid him;",
"9": "And þa hi of þam munte astigon he bead him þt hi nanum ne sædon þa ðing þe hi ge-sawon buton þonne mannes sunu of deaðe aríse;",
"10": "Hi þa ðæt word geheoldon betwux him & smeadon hwæt þt wære þonne he of deaðe arise;",
"11": "And hi hine ahsodon þa. hwæt secgað pharisei & þa boceras. þt gebyrað ærest helias cume;",
"12": "Ða sæde he him andswariende; Helias ealle þing ge-edniwað þonne he cymð. swa be mannes suna awriten is þt hé fela ðolige & si ofer-hogod;",
"13": "Ac ic secge eow þt helias com & hi dydon him swa hwæt swa hi woldon swa be him awriten is;",
"14": "And þa he com to his leorning-cnihtum he ge-seah mycele menegu abutan hi & boceras mid him sprecende.",
"15": "& sona eall folc þæne hælend geseonde wearð afæryd & forht. & hine gretende him to urnon;",
"16": "Þa ahsode he hi. hwæt smeage ge betwux eow;",
"17": "Him &swarode án of þære menigu; Láreow. ic brohte minne sunu dumbne gast hæbbende",
"18": "se swa hwær swa he hine gelæcð forgnit hine. & toðum gristbitað & for-scrincþ. & ic sæde þinum leorning-cnihtum þt hi hine ut adrifon & hi ne mihton;",
"19": "Ða &swarode he him. eala ungeleaffulle cneorys swa lange swa ic mid eow beo. swa lange ic eow þolige; Bringað hine to me.",
"20": "þa brohton hi hine. & þa he hine geseah sona se gást hine gedrefde & on eorðan for-gnyden fæmende he tearflode;",
"21": "And þa ahsode he his fæder. hu lang tid is syððan him þis gebyrede; Þa cwæð he of cildhade.",
"22": "he hine gelómlice on fyr & on wæter sende þt he hine for-spilde; Ac gif þu hwæt miht gefylst us ure gemiltsud;",
"23": "Ða cwæð se hælend. gif þu gelyfan miht ealle þing synd gelyfedum mihtlice;",
"24": "Ða sona hrymde þæs cildes fæder. & wepende cwæð; Drihten ic gelyfe. gefylst minre ungeleaffulnysse;",
"25": "And þa se hælend geseah þa to-yrnendan menegu. he bebead þam unclænan gaste þus cweðende; Eala deafa & dumba gast. ic beode þe gá of him & ne ga þu leng on hine;",
"26": "He ða hrymende & hine swyþe slitende eode of him. & he wæs swylce he dead wære; Swa þt manega cwædon soðlice he is dead;",
"27": "Þa nam se hælend his hand & hine up ahóf & he aras þa;",
"28": "And þa he into þam huse eode his leorning-cnihtas hine digollice ahsodon. hwí ne mihton we hine ut adrifan;",
"29": "Ða sæde he þis cynn ne mæg of nanum men út gán buton þurh gebedu & on fæstene;",
"30": "Þa hi þanon ferdon hi forbugon galileam. he nolde þt hit ænig man wiste;",
"31": "Soðlice he lærde his leorning-cnihtas & sæde; Soþlice mannes sunu bið geseald on synfulra handa þt hi hine ofslean. & ofslagen þam ðriddan dæge he arist;",
"32": "Ða nyston hi þt word. & hi adredon hine ahsiende;",
"33": "Þa comon hi to capharnaum & þa hi æt ham wæron he ahsode hí hwæt smeade gé be wege.",
"34": "& hi suwodon; Witodlice hi on wege smeadon hwylc hyra yldost wære;",
"35": "Þa he sæt he clypode hi twelfe & sæde him. gif eower hwylc wyle beon fyrmest. beo se eaðmodust & eower ealra þen;",
"36": "Þa nam he anne cnapan & ge-sette on hyra middele. þa he hine beclypte he sæde him;",
"37": "Swa hwylc swa anne of þus geradum cnapum on minum naman onfehð. se onfehþ me; And se þe me onfehð he ne onfehþ me. ac þone þe me sende;",
"38": "Ða &swarode iohannes & cwæð; Lareow sumne we ge-sawon on þinum naman deofol-seocnessa ut adrifende. se ne fyligð us. & we him forbudon;",
"39": "Þa cwæð he ne for-beode ge him nis nán þe on minum naman mægen wyrce & mæge raðe be me yfele specan;",
"40": "Se þe nis agen eow se is for eow;",
"41": "Soðlice se ðe sylð drinc eow calic fulne wæteres on minum naman forþam ge cristes synt. ic eow soþ secge. ne forlyst he his mede;",
"42": "And swa hwa swa ge-drefð ænne of þyssum lytlingum on me gelyfendum. betere him wære þt án cweorn-stan wære to his swuran gecnyt & wære on sæ beworpen;",
"43": "And gif þin hand þe swicað ceorf hi of; Betere þe is þt þú wanhal to life ga. þonne þu twa handa hæbbe & fare on helle. & on unacwencedlic fýr",
"44": "þar hyra wyrm ne swylt & fyr ne bið acwenced;",
"45": "And gif ðin fot swicað þe ceorf hine of. betere þe is þt þu healt gá. on écé lif þonne þu hæbbe twegen fet & si aworpen on helle un-acwencedlices fyres.",
"46": "þar hyra wyrm ne swylt ne fyr ne bið adwæsced;",
"47": "Gif þin eage þe swicað weorp hit út. betere þe is mid anum eagan gán on godes ríce þonne twa eagan hæbbende sy aworpen on helle fyr.",
"48": "þar hyra wyrm ne swylt. ne fyr ne bið acwenced;",
"49": "Soðlice ælc man bið mid fyre ge-sylt & ælc offrung bið mid sealte gesylt;",
"50": "Gód is sealt gif þt sealt unsealt biþ on þam þe ge hit syltað; Habbað sealt on eow. & habbað sibbe betwux eow;"},

"10": {
"1": "And þanon he com on iudeisce endas of iordane; Þa comon eft menigu to him & swa swa he ge-wunode he hi lærde eft sona;",
"2": "Ða ge-nealæhton him pharisei & hine axodon. hwæþer alyfð ænegum men his wif forlætan. his þus fandigende;",
"3": "Þa &swarode he him. hwæt bead moyses eow.",
"4": "hi sædon; Moyses lyfde þt man write hiw-gedales boc. & hi for-léte;",
"5": "Ða cwæð se hælend. for eower heortan heardnesse he eow wrat þis bebod;",
"6": "Fram fruman gesceafte god hi ge-worhte wæpned-man & wimman",
"7": "& cwæð. for þam se mann forlæt his fæder & modor & hine his wife geþeot.",
"8": "& beoð twegen on anum flæsce. witodlice ne synt na twegen ac án flæsc;",
"9": "Þæt god ge-samnode ne syndrige þt nán man;",
"10": "And eft innan huse his leorning-cnihtas hine be þam ylcan ahsodon;",
"11": "Ða cwæð he swa hwylc mann swa his wif forlæt & oþer nimð unriht-hæmed he wyrcð. þurh hi;",
"12": "And gif þt wif hire were forlæt & oþerne nimð. heo unriht-hæmð;",
"13": "And hi brohton him hyra lytlingas þt he hi æthrine. þa ciddon his leorning-cnihtas þam ðe hi brohton;",
"14": "Þa se hælend hi ge-seah unwurðlice he hit for-bead & sæde him; Lætaþ þa lytlingas to me cuman & ne for-beode ge him; Soðlice swylcera is heofona ríce;",
"15": "Soþlice ic secge eow swa hwylc swa godes rice ne onfehð swa lytling ne mæg he [on] þt;",
"16": "Ða beclypte he hí. & his handa ofer hi settende bletsode hi;",
"17": "And þa he on wege eode sum him to arn & gebigedum cneowe toforan him cwæð. & bæd hine; La góda lareow hwæt do ic. þt ic éce lif age;",
"18": "Þa cwæð se hælend. hwi segst þu me godne. nis nan mann god buton god ana;",
"19": "Canst þu ða bebodu. ne unriht-hæm þu. ne slyh þu. ne stel þu. ne sege þu lease gewitnesse. facen ne do ðu. wurða þinne fæder & þine modor;",
"20": "Ða &swarode hé goda lareow. eall ðis ic geheold of minre geoguðe;",
"21": "Se hælend hine þa behealdende lufode & sæde him; An þing þe is wana gesyle eall þt ðu age & syle hit þearfum. þonne hæfst þu gold-hord on heofonum & cum & folga me;",
"22": "And for þam worde he wæs ge-unret & ferde gnornigende for þam he hæfde mycele æhta;",
"23": "Þa cwæð se hælend to his leorning-cnihton hine beseonde. swyþe earfoðlice on godes rice gað þa þe feoh habbað;",
"24": "Ða forhtodon his leorning-cnihtas be his wordum; Eft se hælend him &swariende cwæð. eala cild swyðe earfoðlice þa ðe on heora feo getruwigeað gað on godes rice;",
"25": "Eaþere ys olfende to farenne þurh nædle þyrel þonne se rica & se welega on godes rice gá;",
"26": "Hi þæs ðe ma betwux him wundredon & cwædon & hwa mæg beon hal",
"27": "þa beheold se hælend hi & cwæð; Mid mannum hit is uneaþelic ac na mid gode; Ealle þing mid gode synt eaðelice;",
"28": "Þa ongan petrus cweþan; Witodlice we ealle þing for-leton & folgodon þe;",
"29": "Ða &swarode him se hælend. nis nan þe his hus for-læt. oððe gebroþru. oþþe geswustra. oððe fæder. oþþe modor. oððe bearn. oþþe æceras for me & for þam god-spelle",
"30": "þe hund-feald ne onfó. nu on þisse tide. hus & broðru & swustru. fæder & modor. & bearn. & æceras. mid ehtnessum & on toweardre worulde éce lif;",
"31": "Manega fyrmeste beoð ytemeste & ytemeste fyrmyste;",
"32": "Soþlice hi ferdon on wege to hierusalem & se hælend him beforan eode & hi adredon him hine & him fyligdon. & eft he nam hi twelfe & ongan him secgan þa ðing þe him towearde wæron",
"33": "þt we nu astigað to hierusalem & mannes sunu bið ge-seald sacerda ealdrum & bocerum & ealdrum. & hi hine deaðe genyþeriað. & hi hine þeodum syllað.",
"34": "& hi hine bysmriað & hi him on spætað & hine swingað & of-sleað hine. & he arist on þam þriddan dæge;",
"35": "Him þa ge-nealæhton to. iacobus. & Iohannes Zebedeis suna & cwædon; Lareow. we wyllað þt þu us do swa hwæt swa we biddað;",
"36": "Þa cwæð he hwæt wylle gyt þt ic inc dó.",
"37": "þa cwædon hi; Syle unc þt wyt sitton on þinon wuldre. án on þine swyðran healfe & oþer on þine wynstran;",
"38": "Ða cwæð se hælend. gyt nyton hwæt gyt biddað; Mage gyt drincan þone calic. þe ic drince & beon gefullod on þam fulluhte þe ic beo gefullod;",
"39": "Þa cwædon hi wyt magon; Ða cwæð se hælend gyt drincað þone calic þe ic drince. gyt beoð gefullode þam fulluhte ðe ic beo gefullod;",
"40": "Soðlice nis hit na min inc to syllene þt gyt sitton on mine swyðran healfe oððe on þa wynstran. ac þam þe hit ge-gearwod ys;",
"41": "Þa ge-bulgon þa týne hi be Iacobe & Iohanne;",
"42": "Ða clypode se hælend hi & cw; Wite ge þt þa ðe on þeodum ealdor-scype habbað þt hyra ealdras anweald ofer hi habbað;",
"43": "Soðlice on eow hit nis swa. ac swa hwylc swa wyle mid eow yldest beon se byð eower þen.",
"44": "& se ðe wyle on eow fyrmest beon. se byþ ealra þeow;",
"45": "Soðlice ne com mannes sunu. þt him man þenode. ac þt he þenode. & his sawle sealde for manegra alysednysse;",
"46": "Þa comon hi to gericho & he ferde fram gericho & his leorning-cnihtas & mycel menegu. timeus sunu bartimeus sæt blind wið þone weg wædla.",
"47": "þa he ge-hyrde þt. hit wæs se nazareniscea hælend. he on-gan þa clypian & cweðan; Hælend. dauides sunu gemiltsa me;",
"48": "Þa budon him manega þt he suwode. he clypode þa þæs ðe ma miltsa me dauides sunu;",
"49": "Ða æt-stod se hælend & het hine clypian; Þa sædon hi þam blindan. beo geheortra & arís. se hælend þe clypað;",
"50": "He þa awearp his reaf & forð ræsde. & to him com;",
"51": "Ða cwæð se hælend. hwæt wylt þu þt ic þe dó; þa cwæð he. lareow þt ic geseo.",
"52": "þa cwæð se hælend to him. gá þin geleafa þe halne gedyde. & he sona geseah & him fyligde on wege;"},

"11": {
"1": "Ða he ge-nealæhte hierusalem & bethanía to oliuetes dune. he sende his twegen leorning-cnihtas.",
"2": "& cwæð to him. faraþ to þam castele þe [ongean] ínc ys and gyt þar sona gemetað assan folan getigedne. ofer þæne nán man gyt ne sæt. untigeað hine & to me gelædað;",
"3": "And gyf hwa to ínc hwæt cwyð. secgað þt drihten hæfð his neode. & he hine sona hider læt.",
"4": "& þa hi ut-ferdon hi gemetton þone folan ute on twycenan beforan dura. getigedne. þa untigdon hi hine",
"5": "& sume þe þar stodon þus sædon him; Hwæt do gyt þone folan untigende.",
"6": "þa cwædon hi; Swa se hælend unc bead & hi leton hi þa;",
"7": "Ða læddon hi þone folan to þam hælende & hi hyra reaf on á-ledon & he on sæt;",
"8": "Manega hyra reaf on þone weg strehton. sume þa boceras of þam treowum heowon & streowodon on þone weg.",
"9": "& þa ðe beforan eodon & þa ðe æfter folgodon cwædon þus osanná sy gebletsod se þe com on drihtnes naman;",
"10": "Si gebletsod þt ríce þe com ures fæder dauides osanná on heahnessum;",
"11": "And he eode þa on hierosolima templ & ealle þing he be-sceawode; Þa æfen tima wæs he ferde to bethaníam mid his twelf leorning-cnihtum;",
"12": "And oþrum dæge þa hi ferdon fram bethanía hine hingrode;",
"13": "Ða he feorran geseah an fic-treow þe leaf hæfde he cóm & sohte hwæþer he þar on aht funde þa he him to cóm ne funde he þar buton leaf áne; Soðlice hit wæs þæs fic-treowes tima;",
"14": "Þa cw he. heonon forð on ecnesse ne ete ænig mann wæstm of þe. & his leorning-cnihtas þæt gehyrdon;",
"15": "Þa comon hi eft to hierusalem & þa he on þt templ eode he ongann drifan of þam temple syllende & bicgende. & mynetera þrocu. & heah-setlu þe þa culfran cypton he to bræc.",
"16": "& hé ne geþafode þt ænig man ænig fæt ðurh þt templ bære",
"17": "& he þa lærende ðus cw to him; Nis hit awriten þt min hus fram eallum þeodum bið ge-nemned gebed-hus. soðlice ge dydon þt to sceaðena scræfe;",
"18": "Ða þæra sacerda ealdras & þa boceras ðis ge-hyrdon. hi þohton hu hi hine for-spildon. þeh hi him adredon hine. forðam eall seo menigu wundrode be his láre;",
"19": "And þa hit æfen wæs he eode of þære ceastre;",
"20": "On merigen þa hi ferdon. hi gesawon þt fic-treow for-scruncen of þam wyrt-ruman;",
"21": "Þa cwæð petrus. lareow. loca hu for-scranc þt fic-treow þe ðu wyrigdest;",
"22": "Ða cwæð se hælend him and-swarigende. habbað godes truwan.",
"23": "ic secge eow to soðe. swa hwylc swa cwyþ to ðisum munte. si þu afyrred & on sæ aworpen. & on his heortan ne twynað ac gelyfð swa hwæt swa he cwyð gewurðe þis. þt gewyrð;",
"24": "Forþam ic eow secge swa hwæt swa ge gyrnende biddað gelyfað þt ge hit onfoð. & hit eow be-cymð;",
"25": "And þonne ge standað eow to gebiddenne. forgifaþ gif gé hwæt agén ænigne habbað. þt eow eower synna forgyfe eower heofonlica fæder se ðe on heofonum ys;",
"26": "Gif ge ne forgyfað ne eow. eower synna ne forgyfð eower heofonlica fæder;",
"27": "Ða com he eft to hierusalem. & þa he on þam temple eode him to genealæhton þa heah-sacerdos & boceras & ealdras",
"28": "& þus cwædon; On hwylcum anwealde dest þu ðas þing. & hwa sealde þe ðisne anweald þt þu ðis dó;",
"29": "Þa cwæð se hælend & ic ahsige eow ánre spræce &swariað me. & ic secge eow þonne on hwylcum anwealde ic þis dó;",
"30": "Hweðer wæs iohannes fulluht þe of heofone. þe of mannum &swariað me;",
"31": "Ða þohton hi & cwædon betweox him. gif we secgað of heofone. he segð ús hwi ne ge-lyfde ge him.",
"32": "gif we secgað of mannum. we on-drædaþ þis folc. ealle hi hæfdon iohannem þt he wære soðlice witega;",
"33": "Þa &swaredon hi þam hælende & cwædon we nyton; Ða cwæð se hælend. ne ic eow ne secge on hwylcum anwealde ic þas þing dó;"},

"12": 
{
"1": "Ða ongan he him big-spell reccan. sum mann him plantode wingeard & be-tynde hine. & dealf anne seað & getimbrode ænne stypel & gesette hine mid eorð-tilium. & ferde on elþeodignysse;",
"2": "Þa sende he to þam tiligum his þeow on tide þt he þæs wíngeardes wæstm onfenge;",
"3": "Ða swungon hi þæne. & forleton hine idel-hende;",
"4": "And eft he him sende oðerne þeow. & hi þone on heafde gewundodon & mid teonum geswencton;",
"5": "And eft he him sumne sende & hi þæne of-slogon. & manega oþre. sume hi beoton. sume hi of-slogon;",
"6": "Þa hæfde he þa gyt ænne leofostne sunu. þa sende he æt nehstan him þæne & cwæð; Witodlice minne sunu hig for-wandiað;",
"7": "Ða cwædon þa tilian him be-tweonan; Her is se yrfe-numa. uton ofslean hine. þonne bið ure seo yrfeweardnes;",
"8": "Hi þa ofslogon hine. & wurpon wið-utan þone wín-geard;",
"9": "Hwæt deð þæs wíngeardes hlaford. he cymð & fordeð þa tiligean. & sylð oþron þone wíngeard;",
"10": "Ne rædde ge þis gewrit. Se stán þe þa wyrhtan awurpon þes ys geworden on þære hyrnan heafod.",
"11": "þis ys fram drihtne geworden & hit is wundorlic on uron eagum;",
"12": "Þa smeadon hi þt hi gefengon hine & hi ondredon þa menigu. hi on-cneowon þa þt he þis bigspell to him sæde hi ferdon þa & hine forleton;",
"13": "Þa sendon hi to him sume of phariseum & herodianum þt hi befengon hine on his worde;",
"14": "Ða comon hi & þus mid facne cwædon; Lareow. we witon þt þu eart soðfæst & þu ne recst be ænegum menn. ne besceawast þu manna ansyne. ac þu godes weg lærst on soð-fæstnysse; Alyfð gaful to syllanne þam casere",
"15": "hwæðer þe we ne syllað; Þa cwæð he & heora lot-wrenc-ceaste wiste. hwi fandige mín bringað mé þone pening þt ic hine geseo.",
"16": "þa brohton hi him þa sæde he him; Hwæs is þeos anlicnys & þis ge-writ. hi cwædon. ðæs caseres;",
"17": "Ða cwæð se hælend to him. agyfað þam casere þa ðing þe þæs caseres synd. & gode þa ðe godes synd. þa wundrodon hi be þam;",
"18": "Þa comon him to sad[u]cei þa secgað þt ærist ne sý & hine ahsodon & þus cwædon;",
"19": "Lareow. moyses us wrat. gif hwæs broðor dead bið & læfð his wíf & næfð nan bearn. þt his broðor nime his wíf & his broðor sæd wecce;",
"20": "Eornostlice seofon gebroþru wæron. & se æresta nam wíf & wearð dead ná læfedum sæde;",
"21": "And þa nam se oðer hi. & wearð dead. ne sé sæd ne læfde; Gelice se þridda",
"22": "& ealle seofon hi hæfdon & sæd ne læfdon; Ealra æftemest þa forð-ferde þt wif;",
"23": "On þam æriste. hwylces þara seofona bið þt wíf. hi ealle hi hæfdon;",
"24": "Þa &swarode him se hælend hu ne dweligað ge. forþam þe ge nyton þa halgan gewritu ne godes mægen;",
"25": "Soðlice þonne hi of deaðe arisaþ. ne wifiaþ hi. ne ne gyftigeað. ac hi synt swylce godes englas on heofonum;",
"26": "Be þam deadum þt hi aríson. ne rædde ge on moyses bec hu god to him cwæþ. ofer þone gorst-beam; Ic eom abrahames god. & isááces god. & iacobes god.",
"27": "nis god deadra ac he hys lybbendra; Soðlice swyþe ge dweligeað:",
"28": "Ða genealæhte him án of þam bocerum þe he gehyrde hi smeagende & geseah þt he him wel andswarode. & ahsode hine hwæt wære ealra beboda mæst;",
"29": "Þa &swarode he him. þt is þt mæste bebod. ealra israhel gehyr urne drihten god. he is [an god]",
"30": "and lufa þinne drihten god. of ealre þinre heortan. & of ealre þinre sawle. eallum þinum móde. & of eallum þinum mægene. þt is þt fyrmeste bebod;",
"31": "Soðlice is oðer þissum gelic; lufa þinne nehstan swa þe sylfne. nys oðer máre bebod;",
"32": "Ða cwæþ se bocere. lareow. well þú on soþe cwæde. þt an god is. & nis oðer butan him",
"33": "& ðæt he si gelufod of ealre heortan. & of eallum andgyte. & of ealre sawle. & of ealre strengðe. & lufigean his nehstan swa hine sylfne. þæt is mare eallum on-sægdnyssum & offrungum;",
"34": "Ða se hælend geseah þt he him wislice andwyrde he sæde him ne art þu feorr fram godes ríce. & hine ne dorste nan mann ahsian;",
"35": "Ða cwæþ se hælend on þam temple lærende; Hu secgað þa boceras þt crist sy dauides sunu;",
"36": "Dauid sylf cwæþ to þam halgan gaste. drihten cwæþ to minum drihtne. síte on mine swyðran healfe. oð ic þíne fýnd asette to fot-sceamole þinra fóta;",
"37": "Dauid sylf nemde hine drihten. & hwanon is he his sunu; And mycel menegu hine luflice gehyrde.",
"38": "þa sæde he him on his lare; Warniað fram bocerum. þa wyllað on ge-gyrlum gán & beon on straætum grete.",
"39": "& on fyrmostum lareow-setlum. sittan on ge-samnungum & þa fyrmestan setl on ge-beor-scipum",
"40": "þa ðe wudewena hus for-swelgað mid heora langsuman gebede. þa onfoð lengestne dóm;",
"41": "Ða sæt se hælend ongén þone toll-sceamol & geseah hu þt folc hyra feoh. torfude on þone toll-sceamul. & manega welige torfudon fela;",
"42": "Þa com án earm wuduwe. and wearp twegen feorð-lingas;",
"43": "Ða clypode he his leorning cnihtas & sæde him; Soðlice ic eow secge. þt þeos earme wuduwe eallinga mæst sealde þara þe on toll-sceamul sealdon;",
"44": "Ealle sendon of þam þe hi genoh hæfdon; Soðlice þeos of hyre yrmþe eall þt heo hæfde sealde ealle hyre and-lyfene;"},

"13": 
{
"1": "Ða he of þam temple eode þa cwæð án of his leorning-cnihtum to him. lareow loca hwylce stanas her synt & hwylce getimbrunga þisses temples;",
"2": "Þa cwæð se hælend. ne ge-seoge ealle þas mycelan getimbrunga. ne bið her læfed stan ofer stan þe ne beo toworpen;",
"3": "Þa hi sæton on oliuetes dúne ongen þt tempel synderlice hine petrus & iacobus. & iohannes. & andreas. ahsodon;",
"4": "Sege us hwænne þas þing ge-wurdon & hwylc tacen bið þænne ealle þas ðing onginnað beon ge-endud;",
"5": "Þa ongan se hælend him &swarigende to cweðan; Warniað þt eow nan mann ne be-swice;",
"6": "Soþlice manega cumað on minum naman. & cweþað. ic eom crist & beswicað manega",
"7": "& þonne ge gehyrað gefeohtu. & gefeohta hlisan. ne ondræde ge eow. hit gebyrað þt hit gebelimpe. ac þonne gyt nis ende;",
"8": "Soðlice þeod arist ágén þeode. & rice ongén rice & beoð eorþan styrunga geond stowa & hungor. þis synd sara angin;",
"9": "Warniað eow sylfe. hi syllað eow on geþeahte & swingað on gesamnungum. & ge standað beforan demum & cyningum. for minum naman him on ge-witnesse",
"10": "& on ealle þeoda; Ærest ge-byrað beon þt godspel gebodud.",
"11": "& þonne hi syllende eow læþað ne fore-smeage ge hwæt ge specan. ac specað þt eow on þære tide ge-seald bið; Ne synd ge na specende ac se halga gast;",
"12": "Soðlice se broðor þone broþor to deaðe sylð. & se fæder his sunu. & þa bearn arisað agén hyra magas. & mid deaðe hi ge-wæceað.",
"13": "& ge beoð eallum on hatunge for minum naman; Soðlice se bið hal se þe oð ende þurh-wunað;",
"14": "Ðonne ge ge-seoð þære toworpednysse asceonunge standan þar heo ne sceal. þonne ongyte se þe ræt. fleon þonne on muntas þa ðe synt on iudea",
"15": "& se ðe is ofer þécene ne stige he on his hús ne he in ne ga þt he aht on his huse nime.",
"16": "& se ðe bið on æcere ne cyrre he ongean þt he his reaf nime;",
"17": "Wá cenne[n]dum on þam dagum.",
"18": "biddað þt ðis on wintra ne ge-wurðe;",
"19": "Soþlice on þam dagum beoð swylce gedrefednessa. swylce ne ge-wurdon. of frymmðe þære gesceafte þe god gesceop. oð nu. ne na ne gewurþað.",
"20": "And gif drihten þas dagas ne gescyrte. nan flæsc ne wurde hal. ac for þam gecorenum þe he ge-ceas he ge-scyrte þa dagas;",
"21": "And gif eow hwylc segð witodlice her is crist. witodlice þær he is. ne gelyfe ge;",
"22": "Soðlice lease cristas. & lease witegan arisað. & wyrcað fore-beacnu. to beswicanne eac gif hit beon mæg þa ge-corenan;",
"23": "Warniað eow. nu ealle þing. þe ic eow fore-sæde.",
"24": "ac on þam dagum æfter þære geswencednysse. bið sunne aþeostrod. & se mona his beorhtnesse ne sylð",
"25": "& heofones steorran beoð feallende. & beoð astyrode þa megenu þe on heofonum synt;",
"26": "Ðonne geseoð hi mannes sunu cumendne on ge-nipum mid mycelum mægene & wuldre;",
"27": "þonne sent he his englas & hi gaderiað his gecorenan of feower windum of eorþan heanesse oþ heofones heahnesse;",
"28": "Leorniað an bigspell be þam fic-treowe. þonne his twi bið mearu. & leaf beoð acennede. ge witon þt sumor is gehende.",
"29": "& wite ge þonne ge þas ðing geseoð þt he is dura gehende;",
"30": "Soðlice ic eow secge þt þeos cneores ne gewit ærþam ealle þas ðing gewurðon.",
"31": "heofon & eorðe gewitað. witodlice mine word ne ge-witað;",
"32": "Be þam dæge & þære tide nan mann nat. ne englas on heofone ne mannes sunu buton fæder ána;",
"33": "Warniað & waciað & gebiddaþ eow. ge nyton hwænne seo tid ys;",
"34": "Swa se man ælþeodilice ferde forlet his hus & sealde his þeowum þæne anwald gehwylces weorces. & beode þam dure-wearde þt he wacige;",
"35": "Eornostlice wacigeað ge nyton hwænne þæs huses hlaford cymð; þe on æfen þe on midre nihte. þe on hancrede. þe on mergen.",
"36": "þe læs he eow slapende geméte þonne he færinga cymð;",
"37": "Soðlice þt ic eow secge eallum ic hit secge waciað."},

"14": {
"1": "Soþlice þa æfter twam dagum wæron eastron & þa sohton þa heah-sacerdas & þa boceras hu hi hine mid facne namon & of-slogon;",
"2": "Ða cwædon hi næs na on freols-dæge þe læs þæs folces gehlyd wurde;",
"3": "And þa se hælend wæs on bethanía on simones húse anes hreoflan & þar sæt; Þa com an wíf & hæfde hyre sealf-box deorwyrþes nardes. & tobrocenum sealf-boxe. ofer his heafod agét;",
"4": "Sume hit unwurðlice forbæron. & betwux him sylfum cwædon; For hwi wæs þisse sealfe forspillednes geworden.",
"5": "þeos sealf mihte beon geseald to þrim hund penegum. & beon þearfum geseald. & yrsydon agén hi;",
"6": "Ða cwæð se hælend. lætað hi hwi synt ge hire grame. gód weorc heo on me worhte;",
"7": "Soðlice symble ge habbað þearfan mid eow. & þonne ge wyllað ge magon him teala dón. me ge symble nabbað;",
"8": "Þeos sealde þt heo hæfde. heo com to smyrianne minne lic-haman on byrgene;",
"9": "Soðlice ic eow secge swa hwar swa þis godspell gebodad bið. on eallum middan-earde bið gebodod þt heo þis on his gemynde dyde;",
"10": "Ða iudas scarioth þt is wiþersaca. án of þam twelfum. ferde to þam heah-sacerdum þt he hine belæwde;",
"11": "Þa hi þis gehyrdon hi fahnodon & beheton him feoh to syllanne. & he smeade hu he hine digellice sealde;",
"12": "And þam forman dæge azimorum þa hi eastron offrodon. his leorning-cnihtas him sædon. hwyder wylt þu þt we faron & gegearwian þe. þt ðu eastron ete;",
"13": "Ða sende he twegen of his leorning-cnihtum & sæde him; Gað on þa ceastre & inc agén yrnð. sum man berende sume wæter-flaxan; Folgiað him;",
"14": "& swa hwyder swa he inn-gæð secgað þæs huses hlaforde; Vre lareow secgð. hwar is min gyst-hús. & min gereord. hwar ete is eastron. mid minum leorning-cnihtum;",
"15": "And he inc geswutelað mycele healle gedæfte. & ge-ge-earwiað us þara;",
"16": "Þa ferdon his leorning cnihtas & comon on þa ceastre. & fundon hit eall swa he sæde. & ge-gearwodon þa eastron;",
"17": "Soðlice þa æfen cóm. him twelfum mid him",
"18": "sittendum & etendum sæde se hælend; Soðlice ic eow secge þt eower án þe mid me yt gesylð me;",
"19": "Ða ongunnon hi beon dreorige & betwux him cweðan. cwyst þu eom ic hit;",
"20": "Þa sæde he him. án of eow twelfum me sylð. se ðe his hand on disce mid me dypð;",
"21": "And witodlice mannes sunu gæð swa be him awriten is. wá þam menn þurh þone þe mannes sunu geseald bið. betere him wære þt se mann acenned nære;",
"22": "Him þa etendum afeng se hælend hlaf & hine bletsiende bræc. & sealde him & þus cwæð. nimað. ðis ys min lichama.",
"23": "& onfeng calice. & gode þancas dyde & sealde him. & ealle him ofdruncon;",
"24": "Þa sæde he him. ðis ys min blod þære niwan cyðnesse þt bið for manegum agoten;",
"25": "Soðlice ic eow secge þt ic heonon forð ne drince of þyses wingeardes cynne. oð þone dæg þonne ic hine niwne drince on godes rice;",
"26": "And gecwedenum lofe hi ferdon on ele-bergena munt;",
"27": "Ða cwæð se hælend. ealle ge beoð geuntreowsode on þisse nihte. forþam þe hit awriten is. ic slea þæne hyrde & beon þa scép to-dræfede;",
"28": "Ac æfter þam þe ic arise. ic cume beforan eow on galileam;",
"29": "Þa sæde petrus him. þeah ðe ealle swicion ne swicige ic þe ná",
"30": "Þa cwæð se hælend; Soþlice ic þe secge. þt ðu on þisse nihte ær hana tuwa crawe. þriwa wið-sæcst mín.",
"31": "& he þæs ðe mare spræc. & þeah me ge-byrige mid þe to sweltene. ne æt-sace ic þin. & swa hi cwædon ealle;",
"32": "Þa comon hi to anum tune þæs nama wæs gezemani. & he cwæð to his leorning-cnihton; Sittað her oð þt ic me gebidde;",
"33": "And he nam þa mid him petrum & iacobum & iohannem. þa ongan he forhtian & sargian",
"34": "& sæde him; Unrót is min sawl oð deað. gebidað her & waciað;",
"35": "Ða he lyt-hwon forð-stóp he astrehte hine ofer þa eorðan. & he bæd. gif hit beon mihte þt he on þære tide fram him gewite;",
"36": "And þa cwæð he. abba. þt is fæder on ure geþeode. ealle þing þe synt mihtiglice. afyrr þysne calic fram me ac na þt ic wylle ac þt þu;",
"37": "Þa com he & funde hi slæpende. & cwæð to petre; Simon. slæpst þu. ne mihtest ðu áne tide wacian.",
"38": "waciað & gebiddað þt ge on costnunge ne gán. witodlice se gast is gearu. ac þt flæsc is untrum;",
"39": "And eft he ge-bæd þa ylcan spræce.",
"40": "& þa he hine eft agén bewende. he funde hí slæpende. hyra eagan wæron gehefegode & hi nyston hwæt hi him &swaredon;",
"41": "Ða com he þriddan siðe & sæde him. slapað nú & restað genoh hit ys. tíma ys cumen nu is mannes sunu geseald on synfulra handa;",
"42": "Arísaþ. uton gan. nu is gehende se ðe me sylð;",
"43": "Him þa ða gyt sprecendum com íudas scarioth. þt ys wiþersaca. án of þam twelfum. & mid him mycel menegeo mid swurdum & mid sahlum. fram heah-sacerdum. bocerum & ealdrum;",
"44": "Soðlice his læwa him tacen sealde & þus cwæð; Swa hwylcne swa ic cysse he hit is. nimað & lædað hine wærlice.",
"45": "& sona swa he com he ge-nealæhte him to & cw. lareow. & cyste hine.",
"46": "& hi hyra handa on hine wurpon. & namon hine;",
"47": "Soðlice án of þam þe ðar embe-uton stodon his swurde abræd & sloh þæs sacerdes þeow. & his eare of acearf;",
"48": "Þa cwæð se hælend him &swariende; Swa swa to anum sceaðan ge ferdon mid swurdon & treowum me gefón.",
"49": "þonne ic dæghwamlice mid eow wæs on temple lærende & ge me ne namon. ac þt þa gewritu syn gefyllede;",
"50": "Ða forleton his leorning-cnihtas ealle hine & flugon;",
"51": "Sum iungling him fyligde mid anre scytan bewæfed nacod & hi namon hine;",
"52": "Ða aworpenre þære scytan nacod he him fram fleah;",
"53": "And hi læddon þæne hælend to þam heah-sacerde. & comon ealle sacerdas. & boceras & ealdras togædere;",
"54": "Petrus him fyligde feorran oþ ðæs heah-sacerdes cafertún & he sæt mid þam ðenum & wyrmde hine æt þam fyre;",
"55": "Þa heah-sacerdas sohton & eall geþeaht. tale agén þone hælend. þt hi hine to deaðe sealdon & hi ne fundon;",
"56": "Manega sædon lease gecyðnysse agén hine. & þa cyðnessa næron þæslice;",
"57": "Ða arison sume & sædon lease cyðnesse agén hine & þus sædon;",
"58": "Soðes we ge-hyrdon hine secgan. ic to-wurpe þis hand-worhte tempel & æfter þrim dagum ic oðer unhand-worht ge-timbrie;",
"59": "& hyra cyþnys næs þæs-lic;",
"60": "Þa aras sum heah-sacerd on hyra midlene & ahsode þæne hælend. ne andswarast þu nan ðing. agén þt þas þe onwurpað;",
"61": "he suwode & naht ne &swarode; Eft hine axode se heah-sacerd. eart þu crist þæs gebletsodan godes sunu;",
"62": "Ða sæde se hælend. ic eom. & ge geseoð mannes sunu on swyðran healfe sittan his mægenes. & cumende mid heofones genipum;",
"63": "Þa cw se heah-sacerd. his reaf slitende. hwi ge-wilnige wé gyt cyðera.",
"64": "ge gehyrdon his bysmer. hwæt þincð eow; Ða hyrwdon hi ealle hine & cwædon þt he wære deaðes scyldig;",
"65": "And sume agunnon him on spætan & ofer-wreon his ansyne. & mid fystum hine beoton. & him to cwædon; Aræd. and þa ðenas hine mid handum beoton;",
"66": "And þa petrus wæs on cafertune þa com to him án þinen þæs heah-sacerdes.",
"67": "& þa heo geseah petrum wyrmende þa cwæð heo; Þu wære mid ðam nazareniscan hælende;",
"68": "Ða æt soc he & cwæð. ic nát. ne ne can hwæt þu segst; And he eode þa of þam cafertune & se hana creow;",
"69": "Eft þa hine gecneow oðer þinen. heo ongan cweðan. to þam þe ðar abutan stodon; Soðlice þes ys of þam;",
"70": "& he eft ætsóc; & eft þa ymbe lytel þa ðe æt-stodon. cwædon to petre. Soþlice þu eart of ðam. galileisc þu eart;",
"71": "Þa ongan he æt-sacan & swerian. soðes ne can ic þæne man þe ge secgað.",
"72": "& þa eft sona creow se hana; Ða gemunde petrus þæs hælendes worde þe he him sæde. ær se hana crawe tua. þriwa ðu me æt-sæcst. þa ongan he wepan;"},

"15": {
"1": "Þa sona on mergen worhton þa heah-sacerdas hyra gemot mid ealdrum. & bocerum & eallum werodum. & læddon þæne hælend gebundenne. & sealdon hine pilato;",
"2": "Ða axode pilatus hine. eart þu iudea cynincg; Þa &swarode he him. þu hit segst;",
"3": "Ða wregdon hine þa heah-sacerdas on manegum þingum;",
"4": "Eft pilatus hine axode. ne &swarast þu nán þing. loca hu mycelum hi þe wregeað;",
"5": "Ða ne &swarode se hælend him na mare. swa þt pilatus wundrode;",
"6": "On symmel-dæge wæs his gewuna þt he him for-geafe ænne gebundenne. swa hwylcne swa hi bædon;",
"7": "Þa bædon hi barraban. se wæs gebunden mid þam ræplingum. se þurh swic-cræft. man-slyht geworhte.",
"8": "& þa he ferde. þa ongan seo menegeo hine biddan swa heo symle dyde;",
"9": "Ða cwæð pilatus; Wylle ge þt ic eow forgyfe iudea cyning.",
"10": "he wiste þt ðurh andan hine sealdon þa heah-sacerdas;",
"11": "Þa astyredon þa bisceopas þa menegu þt he him barraban forgefe;",
"12": "Eft pilatus him andswarode. hwæt do ic be iudea cininge;",
"13": "Hi eft hrymdon & cwædon. hóh hine;",
"14": "Ða sæde pilatus. hwæt yfeles dyde he; Hi þæs þe ma clypedon ahóh hine;",
"15": "Pilatus wolde þa ðam folce gecweman. & for-gef him barraban & sealde him þone hælend beswungenne þt he á-hangen wære;",
"16": "Þa læddon þa cempan hine on þæs domernes cafertún; & hi to-somne eall werod clypedon;",
"17": "& scryddon hine mid purpuran. & him on setton þyrnenne helm awundenne.",
"18": "& ongunnon hine þus gretan. hal wes þu iudea cyning;",
"19": "& beoton hine on þt heafod mid hreode. & spætton him on. & heora cneow bígdon. & hine ge-eaðmeddon;",
"20": "And syððan hi hine bysmrydon. unscryddon hine þam purpuran. & scryddon hine mid his reafum & læddon hine þt hi hine ahengon.",
"21": "& genyddon sumne weg-ferendne simonem cireneum cumende of þam tune alexandres fæder & rufi. þt he his rode bære.",
"22": "& hi læddon hine on ða stowe golgoða þt is on ure geþeode gereht heafod-pannena stow.",
"23": "& sealdon him gebiterod wín & he hit ne on-feng;",
"24": "And þa hi hine ahengon hi dældon his reaf. & hlotu wurpon. hwæt gehwa náme;",
"25": "Þa wæs undern-tíd. & hi ahengon hine.",
"26": "& ofer-gewrit his gyltes wæs awriten iudea cyning.",
"27": "& hi ahengon mid him twegen sceaðan anne on his swyðran healfe. & oþerne on his wynstran.",
"28": "þa wæs þt ge-writ gefylled. þt cwyð; & he wæs mid unriht-wisum geteald;",
"29": "And þa ðe forð-stopon hine gremedon & hyra heafod cwehton. & ðus cwædon; Wala se to-wyrpð þt tempel. & on þrim dagon eft getimbrað.",
"30": "gehæl ðe sylfne of þære rode stigende;",
"31": "Eall-swa þa heah-sacerdas bysmriende betwux þam bocerum cwædon. oðre he hale gedyde. hine sylfne he ne mæg halne gedon;",
"32": "Críst israhela cyning astige nú of rode þt we ge-seon & ge-lyfon; And þa ðe him mid hangodon wæron him mid gebundene;",
"33": "And þære syxtan tide wurdo[n] þystru gewordene geond ealle eorðan. oð nón-tide",
"34": "& to nón-tide se hælend clypode mycelre stemne. heloi. heloi. lema sabbattani. þt is on ure geðeode mín god mín god. hwi for-lete þu me;",
"35": "& sume þe ðar abuton stodon & þis gehyrdon hi cwædon. nu þes clypað heliam.",
"36": "þa árn hyra án & fylde áne spingan mid ecede. & on hreod sette & him drincan sealde. & cwæð; Lætað þt we ge-seon hwæðer helias cume hine nyþer to settanne;",
"37": "Se hælend þa asende his stefne & forð-ferde.",
"38": "& þæs temples wah-rift wæs tosliten on twa of ufewerdum oð neoþewerd;",
"39": "Þa se hundred-man þe ðar stod agén geseah þt se hælend swa clypiende forð-ferde. he cw. soðlice þes man wæs godes sunu;",
"40": "And þa wíf wæron feorran be-healdende. & betwux þam wæs seo magdalenisce maria. & maria iacobes modor. & salomeæ;",
"41": "& þa he wæs on galilea hi fylidon him. & him þenedon & manega oðre þe him mid ferdon on hierusalem;",
"42": "And þa æfen wæs geworden þt wæs parasceue. þt is ær sæter-dæge",
"43": "þa com iosep se æðela gerefa of abarimathia. se sylfa godes rices geanbidode. & he dyrstiglice into pilate eode. & bæd þæs hælendes lic-haman;",
"44": "Ða wundrode pilatus gif he þa gyt forð-ferde; Þa clypode he þæne hundred-man & hine ahsode hwæðer he dead wære;",
"45": "Ða he wiste þt. þa agef he þone lic-haman iosepe;",
"46": "Þa bohte iosep áne scytan. & hine þar-on befeold. & on byrgene lede. seo wæs of stane aheawen. & wylte anne stan to ðære byrgenne dura;",
"47": "Ða com maria magdalene & iosepes maria. & be-heoldon hwar he geled wære;"},

"16": 
{
"1": "& ða sæternes dæg wæs agán. seo magdalenisce maria & iacobes maria & salomeæ bohton wyrt-gemang þt hi comon & hine smyredon;",
"2": "And swyðe ær anum reste-dæge comon to þære byrgene up-asprungenre sunnan.",
"3": "& cwædon him betwynan; Hwa awylt us ðysne stan of þære byrgene dura;",
"4": "Þa hi hi besawon. hi gesawon þæne stan aweg awyltne. soðlice he wæs swyðe mycel;",
"5": "And þa hi eodon on þa byrgene hi gesawon anne geongne on þa swyðran healfe sittende hwitum gegyrlan ofer-wrohne; & hi þa forhtodon;",
"6": "Ða cwæð he to him ne forhtige ge na. ge secað þæne nazareniscan hælend ahangenne; He arás nis he hér; her is seo stow þær hi hine ledon.",
"7": "ac farað & secgað his leorning-cnihtum. & petre þt he gæð toforan eow on galileam. þar ge hine geseoð swa he eow sæde;",
"8": "And hi ut eodon. & flugon fram þære byrgene. & wæron áfærede for þære gesyhðe þe hi gesawon. & hig nanon men naht ne sædon. soðlice hi him adredon;",
"9": "Þa he arás on ærne morgen on reste-dæge. æryst he æt-ywde þære magdaleniscan marian. of ðære he út adraf seofon deofol-seocnyssa.",
"10": "& heo þa ut eode & hit þam cydde þe mid him wæron heofendum & wependum",
"11": "þa hi gehyrdon þt he leofode & hi hine gesawon. þa ne ge-lyfdon hi him.",
"12": "Æfter þam him twam he wæs æt-ywed on oðrum hiwe. him on þone tún farendum",
"13": "& hi þa foron & þt oðrum cyddon. & hi him ne gelyfdon;",
"14": "Ða æt nehstan he ætywde him twelfum þar hi æt-gædere sæton. & tælde hyra ungeleaffulnesse. & hyra heortan heardnesse. forðam þe hi ne ge-lyfdon þam ðe hine gesawon of deaþe arisan.",
"15": "& he sæde him. Farað into ealne middan-eard & bodiað god-spell. ealre gesceafte.",
"16": "Se þe gelyfð & gefullod bið se biþ hal; Soþlice se ðe ne gelyfð. se bið genyðerod;",
"17": "Þas tacnu fyliað þam ðe ge-lyfað. on minon naman hi deofol-seocnessa ut-drifað; hi sprecaþ niwum tungum.",
"18": "næddran hi afyrrað & him ne derað þeah hi hwæt dead-bærlices drincan; Ofer seoce hi hyra handa settað & hi beoð hale;",
"19": "And witudlice drihten hælend syððan he to him spræc. he wæs on heofonum afangen. & he sitt on godes swiðran healfe;",
"20": "Soþlice hi ða farende æghwar bodedon. drihtne mid-wyrcendum & trymmendre spræce æfter-fyligendum tacnum."
}}